//go:build go1.22

// Package httpapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package httpapi

import (
	"errors"
	"fmt"
	"net/http"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ActivityItemKind.
const (
	ActivityItemKindComment ActivityItemKind = "comment"
	ActivityItemKindEvent   ActivityItemKind = "event"
)

// Valid indicates whether the value is a known member of the ActivityItemKind enum.
func (e ActivityItemKind) Valid() bool {
	switch e {
	case ActivityItemKindComment:
		return true
	case ActivityItemKindEvent:
		return true
	default:
		return false
	}
}

// Defines values for DecisionOutcome.
const (
	DecisionOutcomeImplemented DecisionOutcome = "implemented"
	DecisionOutcomeRejected    DecisionOutcome = "rejected"
)

// Valid indicates whether the value is a known member of the DecisionOutcome enum.
func (e DecisionOutcome) Valid() bool {
	switch e {
	case DecisionOutcomeImplemented:
		return true
	case DecisionOutcomeRejected:
		return true
	default:
		return false
	}
}

// Defines values for DecisionState.
const (
	DecisionStateConfirmed DecisionState = "confirmed"
	DecisionStateDraft     DecisionState = "draft"
)

// Valid indicates whether the value is a known member of the DecisionState enum.
func (e DecisionState) Valid() bool {
	switch e {
	case DecisionStateConfirmed:
		return true
	case DecisionStateDraft:
		return true
	default:
		return false
	}
}

// Defines values for Locale.
const (
	LocaleEn Locale = "en"
	LocaleId Locale = "id"
)

// Valid indicates whether the value is a known member of the Locale enum.
func (e Locale) Valid() bool {
	switch e {
	case LocaleEn:
		return true
	case LocaleId:
		return true
	default:
		return false
	}
}

// Defines values for NodeType.
const (
	NodeTypeMenu   NodeType = "menu"
	NodeTypeModule NodeType = "module"
)

// Valid indicates whether the value is a known member of the NodeType enum.
func (e NodeType) Valid() bool {
	switch e {
	case NodeTypeMenu:
		return true
	case NodeTypeModule:
		return true
	default:
		return false
	}
}

// Defines values for Priority.
const (
	PriorityHigh   Priority = "high"
	PriorityLow    Priority = "low"
	PriorityMedium Priority = "medium"
	PriorityUrgent Priority = "urgent"
)

// Valid indicates whether the value is a known member of the Priority enum.
func (e Priority) Valid() bool {
	switch e {
	case PriorityHigh:
		return true
	case PriorityLow:
		return true
	case PriorityMedium:
		return true
	case PriorityUrgent:
		return true
	default:
		return false
	}
}

// Defines values for ProjectRole.
const (
	ProjectRoleAdmin  ProjectRole = "admin"
	ProjectRoleMember ProjectRole = "member"
	ProjectRoleViewer ProjectRole = "viewer"
)

// Valid indicates whether the value is a known member of the ProjectRole enum.
func (e ProjectRole) Valid() bool {
	switch e {
	case ProjectRoleAdmin:
		return true
	case ProjectRoleMember:
		return true
	case ProjectRoleViewer:
		return true
	default:
		return false
	}
}

// Defines values for StatusCategory.
const (
	StatusCategoryCancelled  StatusCategory = "cancelled"
	StatusCategoryDone       StatusCategory = "done"
	StatusCategoryInProgress StatusCategory = "in_progress"
	StatusCategoryTodo       StatusCategory = "todo"
)

// Valid indicates whether the value is a known member of the StatusCategory enum.
func (e StatusCategory) Valid() bool {
	switch e {
	case StatusCategoryCancelled:
		return true
	case StatusCategoryDone:
		return true
	case StatusCategoryInProgress:
		return true
	case StatusCategoryTodo:
		return true
	default:
		return false
	}
}

// Defines values for TicketRequesterKind.
const (
	TicketRequesterKindContact TicketRequesterKind = "contact"
	TicketRequesterKindUser    TicketRequesterKind = "user"
)

// Valid indicates whether the value is a known member of the TicketRequesterKind enum.
func (e TicketRequesterKind) Valid() bool {
	switch e {
	case TicketRequesterKindContact:
		return true
	case TicketRequesterKindUser:
		return true
	default:
		return false
	}
}

// Defines values for TicketType.
const (
	TicketTypeBug           TicketType = "bug"
	TicketTypeChangeRequest TicketType = "change_request"
	TicketTypeFeature       TicketType = "feature"
)

// Valid indicates whether the value is a known member of the TicketType enum.
func (e TicketType) Valid() bool {
	switch e {
	case TicketTypeBug:
		return true
	case TicketTypeChangeRequest:
		return true
	case TicketTypeFeature:
		return true
	default:
		return false
	}
}

// Defines values for ListTicketsParamsMissing.
const (
	ListTicketsParamsMissingMenus  ListTicketsParamsMissing = "menus"
	ListTicketsParamsMissingReason ListTicketsParamsMissing = "reason"
)

// Valid indicates whether the value is a known member of the ListTicketsParamsMissing enum.
func (e ListTicketsParamsMissing) Valid() bool {
	switch e {
	case ListTicketsParamsMissingMenus:
		return true
	case ListTicketsParamsMissingReason:
		return true
	default:
		return false
	}
}

// Defines values for ListTicketsParamsSort.
const (
	ListTicketsParamsSortCreated  ListTicketsParamsSort = "created"
	ListTicketsParamsSortDue      ListTicketsParamsSort = "due"
	ListTicketsParamsSortKey      ListTicketsParamsSort = "key"
	ListTicketsParamsSortPriority ListTicketsParamsSort = "priority"
	ListTicketsParamsSortUpdated  ListTicketsParamsSort = "updated"
)

// Valid indicates whether the value is a known member of the ListTicketsParamsSort enum.
func (e ListTicketsParamsSort) Valid() bool {
	switch e {
	case ListTicketsParamsSortCreated:
		return true
	case ListTicketsParamsSortDue:
		return true
	case ListTicketsParamsSortKey:
		return true
	case ListTicketsParamsSortPriority:
		return true
	case ListTicketsParamsSortUpdated:
		return true
	default:
		return false
	}
}

// ActivityItem defines model for ActivityItem.
type ActivityItem struct {
	// Action Example: transition
	Action *string   `json:"action,omitempty"`
	Actor  *Ref      `json:"actor,omitempty"`
	At     time.Time `json:"at"`

	// Body A comment's text; absent when deleted
	Body      *string                 `json:"body,omitempty"`
	Changes   *map[string]interface{} `json:"changes,omitempty"`
	CommentId *int64                  `json:"comment_id,omitempty"`
	Deleted   *bool                   `json:"deleted,omitempty"`
	Edited    *bool                   `json:"edited,omitempty"`
	Internal  *bool                   `json:"internal,omitempty"`
	Kind      ActivityItemKind        `json:"kind"`
}

// ActivityItemKind defines model for ActivityItem.Kind.
type ActivityItemKind string

// ActivityList defines model for ActivityList.
type ActivityList struct {
	Items []ActivityItem `json:"items"`
}

// Attachment defines model for Attachment.
type Attachment struct {
	ContentType string    `json:"content_type"`
	CreatedAt   time.Time `json:"created_at"`
	Filename    string    `json:"filename"`
	Id          int64     `json:"id"`
	SizeBytes   int64     `json:"size_bytes"`
	Uploader    Ref       `json:"uploader"`
}

// Client defines model for Client.
type Client struct {
	Aliases  []string `json:"aliases"`
	Archived bool     `json:"archived"`

	// Code Example: CLA
	Code *string `json:"code"`
	Id   int64   `json:"id"`
	Name string  `json:"name"`
}

// ClientCreate defines model for ClientCreate.
type ClientCreate struct {
	Aliases *[]string `json:"aliases,omitempty"`
	Code    *string   `json:"code,omitempty"`
	Name    string    `json:"name"`
}

// ClientList defines model for ClientList.
type ClientList struct {
	Items []Client `json:"items"`
}

// ClientUpdate defines model for ClientUpdate.
type ClientUpdate struct {
	Aliases  *[]string `json:"aliases,omitempty"`
	Archived *bool     `json:"archived,omitempty"`
	Code     *string   `json:"code,omitempty"`
	Name     *string   `json:"name,omitempty"`
}

// CommentInput defines model for CommentInput.
type CommentInput struct {
	Body string `json:"body"`

	// Internal Defaults to true; false marks the comment client-safe.
	Internal *bool `json:"internal,omitempty"`
}

// CommentUpdate defines model for CommentUpdate.
type CommentUpdate struct {
	Body string `json:"body"`
}

// Contact defines model for Contact.
type Contact struct {
	ClientId   *int64  `json:"client_id"`
	ClientName *string `json:"client_name"`
	Email      *string `json:"email"`
	Id         int64   `json:"id"`
	Name       string  `json:"name"`
	Phone      *string `json:"phone"`
	Title      *string `json:"title"`
}

// ContactInput defines model for ContactInput.
type ContactInput struct {
	// ClientId Omitted for internal people.
	ClientId *int64  `json:"client_id,omitempty"`
	Email    *string `json:"email,omitempty"`
	Name     string  `json:"name"`
	Phone    *string `json:"phone,omitempty"`
	Title    *string `json:"title,omitempty"`
}

// ContactList defines model for ContactList.
type ContactList struct {
	Items []Contact `json:"items"`
}

// CreatedUser defines model for CreatedUser.
type CreatedUser struct {
	SetupLink SetupLink `json:"setup_link"`
	User      User      `json:"user"`
}

// DecisionInput defines model for DecisionInput.
type DecisionInput struct {
	Alternatives *string `json:"alternatives,omitempty"`
	WhatChanged  string  `json:"what_changed"`
	Why          string  `json:"why"`
}

// DecisionOutcome defines model for DecisionOutcome.
type DecisionOutcome string

// DecisionRecord defines model for DecisionRecord.
type DecisionRecord struct {
	Alternatives string          `json:"alternatives"`
	ConfirmedAt  *time.Time      `json:"confirmed_at,omitempty"`
	ConfirmedBy  *Ref            `json:"confirmed_by,omitempty"`
	Outcome      DecisionOutcome `json:"outcome"`
	State        DecisionState   `json:"state"`
	WhatChanged  string          `json:"what_changed"`
	Why          string          `json:"why"`
}

// DecisionState defines model for DecisionState.
type DecisionState string

// FieldError defines model for FieldError.
type FieldError struct {
	Code    string `json:"code"`
	Field   string `json:"field"`
	Message string `json:"message"`
}

// Locale defines model for Locale.
type Locale string

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// MeUpdate defines model for MeUpdate.
type MeUpdate struct {
	CurrentPassword *string `json:"current_password,omitempty"`
	Locale          *Locale `json:"locale,omitempty"`
	Name            *string `json:"name,omitempty"`
	NewPassword     *string `json:"new_password,omitempty"`
	Timezone        *string `json:"timezone,omitempty"`
}

// Member defines model for Member.
type Member struct {
	AllClients bool        `json:"all_clients"`
	ClientIds  []int64     `json:"client_ids"`
	Email      string      `json:"email"`
	Name       string      `json:"name"`
	Role       ProjectRole `json:"role"`
	UserId     int64       `json:"user_id"`
}

// MemberInput defines model for MemberInput.
type MemberInput struct {
	// AllClients Project admins always have all clients.
	AllClients bool `json:"all_clients"`

	// ClientIds The clients a scoped member sees; ignored with all_clients.
	ClientIds *[]int64    `json:"client_ids,omitempty"`
	Email     string      `json:"email"`
	Role      ProjectRole `json:"role"`
}

// MemberList defines model for MemberList.
type MemberList struct {
	Items []Member `json:"items"`
}

// MembersUpdate defines model for MembersUpdate.
type MembersUpdate struct {
	Members []MemberInput `json:"members"`
}

// Node defines model for Node.
type Node struct {
	Aliases        []string `json:"aliases"`
	Archived       bool     `json:"archived"`
	ClientSpecific bool     `json:"client_specific"`

	// Clients The node's clients within the caller's scope.
	Clients []NodeClient `json:"clients"`

	// Code Example: HR.ATT.OT_APPROVAL
	Code        *string  `json:"code"`
	Description string   `json:"description"`
	Id          int64    `json:"id"`
	Name        string   `json:"name"`
	ParentId    *int64   `json:"parent_id"`
	Position    int32    `json:"position"`
	Type        NodeType `json:"type"`
}

// NodeClient defines model for NodeClient.
type NodeClient struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

// NodeCreate defines model for NodeCreate.
type NodeCreate struct {
	Aliases        *[]string `json:"aliases,omitempty"`
	ClientIds      *[]int64  `json:"client_ids,omitempty"`
	ClientSpecific *bool     `json:"client_specific,omitempty"`
	Code           *string   `json:"code,omitempty"`
	Description    *string   `json:"description,omitempty"`
	Name           string    `json:"name"`
	ParentId       *int64    `json:"parent_id,omitempty"`
	Type           NodeType  `json:"type"`
}

// NodeList defines model for NodeList.
type NodeList struct {
	Items []Node `json:"items"`
}

// NodeMove defines model for NodeMove.
type NodeMove struct {
	// ParentId Omitted or null moves to the top level.
	ParentId *int64 `json:"parent_id,omitempty"`

	// Position Index among the new siblings; omitted puts the node last.
	Position *int32 `json:"position,omitempty"`
}

// NodeRef defines model for NodeRef.
type NodeRef struct {
	Archived bool   `json:"archived"`
	Id       int64  `json:"id"`
	Name     string `json:"name"`
}

// NodeType defines model for NodeType.
type NodeType string

// NodeUpdate defines model for NodeUpdate.
type NodeUpdate struct {
	Aliases *[]string `json:"aliases,omitempty"`

	// Archived Archive (true) or restore (false); a linked node is archived
	Archived  *bool    `json:"archived,omitempty"`
	ClientIds *[]int64 `json:"client_ids,omitempty"`

	// ClientSpecific When present
	ClientSpecific *bool `json:"client_specific,omitempty"`

	// Code An empty code clears it.
	Code        *string   `json:"code,omitempty"`
	Description *string   `json:"description,omitempty"`
	Move        *NodeMove `json:"move,omitempty"`
	Name        *string   `json:"name,omitempty"`
	Type        *NodeType `json:"type,omitempty"`
}

// Priority defines model for Priority.
type Priority string

// Problem defines model for Problem.
type Problem struct {
	Code   string        `json:"code"`
	Detail *string       `json:"detail,omitempty"`
	Errors *[]FieldError `json:"errors,omitempty"`
	Status int           `json:"status"`
	Title  string        `json:"title"`
	Type   string        `json:"type"`
}

// Project defines model for Project.
type Project struct {
	CreatedAt   time.Time `json:"created_at"`
	Description string    `json:"description"`
	Id          int64     `json:"id"`

	// Key Example: HRIS
	Key  string      `json:"key"`
	Name string      `json:"name"`
	Role ProjectRole `json:"role"`
}

// ProjectClientsUpdate defines model for ProjectClientsUpdate.
type ProjectClientsUpdate struct {
	ClientIds []int64 `json:"client_ids"`
}

// ProjectCreate defines model for ProjectCreate.
type ProjectCreate struct {
	Description *string `json:"description,omitempty"`

	// Key 2–10 capital letters or digits, starting with a letter; lower case is accepted
	Key  string `json:"key"`
	Name string `json:"name"`
}

// ProjectList defines model for ProjectList.
type ProjectList struct {
	Items []Project `json:"items"`
}

// ProjectRole defines model for ProjectRole.
type ProjectRole string

// ProjectUpdate defines model for ProjectUpdate.
type ProjectUpdate struct {
	Description *string `json:"description,omitempty"`
	Key         *string `json:"key,omitempty"`
	Name        *string `json:"name,omitempty"`
}

// Ref defines model for Ref.
type Ref struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

// RefList defines model for RefList.
type RefList struct {
	Items []Ref `json:"items"`
}

// SetupLink defines model for SetupLink.
type SetupLink struct {
	ExpiresAt time.Time `json:"expires_at"`
	Url       string    `json:"url"`
}

// SetupRequest defines model for SetupRequest.
type SetupRequest struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// Status defines model for Status.
type Status struct {
	Category StatusCategory `json:"category"`

	// Color Example: #2563EB
	Color     string `json:"color"`
	Id        int64  `json:"id"`
	IsDefault bool   `json:"is_default"`
	Name      string `json:"name"`
	Position  int32  `json:"position"`
}

// StatusCategory defines model for StatusCategory.
type StatusCategory string

// StatusInput defines model for StatusInput.
type StatusInput struct {
	Category StatusCategory `json:"category"`

	// Color Example: #2563EB
	Color string `json:"color"`

	// Id An existing status; omitted adds one.
	Id        *int64 `json:"id,omitempty"`
	IsDefault *bool  `json:"is_default,omitempty"`
	Name      string `json:"name"`
}

// StatusList defines model for StatusList.
type StatusList struct {
	Items []Status `json:"items"`
}

// StatusMove defines model for StatusMove.
type StatusMove struct {
	// From A removed status.
	From int64 `json:"from"`

	// To A kept status of the same open or closed kind.
	To int64 `json:"to"`
}

// StatusesUpdate defines model for StatusesUpdate.
type StatusesUpdate struct {
	MoveTo   *[]StatusMove `json:"move_to,omitempty"`
	Statuses []StatusInput `json:"statuses"`
}

// Ticket defines model for Ticket.
type Ticket struct {
	Assignee    *Ref         `json:"assignee,omitempty"`
	Attachments []Attachment `json:"attachments"`
	Client      *Ref         `json:"client,omitempty"`

	// ClosedAt Set on close
	ClosedAt    *time.Time          `json:"closed_at,omitempty"`
	CreatedAt   time.Time           `json:"created_at"`
	Decision    *DecisionRecord     `json:"decision,omitempty"`
	Description string              `json:"description"`
	DueDate     *openapi_types.Date `json:"due_date"`
	Id          int64               `json:"id"`

	// Key Example: HRIS-231
	Key        string          `json:"key"`
	Nodes      []NodeRef       `json:"nodes"`
	Priority   Priority        `json:"priority"`
	ProjectKey string          `json:"project_key"`
	Reason     string          `json:"reason"`
	Reporter   Ref             `json:"reporter"`
	Requester  TicketRequester `json:"requester"`
	Status     Status          `json:"status"`
	Title      string          `json:"title"`
	Type       TicketType      `json:"type"`
	UpdatedAt  time.Time       `json:"updated_at"`
	Version    int32           `json:"version"`
}

// TicketCreate defines model for TicketCreate.
type TicketCreate struct {
	AssigneeId *int64 `json:"assignee_id,omitempty"`

	// ClientId Omitted for core work (all clients).
	ClientId           *int64              `json:"client_id,omitempty"`
	Description        *string             `json:"description,omitempty"`
	DueDate            *openapi_types.Date `json:"due_date,omitempty"`
	NodeIds            []int64             `json:"node_ids"`
	Priority           *Priority           `json:"priority,omitempty"`
	Reason             *string             `json:"reason,omitempty"`
	RequesterContactId *int64              `json:"requester_contact_id,omitempty"`

	// RequesterUserId Without a requester the reporter is the requester.
	RequesterUserId *int64 `json:"requester_user_id,omitempty"`

	// StatusId An open status; omitted means the project's default.
	StatusId *int64     `json:"status_id,omitempty"`
	Title    string     `json:"title"`
	Type     TicketType `json:"type"`
}

// TicketPage defines model for TicketPage.
type TicketPage struct {
	Items      []TicketSummary `json:"items"`
	NextCursor *string         `json:"next_cursor"`
}

// TicketRequester defines model for TicketRequester.
type TicketRequester struct {
	Id   int64               `json:"id"`
	Kind TicketRequesterKind `json:"kind"`
	Name string              `json:"name"`

	// Title Example: HR Manager
	Title *string `json:"title"`
}

// TicketRequesterKind defines model for TicketRequester.Kind.
type TicketRequesterKind string

// TicketSummary defines model for TicketSummary.
type TicketSummary struct {
	Assignee      *Ref                `json:"assignee,omitempty"`
	Client        *Ref                `json:"client,omitempty"`
	DueDate       *openapi_types.Date `json:"due_date"`
	Id            int64               `json:"id"`
	Key           string              `json:"key"`
	MissingReason bool                `json:"missing_reason"`
	NodeNames     []string            `json:"node_names"`
	Priority      Priority            `json:"priority"`
	RequesterName string              `json:"requester_name"`
	StatusId      int64               `json:"status_id"`
	Title         string              `json:"title"`
	Type          TicketType          `json:"type"`
	UpdatedAt     time.Time           `json:"updated_at"`
}

// TicketType defines model for TicketType.
type TicketType string

// TicketUpdate Replaces every editable field; send the current value of each field you keep.
type TicketUpdate struct {
	AssigneeId *int64 `json:"assignee_id,omitempty"`

	// ClientId Omitted for core work (all clients).
	ClientId           *int64              `json:"client_id,omitempty"`
	Description        *string             `json:"description,omitempty"`
	DueDate            *openapi_types.Date `json:"due_date,omitempty"`
	NodeIds            []int64             `json:"node_ids"`
	Priority           *Priority           `json:"priority,omitempty"`
	Reason             *string             `json:"reason,omitempty"`
	RequesterContactId *int64              `json:"requester_contact_id,omitempty"`

	// RequesterUserId One of the two requester fields is required.
	RequesterUserId *int64     `json:"requester_user_id,omitempty"`
	Title           string     `json:"title"`
	Type            TicketType `json:"type"`
}

// TransitionRequest defines model for TransitionRequest.
type TransitionRequest struct {
	Decision *DecisionInput `json:"decision,omitempty"`

	// NodeIds A close only; replaces the ticket's menus.
	NodeIds *[]int64 `json:"node_ids,omitempty"`

	// Reason A close only; replaces the ticket's reason.
	Reason   *string `json:"reason,omitempty"`
	StatusId int64   `json:"status_id"`
}

// User defines model for User.
type User struct {
	CreatedAt   time.Time  `json:"created_at"`
	Disabled    bool       `json:"disabled"`
	Email       string     `json:"email"`
	HasPassword bool       `json:"has_password"`
	Id          int64      `json:"id"`
	IsAdmin     bool       `json:"is_admin"`
	LastLoginAt *time.Time `json:"last_login_at"`
	Locale      Locale     `json:"locale"`
	Name        string     `json:"name"`

	// Timezone Example: Asia/Jakarta
	Timezone string `json:"timezone"`
}

// UserCreate defines model for UserCreate.
type UserCreate struct {
	Email    string  `json:"email"`
	IsAdmin  *bool   `json:"is_admin,omitempty"`
	Locale   *Locale `json:"locale,omitempty"`
	Name     string  `json:"name"`
	Timezone *string `json:"timezone,omitempty"`
}

// UserList defines model for UserList.
type UserList struct {
	Items []User `json:"items"`
}

// UserUpdate defines model for UserUpdate.
type UserUpdate struct {
	Disabled *bool   `json:"disabled,omitempty"`
	IsAdmin  *bool   `json:"is_admin,omitempty"`
	Locale   *Locale `json:"locale,omitempty"`
	Name     *string `json:"name,omitempty"`
	Timezone *string `json:"timezone,omitempty"`
}

// ListContactsParams defines parameters for ListContacts.
type ListContactsParams struct {
	Q        *string `form:"q,omitempty" json:"q,omitempty"`
	ClientId *int64  `form:"client_id,omitempty" json:"client_id,omitempty"`

	// Internal Only internal people (no client).
	Internal *bool `form:"internal,omitempty" json:"internal,omitempty"`
}

// ListNodesParams defines parameters for ListNodes.
type ListNodesParams struct {
	// Archived Project admins only; also list archived nodes.
	Archived *bool `form:"archived,omitempty" json:"archived,omitempty"`
}

// ListTicketsParams defines parameters for ListTickets.
type ListTicketsParams struct {
	StatusId *int64          `form:"status_id,omitempty" json:"status_id,omitempty"`
	Category *StatusCategory `form:"category,omitempty" json:"category,omitempty"`

	// Open Only To do and In progress statuses.
	Open *bool `form:"open,omitempty" json:"open,omitempty"`

	// ClosedDays Closed tickets only when closed within this many days; the board asks for 14.
	ClosedDays *int32      `form:"closed_days,omitempty" json:"closed_days,omitempty"`
	Type       *TicketType `form:"type,omitempty" json:"type,omitempty"`
	ClientId   *int64      `form:"client_id,omitempty" json:"client_id,omitempty"`

	// Core Only core work (no client).
	Core       *bool  `form:"core,omitempty" json:"core,omitempty"`
	AssigneeId *int64 `form:"assignee_id,omitempty" json:"assignee_id,omitempty"`

	// Mine Only tickets assigned to the caller.
	Mine *bool `form:"mine,omitempty" json:"mine,omitempty"`

	// NodeId Tickets on this node or its sub-nodes.
	NodeId *int64 `form:"node_id,omitempty" json:"node_id,omitempty"`

	// Q Words in the title
	Q       *string                   `form:"q,omitempty" json:"q,omitempty"`
	Missing *ListTicketsParamsMissing `form:"missing,omitempty" json:"missing,omitempty"`
	Sort    *ListTicketsParamsSort    `form:"sort,omitempty" json:"sort,omitempty"`
	Limit   *int32                    `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor  *string                   `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListTicketsParamsMissing defines parameters for ListTickets.
type ListTicketsParamsMissing string

// ListTicketsParamsSort defines parameters for ListTickets.
type ListTicketsParamsSort string

// UpdateTicketParams defines parameters for UpdateTicket.
type UpdateTicketParams struct {
	IfMatch string `json:"If-Match"`
}

// UploadAttachmentMultipartBody defines parameters for UploadAttachment.
type UploadAttachmentMultipartBody struct {
	File openapi_types.File `json:"file"`
}

// TransitionTicketParams defines parameters for TransitionTicket.
type TransitionTicketParams struct {
	IfMatch *string `json:"If-Match,omitempty"`
}

// CreateUserJSONRequestBody defines body for CreateUser for application/json ContentType.
type CreateUserJSONRequestBody = UserCreate

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = UserUpdate

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// SetupPasswordJSONRequestBody defines body for SetupPassword for application/json ContentType.
type SetupPasswordJSONRequestBody = SetupRequest

// CreateClientJSONRequestBody defines body for CreateClient for application/json ContentType.
type CreateClientJSONRequestBody = ClientCreate

// UpdateClientJSONRequestBody defines body for UpdateClient for application/json ContentType.
type UpdateClientJSONRequestBody = ClientUpdate

// UpdateCommentJSONRequestBody defines body for UpdateComment for application/json ContentType.
type UpdateCommentJSONRequestBody = CommentUpdate

// CreateContactJSONRequestBody defines body for CreateContact for application/json ContentType.
type CreateContactJSONRequestBody = ContactInput

// UpdateContactJSONRequestBody defines body for UpdateContact for application/json ContentType.
type UpdateContactJSONRequestBody = ContactInput

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = MeUpdate

// UpdateNodeJSONRequestBody defines body for UpdateNode for application/json ContentType.
type UpdateNodeJSONRequestBody = NodeUpdate

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = ProjectCreate

// UpdateProjectJSONRequestBody defines body for UpdateProject for application/json ContentType.
type UpdateProjectJSONRequestBody = ProjectUpdate

// SetProjectClientsJSONRequestBody defines body for SetProjectClients for application/json ContentType.
type SetProjectClientsJSONRequestBody = ProjectClientsUpdate

// SetProjectMembersJSONRequestBody defines body for SetProjectMembers for application/json ContentType.
type SetProjectMembersJSONRequestBody = MembersUpdate

// CreateNodeJSONRequestBody defines body for CreateNode for application/json ContentType.
type CreateNodeJSONRequestBody = NodeCreate

// SetStatusesJSONRequestBody defines body for SetStatuses for application/json ContentType.
type SetStatusesJSONRequestBody = StatusesUpdate

// CreateTicketJSONRequestBody defines body for CreateTicket for application/json ContentType.
type CreateTicketJSONRequestBody = TicketCreate

// UpdateTicketJSONRequestBody defines body for UpdateTicket for application/json ContentType.
type UpdateTicketJSONRequestBody = TicketUpdate

// UploadAttachmentMultipartRequestBody defines body for UploadAttachment for multipart/form-data ContentType.
type UploadAttachmentMultipartRequestBody UploadAttachmentMultipartBody

// CreateCommentJSONRequestBody defines body for CreateComment for application/json ContentType.
type CreateCommentJSONRequestBody = CommentInput

// UpdateDecisionJSONRequestBody defines body for UpdateDecision for application/json ContentType.
type UpdateDecisionJSONRequestBody = DecisionInput

// TransitionTicketJSONRequestBody defines body for TransitionTicket for application/json ContentType.
type TransitionTicketJSONRequestBody = TransitionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /admin/users)
	ListUsers(w http.ResponseWriter, r *http.Request)

	// (POST /admin/users)
	CreateUser(w http.ResponseWriter, r *http.Request)

	// (PATCH /admin/users/{id})
	UpdateUser(w http.ResponseWriter, r *http.Request, id int64)

	// (POST /admin/users/{id}/setup-link)
	CreateSetupLink(w http.ResponseWriter, r *http.Request, id int64)

	// (DELETE /attachments/{id})
	DeleteAttachment(w http.ResponseWriter, r *http.Request, id int64)

	// (GET /attachments/{id})
	DownloadAttachment(w http.ResponseWriter, r *http.Request, id int64)

	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)

	// (POST /auth/logout)
	Logout(w http.ResponseWriter, r *http.Request)

	// (POST /auth/setup)
	SetupPassword(w http.ResponseWriter, r *http.Request)

	// (GET /clients)
	ListClients(w http.ResponseWriter, r *http.Request)

	// (POST /clients)
	CreateClient(w http.ResponseWriter, r *http.Request)

	// (PATCH /clients/{id})
	UpdateClient(w http.ResponseWriter, r *http.Request, id int64)

	// (DELETE /comments/{id})
	DeleteComment(w http.ResponseWriter, r *http.Request, id int64)

	// (PATCH /comments/{id})
	UpdateComment(w http.ResponseWriter, r *http.Request, id int64)

	// (GET /contacts)
	ListContacts(w http.ResponseWriter, r *http.Request, params ListContactsParams)

	// (POST /contacts)
	CreateContact(w http.ResponseWriter, r *http.Request)

	// (PATCH /contacts/{id})
	UpdateContact(w http.ResponseWriter, r *http.Request, id int64)

	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)

	// (PATCH /me)
	UpdateMe(w http.ResponseWriter, r *http.Request)

	// (DELETE /nodes/{id})
	DeleteNode(w http.ResponseWriter, r *http.Request, id int64)

	// (PATCH /nodes/{id})
	UpdateNode(w http.ResponseWriter, r *http.Request, id int64)

	// (GET /projects)
	ListProjects(w http.ResponseWriter, r *http.Request)

	// (POST /projects)
	CreateProject(w http.ResponseWriter, r *http.Request)

	// (GET /projects/{key})
	GetProject(w http.ResponseWriter, r *http.Request, key string)

	// (PATCH /projects/{key})
	UpdateProject(w http.ResponseWriter, r *http.Request, key string)

	// (GET /projects/{key}/assignees)
	ListAssignees(w http.ResponseWriter, r *http.Request, key string)

	// (GET /projects/{key}/clients)
	ListProjectClients(w http.ResponseWriter, r *http.Request, key string)

	// (PUT /projects/{key}/clients)
	SetProjectClients(w http.ResponseWriter, r *http.Request, key string)

	// (GET /projects/{key}/members)
	ListProjectMembers(w http.ResponseWriter, r *http.Request, key string)

	// (PUT /projects/{key}/members)
	SetProjectMembers(w http.ResponseWriter, r *http.Request, key string)

	// (GET /projects/{key}/nodes)
	ListNodes(w http.ResponseWriter, r *http.Request, key string, params ListNodesParams)

	// (POST /projects/{key}/nodes)
	CreateNode(w http.ResponseWriter, r *http.Request, key string)

	// (GET /projects/{key}/statuses)
	GetStatuses(w http.ResponseWriter, r *http.Request, key string)

	// (PUT /projects/{key}/statuses)
	SetStatuses(w http.ResponseWriter, r *http.Request, key string)

	// (GET /projects/{key}/tickets)
	ListTickets(w http.ResponseWriter, r *http.Request, key string, params ListTicketsParams)

	// (POST /projects/{key}/tickets)
	CreateTicket(w http.ResponseWriter, r *http.Request, key string)

	// (GET /tickets/{key})
	GetTicket(w http.ResponseWriter, r *http.Request, key string)

	// (PUT /tickets/{key})
	UpdateTicket(w http.ResponseWriter, r *http.Request, key string, params UpdateTicketParams)

	// (GET /tickets/{key}/activity)
	GetTicketActivity(w http.ResponseWriter, r *http.Request, key string)

	// (POST /tickets/{key}/attachments)
	UploadAttachment(w http.ResponseWriter, r *http.Request, key string)

	// (POST /tickets/{key}/comments)
	CreateComment(w http.ResponseWriter, r *http.Request, key string)

	// (PUT /tickets/{key}/decision)
	UpdateDecision(w http.ResponseWriter, r *http.Request, key string)

	// (POST /tickets/{key}/transition)
	TransitionTicket(w http.ResponseWriter, r *http.Request, key string, params TransitionTicketParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateUser operation middleware
func (siw *ServerInterfaceWrapper) CreateUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUser(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSetupLink operation middleware
func (siw *ServerInterfaceWrapper) CreateSetupLink(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSetupLink(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteAttachment operation middleware
func (siw *ServerInterfaceWrapper) DeleteAttachment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteAttachment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DownloadAttachment operation middleware
func (siw *ServerInterfaceWrapper) DownloadAttachment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DownloadAttachment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetupPassword operation middleware
func (siw *ServerInterfaceWrapper) SetupPassword(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetupPassword(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListClients operation middleware
func (siw *ServerInterfaceWrapper) ListClients(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClients(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateClient operation middleware
func (siw *ServerInterfaceWrapper) CreateClient(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateClient(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateClient operation middleware
func (siw *ServerInterfaceWrapper) UpdateClient(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateClient(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteComment operation middleware
func (siw *ServerInterfaceWrapper) DeleteComment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteComment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateComment operation middleware
func (siw *ServerInterfaceWrapper) UpdateComment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateComment(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListContacts operation middleware
func (siw *ServerInterfaceWrapper) ListContacts(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListContactsParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "client_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "client_id", r.URL.Query(), &params.ClientId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "client_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "client_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "internal" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "internal", r.URL.Query(), &params.Internal, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "internal"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "internal", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListContacts(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateContact operation middleware
func (siw *ServerInterfaceWrapper) CreateContact(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateContact(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateContact operation middleware
func (siw *ServerInterfaceWrapper) UpdateContact(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateContact(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMe operation middleware
func (siw *ServerInterfaceWrapper) UpdateMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteNode operation middleware
func (siw *ServerInterfaceWrapper) DeleteNode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateNode operation middleware
func (siw *ServerInterfaceWrapper) UpdateNode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateNode(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjects operation middleware
func (siw *ServerInterfaceWrapper) ListProjects(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjects(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateProject operation middleware
func (siw *ServerInterfaceWrapper) CreateProject(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateProject(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetProject operation middleware
func (siw *ServerInterfaceWrapper) GetProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetProject(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateProject operation middleware
func (siw *ServerInterfaceWrapper) UpdateProject(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateProject(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAssignees operation middleware
func (siw *ServerInterfaceWrapper) ListAssignees(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAssignees(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjectClients operation middleware
func (siw *ServerInterfaceWrapper) ListProjectClients(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjectClients(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetProjectClients operation middleware
func (siw *ServerInterfaceWrapper) SetProjectClients(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetProjectClients(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListProjectMembers operation middleware
func (siw *ServerInterfaceWrapper) ListProjectMembers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListProjectMembers(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetProjectMembers operation middleware
func (siw *ServerInterfaceWrapper) SetProjectMembers(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetProjectMembers(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListNodes operation middleware
func (siw *ServerInterfaceWrapper) ListNodes(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNodesParams

	// ------------- Optional query parameter "archived" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "archived", r.URL.Query(), &params.Archived, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "archived"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "archived", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListNodes(w, r, key, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateNode operation middleware
func (siw *ServerInterfaceWrapper) CreateNode(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateNode(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetStatuses operation middleware
func (siw *ServerInterfaceWrapper) GetStatuses(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetStatuses(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SetStatuses operation middleware
func (siw *ServerInterfaceWrapper) SetStatuses(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SetStatuses(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListTickets operation middleware
func (siw *ServerInterfaceWrapper) ListTickets(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListTicketsParams

	// ------------- Optional query parameter "status_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "status_id", r.URL.Query(), &params.StatusId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "status_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", r.URL.Query(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "category"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "category", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "open" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "open", r.URL.Query(), &params.Open, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "open"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "open", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "closed_days" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "closed_days", r.URL.Query(), &params.ClosedDays, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "closed_days"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "closed_days", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "type" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "type", r.URL.Query(), &params.Type, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "type"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "type", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "client_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "client_id", r.URL.Query(), &params.ClientId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "client_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "client_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "core" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "core", r.URL.Query(), &params.Core, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "core"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "core", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "assignee_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "assignee_id", r.URL.Query(), &params.AssigneeId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "assignee_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "assignee_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "mine" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "mine", r.URL.Query(), &params.Mine, runtime.BindQueryParameterOptions{Type: "boolean", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "mine"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "mine", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "node_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "node_id", r.URL.Query(), &params.NodeId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "node_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "node_id", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "missing" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "missing", r.URL.Query(), &params.Missing, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "missing"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "missing", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "sort" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "sort", r.URL.Query(), &params.Sort, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "sort"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sort", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: "int32"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListTickets(w, r, key, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateTicket operation middleware
func (siw *ServerInterfaceWrapper) CreateTicket(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateTicket(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTicket operation middleware
func (siw *ServerInterfaceWrapper) GetTicket(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTicket(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateTicket operation middleware
func (siw *ServerInterfaceWrapper) UpdateTicket(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params UpdateTicketParams

	headers := r.Header

	// ------------- Required header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = IfMatch

	} else {
		err := fmt.Errorf("Header parameter If-Match is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "If-Match", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateTicket(w, r, key, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetTicketActivity operation middleware
func (siw *ServerInterfaceWrapper) GetTicketActivity(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetTicketActivity(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UploadAttachment operation middleware
func (siw *ServerInterfaceWrapper) UploadAttachment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UploadAttachment(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateComment operation middleware
func (siw *ServerInterfaceWrapper) CreateComment(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateComment(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateDecision operation middleware
func (siw *ServerInterfaceWrapper) UpdateDecision(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateDecision(w, r, key)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// TransitionTicket operation middleware
func (siw *ServerInterfaceWrapper) TransitionTicket(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "key" -------------
	var key string

	err = runtime.BindStyledParameterWithOptions("simple", "key", r.PathValue("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "key", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params TransitionTicketParams

	headers := r.Header

	// ------------- Optional header parameter "If-Match" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("If-Match")]; found {
		var IfMatch string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "If-Match", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "If-Match", valueList[0], &IfMatch, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: false, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "If-Match", Err: err})
			return
		}

		params.IfMatch = &IfMatch

	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.TransitionTicket(w, r, key, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/login", wrapper.Login)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/logout", wrapper.Logout)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/auth/setup", wrapper.SetupPassword)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/me", wrapper.GetMe)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/me", wrapper.UpdateMe)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/admin/users", wrapper.ListUsers)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/admin/users", wrapper.CreateUser)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/admin/users/{id}", wrapper.UpdateUser)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/admin/users/{id}/setup-link", wrapper.CreateSetupLink)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects", wrapper.ListProjects)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects", wrapper.CreateProject)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{key}", wrapper.GetProject)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/projects/{key}", wrapper.UpdateProject)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{key}/clients", wrapper.ListProjectClients)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/projects/{key}/clients", wrapper.SetProjectClients)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/clients", wrapper.ListClients)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/clients", wrapper.CreateClient)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/clients/{id}", wrapper.UpdateClient)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{key}/members", wrapper.ListProjectMembers)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/projects/{key}/members", wrapper.SetProjectMembers)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/contacts", wrapper.ListContacts)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/contacts", wrapper.CreateContact)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/contacts/{id}", wrapper.UpdateContact)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{key}/nodes", wrapper.ListNodes)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{key}/nodes", wrapper.CreateNode)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/nodes/{id}", wrapper.DeleteNode)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/nodes/{id}", wrapper.UpdateNode)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{key}/statuses", wrapper.GetStatuses)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/projects/{key}/statuses", wrapper.SetStatuses)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{key}/assignees", wrapper.ListAssignees)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/projects/{key}/tickets", wrapper.ListTickets)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/projects/{key}/tickets", wrapper.CreateTicket)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/tickets/{key}", wrapper.GetTicket)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/tickets/{key}", wrapper.UpdateTicket)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/tickets/{key}/transition", wrapper.TransitionTicket)
	m.HandleFunc(http.MethodPut+" "+options.BaseURL+"/tickets/{key}/decision", wrapper.UpdateDecision)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/tickets/{key}/activity", wrapper.GetTicketActivity)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/tickets/{key}/comments", wrapper.CreateComment)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/comments/{id}", wrapper.DeleteComment)
	m.HandleFunc(http.MethodPatch+" "+options.BaseURL+"/comments/{id}", wrapper.UpdateComment)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/tickets/{key}/attachments", wrapper.UploadAttachment)
	m.HandleFunc(http.MethodDelete+" "+options.BaseURL+"/attachments/{id}", wrapper.DeleteAttachment)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/attachments/{id}", wrapper.DownloadAttachment)

	return m
}
