// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ask.sql

package db

import (
	"context"
	"time"
)

const createThread = `-- name: CreateThread :one
INSERT INTO ask_threads (user_id, title) VALUES ($1, $2) RETURNING id, user_id, title, created_at, hidden_at
`

type CreateThreadParams struct {
	UserID int64
	Title  string
}

func (q *Queries) CreateThread(ctx context.Context, arg CreateThreadParams) (AskThread, error) {
	row := q.db.QueryRow(ctx, createThread, arg.UserID, arg.Title)
	var i AskThread
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.HiddenAt,
	)
	return i, err
}

const getThread = `-- name: GetThread :one
SELECT id, user_id, title, created_at, hidden_at FROM ask_threads WHERE id = $1 AND user_id = $2 AND hidden_at IS NULL
`

type GetThreadParams struct {
	ID     int64
	UserID int64
}

// A thread is private to its owner (§10.6); a hidden one is gone for them.
func (q *Queries) GetThread(ctx context.Context, arg GetThreadParams) (AskThread, error) {
	row := q.db.QueryRow(ctx, getThread, arg.ID, arg.UserID)
	var i AskThread
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.HiddenAt,
	)
	return i, err
}

const hideThread = `-- name: HideThread :execrows
UPDATE ask_threads SET hidden_at = now() WHERE id = $1 AND user_id = $2 AND hidden_at IS NULL
`

type HideThreadParams struct {
	ID     int64
	UserID int64
}

// The log keeps the thread until retention expires (§10.6).
func (q *Queries) HideThread(ctx context.Context, arg HideThreadParams) (int64, error) {
	result, err := q.db.Exec(ctx, hideThread, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertAskQuery = `-- name: InsertAskQuery :one
INSERT INTO ask_queries (thread_id, user_id, question, lang, scope, evidence, llm_called, status, answer, dropped, model, latency_ms, first_claim_ms)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id
`

type InsertAskQueryParams struct {
	ThreadID     *int64
	UserID       int64
	Question     string
	Lang         string
	Scope        []byte
	Evidence     []byte
	LlmCalled    bool
	Status       string
	Answer       []byte
	Dropped      []byte
	Model        *string
	LatencyMs    *int32
	FirstClaimMs *int32
}

func (q *Queries) InsertAskQuery(ctx context.Context, arg InsertAskQueryParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertAskQuery,
		arg.ThreadID,
		arg.UserID,
		arg.Question,
		arg.Lang,
		arg.Scope,
		arg.Evidence,
		arg.LlmCalled,
		arg.Status,
		arg.Answer,
		arg.Dropped,
		arg.Model,
		arg.LatencyMs,
		arg.FirstClaimMs,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listThreadQueries = `-- name: ListThreadQueries :many
SELECT id, question, lang, status, answer, model, created_at FROM ask_queries WHERE thread_id = $1 ORDER BY created_at, id
`

type ListThreadQueriesRow struct {
	ID        int64
	Question  string
	Lang      string
	Status    string
	Answer    []byte
	Model     *string
	CreatedAt time.Time
}

func (q *Queries) ListThreadQueries(ctx context.Context, threadID *int64) ([]ListThreadQueriesRow, error) {
	rows, err := q.db.Query(ctx, listThreadQueries, threadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListThreadQueriesRow
	for rows.Next() {
		var i ListThreadQueriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Question,
			&i.Lang,
			&i.Status,
			&i.Answer,
			&i.Model,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listThreads = `-- name: ListThreads :many
SELECT id, user_id, title, created_at, hidden_at FROM ask_threads WHERE user_id = $1 AND hidden_at IS NULL ORDER BY created_at DESC, id DESC LIMIT 100
`

func (q *Queries) ListThreads(ctx context.Context, userID int64) ([]AskThread, error) {
	rows, err := q.db.Query(ctx, listThreads, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AskThread
	for rows.Next() {
		var i AskThread
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
			&i.HiddenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
