// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ask_retrieve.sql

package db

import (
	"context"
	"time"

	pgvector "github.com/pgvector/pgvector-go"
)

const countScopeNotes = `-- name: CountScopeNotes :one
SELECT count(*)
FROM (
  SELECT n.id
  FROM decision_notes n
  WHERE n.archived_at IS NULL
    AND EXISTS (
    SELECT 1 FROM chunks ch
    WHERE ch.note_id = n.id
      AND ($1::boolean OR EXISTS (
            SELECT 1 FROM memberships m
            WHERE m.user_id = $2::bigint AND m.project_id = ch.project_id
              AND (m.all_clients OR ch.client_id IS NULL OR EXISTS (
                    SELECT 1 FROM membership_clients mc
                    WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = ch.client_id))))
      AND (cardinality($3::bigint[]) = 0 OR ch.project_id = ANY ($3::bigint[]))
      AND (cardinality($4::bigint[]) = 0 OR ch.node_ids && $4::bigint[])
      AND (cardinality($5::bigint[]) = 0 OR ch.client_id IS NULL OR ch.client_id = ANY ($5::bigint[]))
      AND ((cardinality($6::bigint[]) = 0 AND cardinality($7::bigint[]) = 0)
           OR ch.user_ids && $6::bigint[] OR ch.contact_ids && $7::bigint[]))
    AND ($8::timestamptz IS NULL OR n.decided_on >= $8::timestamptz)
    AND ($9::timestamptz IS NULL OR n.decided_on < $9::timestamptz)
  LIMIT $10
) scoped
`

type CountScopeNotesParams struct {
	IsAdmin    bool
	UserID     int64
	ProjectIds []int64
	NodeIds    []int64
	ClientIds  []int64
	UserIds    []int64
	ContactIds []int64
	FromTs     *time.Time
	ToTs       *time.Time
	Cap        int32
}

// How many decision notes are in scope, counting no further than cap (§11.3).
func (q *Queries) CountScopeNotes(ctx context.Context, arg CountScopeNotesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countScopeNotes,
		arg.IsAdmin,
		arg.UserID,
		arg.ProjectIds,
		arg.NodeIds,
		arg.ClientIds,
		arg.UserIds,
		arg.ContactIds,
		arg.FromTs,
		arg.ToTs,
		arg.Cap,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countScopeTickets = `-- name: CountScopeTickets :one
SELECT count(*)
FROM (
  SELECT t.id
  FROM tickets t
  WHERE EXISTS (
    SELECT 1 FROM chunks ch
    WHERE ch.ticket_id = t.id
      AND ($1::boolean OR EXISTS (
            SELECT 1 FROM memberships m
            WHERE m.user_id = $2::bigint AND m.project_id = ch.project_id
              AND (m.all_clients OR ch.client_id IS NULL OR EXISTS (
                    SELECT 1 FROM membership_clients mc
                    WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = ch.client_id))))
      AND (cardinality($3::bigint[]) = 0 OR ch.project_id = ANY ($3::bigint[]))
      AND (cardinality($4::bigint[]) = 0 OR ch.node_ids && $4::bigint[])
      AND (cardinality($5::bigint[]) = 0 OR ch.client_id IS NULL OR ch.client_id = ANY ($5::bigint[]))
      AND ((cardinality($6::bigint[]) = 0 AND cardinality($7::bigint[]) = 0)
           OR ch.user_ids && $6::bigint[] OR ch.contact_ids && $7::bigint[]))
    AND ($8::timestamptz IS NULL OR coalesce(t.closed_at, t.created_at) >= $8::timestamptz)
    AND ($9::timestamptz IS NULL OR coalesce(t.closed_at, t.created_at) < $9::timestamptz)
  LIMIT $10
) scoped
`

type CountScopeTicketsParams struct {
	IsAdmin    bool
	UserID     int64
	ProjectIds []int64
	NodeIds    []int64
	ClientIds  []int64
	UserIds    []int64
	ContactIds []int64
	FromTs     *time.Time
	ToTs       *time.Time
	Cap        int32
}

// How many tickets are in scope, counting no further than cap: retrieval only
// asks whether the set is small (§11.3). Driven from tickets with LIMIT, it
// stops early on a broad scope instead of scanning every chunk.
func (q *Queries) CountScopeTickets(ctx context.Context, arg CountScopeTicketsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countScopeTickets,
		arg.IsAdmin,
		arg.UserID,
		arg.ProjectIds,
		arg.NodeIds,
		arg.ClientIds,
		arg.UserIds,
		arg.ContactIds,
		arg.FromTs,
		arg.ToTs,
		arg.Cap,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const expandNodes = `-- name: ExpandNodes :many

WITH RECURSIVE sub AS (
  SELECT n.id FROM nodes n WHERE n.id = ANY ($1::bigint[])
  UNION
  SELECT n.id FROM nodes n JOIN sub ON n.parent_id = sub.id
)
SELECT id FROM sub ORDER BY id
`

// The Ask engine's retrieval (FSD §11.3). Every query applies the visibility
// predicate to the chunk's project and client (§5.3, R-AC-7) and the scope in
// SQL, never after. An empty array means "no filter"; node_ids arrive already
// expanded to sub-nodes; dates filter on the item's date, the close date or,
// while open, the creation date (§10.2), with to_ts exclusive.
// The nodes and all their sub-nodes, archived ones too, so history under an
// archived menu still counts.
func (q *Queries) ExpandNodes(ctx context.Context, nodeIds []int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, expandNodes, nodeIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const keywordSearch = `-- name: KeywordSearch :many
SELECT c.id, c.ticket_id, c.note_id, c.section_id, c.rank
FROM (
SELECT ch.id, ch.ticket_id, ch.note_id, ch.section_id, ts_rank_cd(ch.tsv, query)::float8 AS rank
FROM chunks ch
LEFT JOIN tickets t ON t.id = ch.ticket_id,
     to_tsquery('simple', $1::text) AS query
WHERE ch.tsv @@ query
  AND ($2::boolean OR EXISTS (
        SELECT 1 FROM memberships m
        WHERE m.user_id = $3::bigint AND m.project_id = ch.project_id
          AND (m.all_clients OR ch.client_id IS NULL OR EXISTS (
                SELECT 1 FROM membership_clients mc
                WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = ch.client_id))))
  AND (cardinality($4::bigint[]) = 0 OR ch.project_id = ANY ($4::bigint[]))
  AND (cardinality($5::bigint[]) = 0 OR ch.node_ids && $5::bigint[])
  AND (cardinality($6::bigint[]) = 0 OR ch.client_id IS NULL OR ch.client_id = ANY ($6::bigint[]))
  AND ((cardinality($7::bigint[]) = 0 AND cardinality($8::bigint[]) = 0)
       OR ch.user_ids && $7::bigint[] OR ch.contact_ids && $8::bigint[])
  AND ($9::timestamptz IS NULL OR coalesce(t.closed_at, t.created_at, ch.occurred_at) >= $9::timestamptz)
  AND ($10::timestamptz IS NULL OR coalesce(t.closed_at, t.created_at, ch.occurred_at) < $10::timestamptz)
LIMIT $11
) c
ORDER BY c.rank DESC, c.id
LIMIT 50
`

type KeywordSearchParams struct {
	Terms      string
	IsAdmin    bool
	UserID     int64
	ProjectIds []int64
	NodeIds    []int64
	ClientIds  []int64
	UserIds    []int64
	ContactIds []int64
	FromTs     *time.Time
	ToTs       *time.Time
	Candidates int32
}

type KeywordSearchRow struct {
	ID        int64
	TicketID  *int64
	NoteID    *int64
	SectionID *int64
	Rank      float64
}

// The 50 chunks whose words best match the question. The 'simple'
// configuration skips stemming, which suits mixed Indonesian-English text,
// IDs and names (§11.3). Ranking reads every candidate row, so it ranks at
// most `candidates` of them: a word found in thousands of chunks says little
// on its own, and the caller tries all the words together first.
func (q *Queries) KeywordSearch(ctx context.Context, arg KeywordSearchParams) ([]KeywordSearchRow, error) {
	rows, err := q.db.Query(ctx, keywordSearch,
		arg.Terms,
		arg.IsAdmin,
		arg.UserID,
		arg.ProjectIds,
		arg.NodeIds,
		arg.ClientIds,
		arg.UserIds,
		arg.ContactIds,
		arg.FromTs,
		arg.ToTs,
		arg.Candidates,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []KeywordSearchRow
	for rows.Next() {
		var i KeywordSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.NoteID,
			&i.SectionID,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopeNoteIDs = `-- name: ListScopeNoteIDs :many
SELECT n.id
FROM decision_notes n
WHERE n.archived_at IS NULL
  AND EXISTS (
  SELECT 1 FROM chunks ch
  WHERE ch.note_id = n.id
    AND ($1::boolean OR EXISTS (
          SELECT 1 FROM memberships m
          WHERE m.user_id = $2::bigint AND m.project_id = ch.project_id
            AND (m.all_clients OR ch.client_id IS NULL OR EXISTS (
                  SELECT 1 FROM membership_clients mc
                  WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = ch.client_id))))
    AND (cardinality($3::bigint[]) = 0 OR ch.project_id = ANY ($3::bigint[]))
    AND (cardinality($4::bigint[]) = 0 OR ch.node_ids && $4::bigint[])
    AND (cardinality($5::bigint[]) = 0 OR ch.client_id IS NULL OR ch.client_id = ANY ($5::bigint[]))
    AND ((cardinality($6::bigint[]) = 0 AND cardinality($7::bigint[]) = 0)
         OR ch.user_ids && $6::bigint[] OR ch.contact_ids && $7::bigint[]))
  AND ($8::timestamptz IS NULL OR n.decided_on >= $8::timestamptz)
  AND ($9::timestamptz IS NULL OR n.decided_on < $9::timestamptz)
ORDER BY n.decided_on DESC, n.id DESC
LIMIT $10
`

type ListScopeNoteIDsParams struct {
	IsAdmin    bool
	UserID     int64
	ProjectIds []int64
	NodeIds    []int64
	ClientIds  []int64
	UserIds    []int64
	ContactIds []int64
	FromTs     *time.Time
	ToTs       *time.Time
	Lim        int32
}

// Every decision note in scope, newest first by decision date: the small-set path.
func (q *Queries) ListScopeNoteIDs(ctx context.Context, arg ListScopeNoteIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listScopeNoteIDs,
		arg.IsAdmin,
		arg.UserID,
		arg.ProjectIds,
		arg.NodeIds,
		arg.ClientIds,
		arg.UserIds,
		arg.ContactIds,
		arg.FromTs,
		arg.ToTs,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScopeTicketIDs = `-- name: ListScopeTicketIDs :many
SELECT t.id
FROM tickets t
WHERE EXISTS (
  SELECT 1 FROM chunks ch
  WHERE ch.ticket_id = t.id
    AND ($1::boolean OR EXISTS (
          SELECT 1 FROM memberships m
          WHERE m.user_id = $2::bigint AND m.project_id = ch.project_id
            AND (m.all_clients OR ch.client_id IS NULL OR EXISTS (
                  SELECT 1 FROM membership_clients mc
                  WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = ch.client_id))))
    AND (cardinality($3::bigint[]) = 0 OR ch.project_id = ANY ($3::bigint[]))
    AND (cardinality($4::bigint[]) = 0 OR ch.node_ids && $4::bigint[])
    AND (cardinality($5::bigint[]) = 0 OR ch.client_id IS NULL OR ch.client_id = ANY ($5::bigint[]))
    AND ((cardinality($6::bigint[]) = 0 AND cardinality($7::bigint[]) = 0)
         OR ch.user_ids && $6::bigint[] OR ch.contact_ids && $7::bigint[]))
  AND ($8::timestamptz IS NULL OR coalesce(t.closed_at, t.created_at) >= $8::timestamptz)
  AND ($9::timestamptz IS NULL OR coalesce(t.closed_at, t.created_at) < $9::timestamptz)
ORDER BY coalesce(t.closed_at, t.created_at) DESC, t.id DESC
LIMIT $10
`

type ListScopeTicketIDsParams struct {
	IsAdmin    bool
	UserID     int64
	ProjectIds []int64
	NodeIds    []int64
	ClientIds  []int64
	UserIds    []int64
	ContactIds []int64
	FromTs     *time.Time
	ToTs       *time.Time
	Lim        int32
}

// Every ticket in scope, newest first by item date: the small-set path.
func (q *Queries) ListScopeTicketIDs(ctx context.Context, arg ListScopeTicketIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, listScopeTicketIDs,
		arg.IsAdmin,
		arg.UserID,
		arg.ProjectIds,
		arg.NodeIds,
		arg.ClientIds,
		arg.UserIds,
		arg.ContactIds,
		arg.FromTs,
		arg.ToTs,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const vectorSearch = `-- name: VectorSearch :many
SELECT ch.id, ch.ticket_id, ch.note_id, ch.section_id, (1 - (ch.embedding <=> $1::halfvec))::float8 AS similarity
FROM chunks ch
LEFT JOIN tickets t ON t.id = ch.ticket_id
WHERE ch.embed_model = $2::text
  AND ($3::boolean OR EXISTS (
        SELECT 1 FROM memberships m
        WHERE m.user_id = $4::bigint AND m.project_id = ch.project_id
          AND (m.all_clients OR ch.client_id IS NULL OR EXISTS (
                SELECT 1 FROM membership_clients mc
                WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = ch.client_id))))
  AND (cardinality($5::bigint[]) = 0 OR ch.project_id = ANY ($5::bigint[]))
  AND (cardinality($6::bigint[]) = 0 OR ch.node_ids && $6::bigint[])
  AND (cardinality($7::bigint[]) = 0 OR ch.client_id IS NULL OR ch.client_id = ANY ($7::bigint[]))
  AND ((cardinality($8::bigint[]) = 0 AND cardinality($9::bigint[]) = 0)
       OR ch.user_ids && $8::bigint[] OR ch.contact_ids && $9::bigint[])
  AND ($10::timestamptz IS NULL OR coalesce(t.closed_at, t.created_at, ch.occurred_at) >= $10::timestamptz)
  AND ($11::timestamptz IS NULL OR coalesce(t.closed_at, t.created_at, ch.occurred_at) < $11::timestamptz)
ORDER BY ch.embedding <=> $1::halfvec
LIMIT 50
`

type VectorSearchParams struct {
	Vec        pgvector.HalfVector
	Model      string
	IsAdmin    bool
	UserID     int64
	ProjectIds []int64
	NodeIds    []int64
	ClientIds  []int64
	UserIds    []int64
	ContactIds []int64
	FromTs     *time.Time
	ToTs       *time.Time
}

type VectorSearchRow struct {
	ID         int64
	TicketID   *int64
	NoteID     *int64
	SectionID  *int64
	Similarity float64
}

// The 50 chunks nearest the question, among chunks embedded by the current
// model. A chunk belongs to a ticket or to a decision note (§9.4); a note's
// date is its decision date. The caller sets hnsw.iterative_scan and hnsw.ef_search for its
// transaction, so filtered searches still find enough rows (§11.3).
func (q *Queries) VectorSearch(ctx context.Context, arg VectorSearchParams) ([]VectorSearchRow, error) {
	rows, err := q.db.Query(ctx, vectorSearch,
		arg.Vec,
		arg.Model,
		arg.IsAdmin,
		arg.UserID,
		arg.ProjectIds,
		arg.NodeIds,
		arg.ClientIds,
		arg.UserIds,
		arg.ContactIds,
		arg.FromTs,
		arg.ToTs,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VectorSearchRow
	for rows.Next() {
		var i VectorSearchRow
		if err := rows.Scan(
			&i.ID,
			&i.TicketID,
			&i.NoteID,
			&i.SectionID,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const visibleNoteIDs = `-- name: VisibleNoteIDs :many
SELECT n.id
FROM decision_notes n
WHERE n.id = ANY ($1::bigint[]) AND n.archived_at IS NULL
  AND ($2::boolean OR EXISTS (
        SELECT 1 FROM memberships m
        WHERE m.user_id = $3::bigint AND m.project_id = n.project_id
          AND (m.all_clients OR n.client_id IS NULL OR EXISTS (
                SELECT 1 FROM membership_clients mc
                WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = n.client_id))))
`

type VisibleNoteIDsParams struct {
	Ids     []int64
	IsAdmin bool
	UserID  int64
}

// Of the given notes, those the asker may open now (§10.6).
func (q *Queries) VisibleNoteIDs(ctx context.Context, arg VisibleNoteIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, visibleNoteIDs, arg.Ids, arg.IsAdmin, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const visibleNoteIDsByKey = `-- name: VisibleNoteIDsByKey :many
SELECT n.id, n.key
FROM decision_notes n
WHERE n.key = ANY ($1::text[]) AND n.archived_at IS NULL
  AND ($2::boolean OR EXISTS (
        SELECT 1 FROM memberships m
        WHERE m.user_id = $3::bigint AND m.project_id = n.project_id
          AND (m.all_clients OR n.client_id IS NULL OR EXISTS (
                SELECT 1 FROM membership_clients mc
                WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = n.client_id))))
`

type VisibleNoteIDsByKeyParams struct {
	Keys    []string
	IsAdmin bool
	UserID  int64
}

type VisibleNoteIDsByKeyRow struct {
	ID  int64
	Key string
}

// Notes a question names by key that the asker may open (§11.2).
func (q *Queries) VisibleNoteIDsByKey(ctx context.Context, arg VisibleNoteIDsByKeyParams) ([]VisibleNoteIDsByKeyRow, error) {
	rows, err := q.db.Query(ctx, visibleNoteIDsByKey, arg.Keys, arg.IsAdmin, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VisibleNoteIDsByKeyRow
	for rows.Next() {
		var i VisibleNoteIDsByKeyRow
		if err := rows.Scan(&i.ID, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const visibleTicketIDs = `-- name: VisibleTicketIDs :many
SELECT t.id
FROM tickets t
WHERE t.id = ANY ($1::bigint[])
  AND ($2::boolean OR EXISTS (
        SELECT 1 FROM memberships m
        WHERE m.user_id = $3::bigint AND m.project_id = t.project_id
          AND (m.all_clients OR t.client_id IS NULL OR EXISTS (
                SELECT 1 FROM membership_clients mc
                WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = t.client_id))))
`

type VisibleTicketIDsParams struct {
	Ids     []int64
	IsAdmin bool
	UserID  int64
}

// Of the given tickets, those the asker may open now, for re-showing a
// thread's evidence (§10.6).
func (q *Queries) VisibleTicketIDs(ctx context.Context, arg VisibleTicketIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, visibleTicketIDs, arg.Ids, arg.IsAdmin, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const visibleTicketIDsByKey = `-- name: VisibleTicketIDsByKey :many
SELECT t.id, t.key
FROM tickets t
WHERE t.key = ANY ($1::text[])
  AND ($2::boolean OR EXISTS (
        SELECT 1 FROM memberships m
        WHERE m.user_id = $3::bigint AND m.project_id = t.project_id
          AND (m.all_clients OR t.client_id IS NULL OR EXISTS (
                SELECT 1 FROM membership_clients mc
                WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = t.client_id))))
`

type VisibleTicketIDsByKeyParams struct {
	Keys    []string
	IsAdmin bool
	UserID  int64
}

type VisibleTicketIDsByKeyRow struct {
	ID  int64
	Key string
}

// Tickets a question names by key that the asker may open (§11.2).
func (q *Queries) VisibleTicketIDsByKey(ctx context.Context, arg VisibleTicketIDsByKeyParams) ([]VisibleTicketIDsByKeyRow, error) {
	rows, err := q.db.Query(ctx, visibleTicketIDsByKey, arg.Keys, arg.IsAdmin, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []VisibleTicketIDsByKeyRow
	for rows.Next() {
		var i VisibleTicketIDsByKeyRow
		if err := rows.Scan(&i.ID, &i.Key); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
