// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ask_log.sql

package db

import (
	"context"
	"time"
)

const getAskLogEntry = `-- name: GetAskLogEntry :one
SELECT q.id, q.thread_id, q.user_id, q.question, q.lang, q.scope, q.evidence, q.llm_called, q.status, q.answer, q.dropped, q.model, q.latency_ms, q.first_claim_ms, q.created_at, u.name AS user_name,
       jsonb_array_length(q.evidence)::int AS evidence_count,
       (SELECT count(DISTINCT c.key)
        FROM jsonb_array_elements(coalesce(q.answer, '[]'::jsonb)) a, jsonb_array_elements_text(a -> 'cites') AS c(key))::int AS citations
FROM ask_queries q
JOIN users u ON u.id = q.user_id
WHERE q.id = $1
`

type GetAskLogEntryRow struct {
	ID            int64
	ThreadID      *int64
	UserID        int64
	Question      string
	Lang          string
	Scope         []byte
	Evidence      []byte
	LlmCalled     bool
	Status        string
	Answer        []byte
	Dropped       []byte
	Model         *string
	LatencyMs     *int32
	FirstClaimMs  *int32
	CreatedAt     time.Time
	UserName      string
	EvidenceCount int32
	Citations     int32
}

func (q *Queries) GetAskLogEntry(ctx context.Context, id int64) (GetAskLogEntryRow, error) {
	row := q.db.QueryRow(ctx, getAskLogEntry, id)
	var i GetAskLogEntryRow
	err := row.Scan(
		&i.ID,
		&i.ThreadID,
		&i.UserID,
		&i.Question,
		&i.Lang,
		&i.Scope,
		&i.Evidence,
		&i.LlmCalled,
		&i.Status,
		&i.Answer,
		&i.Dropped,
		&i.Model,
		&i.LatencyMs,
		&i.FirstClaimMs,
		&i.CreatedAt,
		&i.UserName,
		&i.EvidenceCount,
		&i.Citations,
	)
	return i, err
}

const listAskLog = `-- name: ListAskLog :many
SELECT q.id, q.created_at, q.user_id, u.name AS user_name, q.question, q.status, q.llm_called, q.latency_ms, q.model,
       jsonb_array_length(q.evidence)::int AS evidence_count,
       (SELECT count(DISTINCT c.key)
        FROM jsonb_array_elements(coalesce(q.answer, '[]'::jsonb)) a, jsonb_array_elements_text(a -> 'cites') AS c(key))::int AS citations
FROM ask_queries q
JOIN users u ON u.id = q.user_id
WHERE ($1::text IS NULL OR q.status = $1::text)
  AND (NOT $2::boolean OR q.latency_ms > 30000)
  AND ($3::bigint IS NULL OR q.user_id = $3::bigint)
  AND ($4::bigint IS NULL OR q.id < $4::bigint)
ORDER BY q.id DESC
LIMIT $5
`

type ListAskLogParams struct {
	Status *string
	Slow   bool
	UserID *int64
	Before *int64
	Lim    int32
}

type ListAskLogRow struct {
	ID            int64
	CreatedAt     time.Time
	UserID        int64
	UserName      string
	Question      string
	Status        string
	LlmCalled     bool
	LatencyMs     *int32
	Model         *string
	EvidenceCount int32
	Citations     int32
}

// The Ask log for system admins, newest first (FSD §15.4).
func (q *Queries) ListAskLog(ctx context.Context, arg ListAskLogParams) ([]ListAskLogRow, error) {
	rows, err := q.db.Query(ctx, listAskLog,
		arg.Status,
		arg.Slow,
		arg.UserID,
		arg.Before,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAskLogRow
	for rows.Next() {
		var i ListAskLogRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UserID,
			&i.UserName,
			&i.Question,
			&i.Status,
			&i.LlmCalled,
			&i.LatencyMs,
			&i.Model,
			&i.EvidenceCount,
			&i.Citations,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeAskQueries = `-- name: PurgeAskQueries :execrows
DELETE FROM ask_queries WHERE created_at < $1
`

// Retention: questions older than the cutoff go (FSD §15.4, 365 days by default).
func (q *Queries) PurgeAskQueries(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeAskQueries, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeEmptyThreads = `-- name: PurgeEmptyThreads :execrows
DELETE FROM ask_threads t
WHERE t.created_at < $1
  AND NOT EXISTS (SELECT 1 FROM ask_queries q WHERE q.thread_id = t.id)
`

// Then the threads that retention left empty.
func (q *Queries) PurgeEmptyThreads(ctx context.Context, cutoff time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, purgeEmptyThreads, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
