// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: attachments.sql

package db

import (
	"context"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO attachments (ticket_id, uploader_id, filename, content_type, size_bytes, sha256)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, ticket_id, uploader_id, filename, content_type, size_bytes, sha256, created_at, deleted_at
`

type CreateAttachmentParams struct {
	TicketID    int64
	UploaderID  int64
	Filename    string
	ContentType string
	SizeBytes   int64
	Sha256      []byte
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.TicketID,
		arg.UploaderID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.Sha256,
	)
	var i Attachment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.UploaderID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteAttachment = `-- name: DeleteAttachment :exec
UPDATE attachments SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteAttachment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAttachment, id)
	return err
}

const getAttachment = `-- name: GetAttachment :one
SELECT a.id, a.ticket_id, a.uploader_id, a.filename, a.content_type, a.size_bytes, a.sha256, a.created_at, a.deleted_at, t.key AS ticket_key
FROM attachments a JOIN tickets t ON t.id = a.ticket_id
WHERE a.id = $1 AND a.deleted_at IS NULL
`

type GetAttachmentRow struct {
	Attachment Attachment
	TicketKey  string
}

func (q *Queries) GetAttachment(ctx context.Context, id int64) (GetAttachmentRow, error) {
	row := q.db.QueryRow(ctx, getAttachment, id)
	var i GetAttachmentRow
	err := row.Scan(
		&i.Attachment.ID,
		&i.Attachment.TicketID,
		&i.Attachment.UploaderID,
		&i.Attachment.Filename,
		&i.Attachment.ContentType,
		&i.Attachment.SizeBytes,
		&i.Attachment.Sha256,
		&i.Attachment.CreatedAt,
		&i.Attachment.DeletedAt,
		&i.TicketKey,
	)
	return i, err
}

const listAttachments = `-- name: ListAttachments :many
SELECT a.id, a.ticket_id, a.uploader_id, a.filename, a.content_type, a.size_bytes, a.sha256, a.created_at, a.deleted_at, u.name AS uploader_name
FROM attachments a JOIN users u ON u.id = a.uploader_id
WHERE a.ticket_id = $1 AND a.deleted_at IS NULL
ORDER BY a.created_at, a.id
`

type ListAttachmentsRow struct {
	Attachment   Attachment
	UploaderName string
}

func (q *Queries) ListAttachments(ctx context.Context, ticketID int64) ([]ListAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listAttachments, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttachmentsRow
	for rows.Next() {
		var i ListAttachmentsRow
		if err := rows.Scan(
			&i.Attachment.ID,
			&i.Attachment.TicketID,
			&i.Attachment.UploaderID,
			&i.Attachment.Filename,
			&i.Attachment.ContentType,
			&i.Attachment.SizeBytes,
			&i.Attachment.Sha256,
			&i.Attachment.CreatedAt,
			&i.Attachment.DeletedAt,
			&i.UploaderName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
