// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"net/netip"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (actor_id, via, entity, entity_id, project_id, action, changes, request_id, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAuditEventParams struct {
	ActorID   *int64
	Via       string
	Entity    string
	EntityID  int64
	ProjectID *int64
	Action    string
	Changes   []byte
	RequestID *string
	Ip        *netip.Addr
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ActorID,
		arg.Via,
		arg.Entity,
		arg.EntityID,
		arg.ProjectID,
		arg.Action,
		arg.Changes,
		arg.RequestID,
		arg.Ip,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, occurred_at, actor_id, via, entity, entity_id, project_id, action, changes, request_id, ip FROM audit_events WHERE entity = $1 AND entity_id = $2 ORDER BY id
`

type ListAuditEventsParams struct {
	Entity   string
	EntityID int64
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, arg.Entity, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorID,
			&i.Via,
			&i.Entity,
			&i.EntityID,
			&i.ProjectID,
			&i.Action,
			&i.Changes,
			&i.RequestID,
			&i.Ip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
