// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package db

import (
	"context"
	"net/netip"
	"time"
)

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit_events (actor_id, via, entity, entity_id, project_id, action, changes, request_id, ip)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAuditEventParams struct {
	ActorID   *int64
	Via       string
	Entity    string
	EntityID  int64
	ProjectID *int64
	Action    string
	Changes   []byte
	RequestID *string
	Ip        *netip.Addr
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.ActorID,
		arg.Via,
		arg.Entity,
		arg.EntityID,
		arg.ProjectID,
		arg.Action,
		arg.Changes,
		arg.RequestID,
		arg.Ip,
	)
	return err
}

const listAudit = `-- name: ListAudit :many
SELECT e.id, e.occurred_at, e.actor_id, u.name AS actor_name, e.via, e.entity, e.entity_id, p.key AS project_key, e.action, e.changes
FROM audit_events e
LEFT JOIN users u ON u.id = e.actor_id
LEFT JOIN projects p ON p.id = e.project_id
WHERE ($1::bigint IS NULL OR e.actor_id = $1::bigint)
  AND ($2::text IS NULL OR e.entity = $2::text)
  AND ($3::text IS NULL OR e.action = $3::text)
  AND ($4::timestamptz IS NULL OR e.occurred_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR e.occurred_at < $5::timestamptz)
  AND ($6::bigint IS NULL OR e.id < $6::bigint)
ORDER BY e.id DESC
LIMIT $7
`

type ListAuditParams struct {
	ActorID *int64
	Entity  *string
	Action  *string
	Since   *time.Time
	Until   *time.Time
	Before  *int64
	Lim     int32
}

type ListAuditRow struct {
	ID         int64
	OccurredAt time.Time
	ActorID    *int64
	ActorName  *string
	Via        string
	Entity     string
	EntityID   int64
	ProjectKey *string
	Action     string
	Changes    []byte
}

// The audit log for system admins, newest first, filtered (FSD §15.4). Dates
// are whole days in the admin's timezone, passed as bounds.
func (q *Queries) ListAudit(ctx context.Context, arg ListAuditParams) ([]ListAuditRow, error) {
	rows, err := q.db.Query(ctx, listAudit,
		arg.ActorID,
		arg.Entity,
		arg.Action,
		arg.Since,
		arg.Until,
		arg.Before,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuditRow
	for rows.Next() {
		var i ListAuditRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorID,
			&i.ActorName,
			&i.Via,
			&i.Entity,
			&i.EntityID,
			&i.ProjectKey,
			&i.Action,
			&i.Changes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, occurred_at, actor_id, via, entity, entity_id, project_id, action, changes, request_id, ip FROM audit_events WHERE entity = $1 AND entity_id = $2 ORDER BY id
`

type ListAuditEventsParams struct {
	Entity   string
	EntityID int64
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]AuditEvent, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, arg.Entity, arg.EntityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditEvent
	for rows.Next() {
		var i AuditEvent
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorID,
			&i.Via,
			&i.Entity,
			&i.EntityID,
			&i.ProjectID,
			&i.Action,
			&i.Changes,
			&i.RequestID,
			&i.Ip,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketEvents = `-- name: ListTicketEvents :many
SELECT e.id, e.occurred_at, e.actor_id, u.name AS actor_name, e.action, e.changes
FROM audit_events e
LEFT JOIN users u ON u.id = e.actor_id
WHERE e.entity = 'ticket' AND e.entity_id = $1
ORDER BY e.id
`

type ListTicketEventsRow struct {
	ID         int64
	OccurredAt time.Time
	ActorID    *int64
	ActorName  *string
	Action     string
	Changes    []byte
}

// A ticket's history: every event recorded against it, oldest first (FSD §8.7).
func (q *Queries) ListTicketEvents(ctx context.Context, entityID int64) ([]ListTicketEventsRow, error) {
	rows, err := q.db.Query(ctx, listTicketEvents, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketEventsRow
	for rows.Next() {
		var i ListTicketEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.OccurredAt,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.Changes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
