// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chunks.sql

package db

import (
	"context"
	"time"

	pgvector "github.com/pgvector/pgvector-go"
)

const countChunksByModel = `-- name: CountChunksByModel :many
SELECT coalesce(embed_model, '') AS model, count(*) AS chunks, max(indexed_at)::timestamptz AS latest
FROM chunks GROUP BY 1 ORDER BY 1
`

type CountChunksByModelRow struct {
	Model  string
	Chunks int64
	Latest time.Time
}

func (q *Queries) CountChunksByModel(ctx context.Context) ([]CountChunksByModelRow, error) {
	rows, err := q.db.Query(ctx, countChunksByModel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountChunksByModelRow
	for rows.Next() {
		var i CountChunksByModelRow
		if err := rows.Scan(&i.Model, &i.Chunks, &i.Latest); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countEmbeddedChunks = `-- name: CountEmbeddedChunks :one
SELECT count(*) FROM chunks WHERE embedding IS NOT NULL
`

func (q *Queries) CountEmbeddedChunks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEmbeddedChunks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPendingChunks = `-- name: CountPendingChunks :one
SELECT count(*) FROM chunks WHERE embedding IS NULL OR embed_model IS DISTINCT FROM $1::text
`

func (q *Queries) CountPendingChunks(ctx context.Context, model string) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingChunks, model)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteChunksFrom = `-- name: DeleteChunksFrom :exec
DELETE FROM chunks WHERE source_type = $1 AND source_id = $2 AND seq >= $3
`

type DeleteChunksFromParams struct {
	SourceType string
	SourceID   int64
	Seq        int32
}

// Removes a source's parts from seq on: all of them with 0, or the tail that
// a shorter text no longer has.
func (q *Queries) DeleteChunksFrom(ctx context.Context, arg DeleteChunksFromParams) error {
	_, err := q.db.Exec(ctx, deleteChunksFrom, arg.SourceType, arg.SourceID, arg.Seq)
	return err
}

const deleteNoteChunks = `-- name: DeleteNoteChunks :exec
DELETE FROM chunks WHERE note_id = $1::bigint
`

func (q *Queries) DeleteNoteChunks(ctx context.Context, noteID int64) error {
	_, err := q.db.Exec(ctx, deleteNoteChunks, noteID)
	return err
}

const deleteTicketChunks = `-- name: DeleteTicketChunks :exec
DELETE FROM chunks WHERE ticket_id = $1::bigint
`

func (q *Queries) DeleteTicketChunks(ctx context.Context, ticketID int64) error {
	_, err := q.db.Exec(ctx, deleteTicketChunks, ticketID)
	return err
}

const listPendingChunks = `-- name: ListPendingChunks :many
SELECT id, content, content_hash FROM chunks
WHERE embedding IS NULL OR embed_model IS DISTINCT FROM $1::text
ORDER BY occurred_at DESC, id DESC
LIMIT $2
`

type ListPendingChunksParams struct {
	Model string
	Lim   int32
}

type ListPendingChunksRow struct {
	ID          int64
	Content     string
	ContentHash []byte
}

// Chunks without a vector from the current embedding model, newest first (§13.4).
func (q *Queries) ListPendingChunks(ctx context.Context, arg ListPendingChunksParams) ([]ListPendingChunksRow, error) {
	rows, err := q.db.Query(ctx, listPendingChunks, arg.Model, arg.Lim)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingChunksRow
	for rows.Next() {
		var i ListPendingChunksRow
		if err := rows.Scan(&i.ID, &i.Content, &i.ContentHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketChunks = `-- name: ListTicketChunks :many
SELECT id, source_type, source_id, seq, content, content_hash, embed_model, (embedding IS NOT NULL)::boolean AS embedded
FROM chunks WHERE ticket_id = $1::bigint ORDER BY source_type, source_id, seq
`

type ListTicketChunksRow struct {
	ID          int64
	SourceType  string
	SourceID    int64
	Seq         int32
	Content     string
	ContentHash []byte
	EmbedModel  *string
	Embedded    bool
}

func (q *Queries) ListTicketChunks(ctx context.Context, ticketID int64) ([]ListTicketChunksRow, error) {
	rows, err := q.db.Query(ctx, listTicketChunks, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketChunksRow
	for rows.Next() {
		var i ListTicketChunksRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceType,
			&i.SourceID,
			&i.Seq,
			&i.Content,
			&i.ContentHash,
			&i.EmbedModel,
			&i.Embedded,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setChunkEmbedding = `-- name: SetChunkEmbedding :exec
UPDATE chunks SET embedding = $1::halfvec, embed_model = $2::text, indexed_at = now()
WHERE id = $3 AND content_hash = $4
`

type SetChunkEmbeddingParams struct {
	Embedding   pgvector.HalfVector
	Model       string
	ID          int64
	ContentHash []byte
}

// The hash guard skips a vector whose text changed while it was embedded.
func (q *Queries) SetChunkEmbedding(ctx context.Context, arg SetChunkEmbeddingParams) error {
	_, err := q.db.Exec(ctx, setChunkEmbedding,
		arg.Embedding,
		arg.Model,
		arg.ID,
		arg.ContentHash,
	)
	return err
}

const upsertChunk = `-- name: UpsertChunk :exec
INSERT INTO chunks (source_type, source_id, seq, ticket_id, note_id, project_id, client_id, node_ids, user_ids, contact_ids,
                    internal, occurred_at, content, content_hash)
VALUES ($1, $2, $3, $4::bigint, $5::bigint, $6,
        $7, $8::bigint[], $9::bigint[], $10::bigint[],
        $11, $12, $13, $14)
ON CONFLICT (source_type, source_id, seq) DO UPDATE SET
  ticket_id = excluded.ticket_id, note_id = excluded.note_id, project_id = excluded.project_id, client_id = excluded.client_id,
  node_ids = excluded.node_ids, user_ids = excluded.user_ids, contact_ids = excluded.contact_ids,
  internal = excluded.internal, occurred_at = excluded.occurred_at,
  embedding   = CASE WHEN chunks.content_hash = excluded.content_hash THEN chunks.embedding END,
  embed_model = CASE WHEN chunks.content_hash = excluded.content_hash THEN chunks.embed_model END,
  content = excluded.content, content_hash = excluded.content_hash, indexed_at = now()
`

type UpsertChunkParams struct {
	SourceType  string
	SourceID    int64
	Seq         int32
	TicketID    *int64
	NoteID      *int64
	ProjectID   int64
	ClientID    *int64
	NodeIds     []int64
	UserIds     []int64
	ContactIds  []int64
	Internal    bool
	OccurredAt  time.Time
	Content     string
	ContentHash []byte
}

// A chunk whose text is unchanged keeps its vector and only takes the new
// filter columns; changed text clears the vector for the embedder (§13.2).
func (q *Queries) UpsertChunk(ctx context.Context, arg UpsertChunkParams) error {
	_, err := q.db.Exec(ctx, upsertChunk,
		arg.SourceType,
		arg.SourceID,
		arg.Seq,
		arg.TicketID,
		arg.NoteID,
		arg.ProjectID,
		arg.ClientID,
		arg.NodeIds,
		arg.UserIds,
		arg.ContactIds,
		arg.Internal,
		arg.OccurredAt,
		arg.Content,
		arg.ContentHash,
	)
	return err
}
