// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package db

import (
	"context"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (ticket_id, author_id, internal, body) VALUES ($1, $2, $3, $4) RETURNING id, ticket_id, author_id, internal, body, created_at, edited_at, deleted_at
`

type CreateCommentParams struct {
	TicketID int64
	AuthorID int64
	Internal bool
	Body     string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.TicketID,
		arg.AuthorID,
		arg.Internal,
		arg.Body,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.AuthorID,
		&i.Internal,
		&i.Body,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :exec
UPDATE comments SET deleted_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteComment, id)
	return err
}

const getComment = `-- name: GetComment :one
SELECT c.id, c.ticket_id, c.author_id, c.internal, c.body, c.created_at, c.edited_at, c.deleted_at, t.key AS ticket_key
FROM comments c JOIN tickets t ON t.id = c.ticket_id
WHERE c.id = $1
`

type GetCommentRow struct {
	Comment   Comment
	TicketKey string
}

func (q *Queries) GetComment(ctx context.Context, id int64) (GetCommentRow, error) {
	row := q.db.QueryRow(ctx, getComment, id)
	var i GetCommentRow
	err := row.Scan(
		&i.Comment.ID,
		&i.Comment.TicketID,
		&i.Comment.AuthorID,
		&i.Comment.Internal,
		&i.Comment.Body,
		&i.Comment.CreatedAt,
		&i.Comment.EditedAt,
		&i.Comment.DeletedAt,
		&i.TicketKey,
	)
	return i, err
}

const listComments = `-- name: ListComments :many
SELECT c.id, c.ticket_id, c.author_id, c.internal, c.body, c.created_at, c.edited_at, c.deleted_at, u.name AS author_name
FROM comments c JOIN users u ON u.id = c.author_id
WHERE c.ticket_id = $1
ORDER BY c.created_at, c.id
`

type ListCommentsRow struct {
	Comment    Comment
	AuthorName string
}

func (q *Queries) ListComments(ctx context.Context, ticketID int64) ([]ListCommentsRow, error) {
	rows, err := q.db.Query(ctx, listComments, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsRow
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.Comment.ID,
			&i.Comment.TicketID,
			&i.Comment.AuthorID,
			&i.Comment.Internal,
			&i.Comment.Body,
			&i.Comment.CreatedAt,
			&i.Comment.EditedAt,
			&i.Comment.DeletedAt,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCommentBody = `-- name: UpdateCommentBody :one
UPDATE comments SET body = $2, edited_at = now() WHERE id = $1 AND deleted_at IS NULL RETURNING id, ticket_id, author_id, internal, body, created_at, edited_at, deleted_at
`

type UpdateCommentBodyParams struct {
	ID   int64
	Body string
}

func (q *Queries) UpdateCommentBody(ctx context.Context, arg UpdateCommentBodyParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateCommentBody, arg.ID, arg.Body)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.TicketID,
		&i.AuthorID,
		&i.Internal,
		&i.Body,
		&i.CreatedAt,
		&i.EditedAt,
		&i.DeletedAt,
	)
	return i, err
}
