// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package db

import (
	"context"
)

const canEditContactsOf = `-- name: CanEditContactsOf :one
SELECT EXISTS (
  SELECT 1 FROM memberships m
  WHERE m.user_id = $1 AND m.role IN ('admin', 'member')
    AND ($2::bigint IS NULL
         OR (m.all_clients AND EXISTS (SELECT 1 FROM project_clients pc
                                       WHERE pc.project_id = m.project_id
                                         AND pc.client_id = $2::bigint))
         OR EXISTS (SELECT 1 FROM membership_clients mc
                    WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id
                      AND mc.client_id = $2::bigint))
)
`

type CanEditContactsOfParams struct {
	UserID   int64
	ClientID *int64
}

// Members and project admins keep the contacts of clients in their scope, and
// internal contacts (client NULL) in any project they belong to.
func (q *Queries) CanEditContactsOf(ctx context.Context, arg CanEditContactsOfParams) (bool, error) {
	row := q.db.QueryRow(ctx, canEditContactsOf, arg.UserID, arg.ClientID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createContact = `-- name: CreateContact :one
INSERT INTO contacts (client_id, name, title, email, phone)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateContactParams struct {
	ClientID *int64
	Name     string
	Title    *string
	Email    *string
	Phone    *string
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (int64, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.ClientID,
		arg.Name,
		arg.Title,
		arg.Email,
		arg.Phone,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listContacts = `-- name: ListContacts :many
SELECT c.id, c.client_id, cl.name AS client_name, c.name, c.title, c.email, c.phone
FROM contacts c
LEFT JOIN clients cl ON cl.id = c.client_id
WHERE ($1::boolean
       OR (c.client_id IS NULL AND EXISTS (SELECT 1 FROM memberships m WHERE m.user_id = $2))
       OR c.client_id IN (SELECT pc.client_id
                          FROM memberships m
                          JOIN project_clients pc ON pc.project_id = m.project_id
                          WHERE m.user_id = $2 AND m.all_clients
                          UNION ALL
                          SELECT mc.client_id FROM membership_clients mc WHERE mc.user_id = $2))
  AND ($3::bigint IS NULL OR c.id = $3::bigint)
  AND ($4::bigint IS NULL OR c.client_id = $4::bigint)
  AND (NOT $5::boolean OR c.client_id IS NULL)
  AND c.name ILIKE '%' || $6::text || '%'
ORDER BY lower(c.name), c.id
LIMIT 50
`

type ListContactsParams struct {
	IsAdmin  bool
	UserID   int64
	ID       *int64
	ClientID *int64
	Internal bool
	Q        string
}

type ListContactsRow struct {
	ID         int64
	ClientID   *int64
	ClientName *string
	Name       string
	Title      *string
	Email      *string
	Phone      *string
}

// R-AC-6: a contact is visible when its client is in the user's scope in some
// project; internal contacts (no client) are visible to every project member.
func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]ListContactsRow, error) {
	rows, err := q.db.Query(ctx, listContacts,
		arg.IsAdmin,
		arg.UserID,
		arg.ID,
		arg.ClientID,
		arg.Internal,
		arg.Q,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContactsRow
	for rows.Next() {
		var i ListContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.ClientID,
			&i.ClientName,
			&i.Name,
			&i.Title,
			&i.Email,
			&i.Phone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContact = `-- name: UpdateContact :exec
UPDATE contacts SET client_id = $2, name = $3, title = $4, email = $5, phone = $6
WHERE id = $1
`

type UpdateContactParams struct {
	ID       int64
	ClientID *int64
	Name     string
	Title    *string
	Email    *string
	Phone    *string
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) error {
	_, err := q.db.Exec(ctx, updateContact,
		arg.ID,
		arg.ClientID,
		arg.Name,
		arg.Title,
		arg.Email,
		arg.Phone,
	)
	return err
}
