// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decisions.sql

package db

import (
	"context"
)

const confirmDecision = `-- name: ConfirmDecision :one
INSERT INTO decision_records (ticket_id, what_changed, why, alternatives, outcome, state, confirmed_by, confirmed_at)
VALUES ($1::bigint, $2::text, $3::text, $4::text,
        $5::text, 'confirmed', $6::bigint, now())
ON CONFLICT (ticket_id) DO UPDATE SET
  what_changed = excluded.what_changed, why = excluded.why, alternatives = excluded.alternatives,
  outcome = excluded.outcome, state = 'confirmed', confirmed_by = excluded.confirmed_by, confirmed_at = excluded.confirmed_at
RETURNING ticket_id, what_changed, why, alternatives, outcome, state, confirmed_by, confirmed_at, superseded_by
`

type ConfirmDecisionParams struct {
	TicketID     int64
	WhatChanged  string
	Why          string
	Alternatives string
	Outcome      string
	ConfirmedBy  int64
}

// A close writes the record, or confirms a reopened ticket's draft again, with
// the closing user as confirmer (R-DC-4, R-DC-6).
func (q *Queries) ConfirmDecision(ctx context.Context, arg ConfirmDecisionParams) (DecisionRecord, error) {
	row := q.db.QueryRow(ctx, confirmDecision,
		arg.TicketID,
		arg.WhatChanged,
		arg.Why,
		arg.Alternatives,
		arg.Outcome,
		arg.ConfirmedBy,
	)
	var i DecisionRecord
	err := row.Scan(
		&i.TicketID,
		&i.WhatChanged,
		&i.Why,
		&i.Alternatives,
		&i.Outcome,
		&i.State,
		&i.ConfirmedBy,
		&i.ConfirmedAt,
		&i.SupersededBy,
	)
	return i, err
}

const draftDecision = `-- name: DraftDecision :exec
UPDATE decision_records SET state = 'draft', confirmed_by = NULL, confirmed_at = NULL WHERE ticket_id = $1
`

// A reopen turns the record back into a draft; the history keeps who confirmed it (R-DC-6).
func (q *Queries) DraftDecision(ctx context.Context, ticketID int64) error {
	_, err := q.db.Exec(ctx, draftDecision, ticketID)
	return err
}

const getDecision = `-- name: GetDecision :one
SELECT d.ticket_id, d.what_changed, d.why, d.alternatives, d.outcome, d.state, d.confirmed_by, d.confirmed_at, d.superseded_by, u.name AS confirmer_name, sk.key AS superseded_by_key
FROM decision_records d
LEFT JOIN users u ON u.id = d.confirmed_by
LEFT JOIN tickets sk ON sk.id = d.superseded_by
WHERE d.ticket_id = $1
`

type GetDecisionRow struct {
	DecisionRecord  DecisionRecord
	ConfirmerName   *string
	SupersededByKey *string
}

func (q *Queries) GetDecision(ctx context.Context, ticketID int64) (GetDecisionRow, error) {
	row := q.db.QueryRow(ctx, getDecision, ticketID)
	var i GetDecisionRow
	err := row.Scan(
		&i.DecisionRecord.TicketID,
		&i.DecisionRecord.WhatChanged,
		&i.DecisionRecord.Why,
		&i.DecisionRecord.Alternatives,
		&i.DecisionRecord.Outcome,
		&i.DecisionRecord.State,
		&i.DecisionRecord.ConfirmedBy,
		&i.DecisionRecord.ConfirmedAt,
		&i.DecisionRecord.SupersededBy,
		&i.ConfirmerName,
		&i.SupersededByKey,
	)
	return i, err
}

const refreshSuperseded = `-- name: RefreshSuperseded :exec
UPDATE decision_records d SET superseded_by = (
  SELECT l.from_id FROM ticket_links l WHERE l.to_id = d.ticket_id AND l.type = 'reverses'
  ORDER BY l.created_at DESC, l.id DESC LIMIT 1)
WHERE d.ticket_id = $1
`

// A ticket's decision is superseded by the newest ticket that reverses it, and
// current again when no reverses link is left (R-TK-5, R-TK-7).
func (q *Queries) RefreshSuperseded(ctx context.Context, ticketID int64) error {
	_, err := q.db.Exec(ctx, refreshSuperseded, ticketID)
	return err
}

const updateDecision = `-- name: UpdateDecision :exec
UPDATE decision_records SET what_changed = $1, why = $2, alternatives = $3
WHERE ticket_id = $4
`

type UpdateDecisionParams struct {
	WhatChanged  string
	Why          string
	Alternatives string
	TicketID     int64
}

func (q *Queries) UpdateDecision(ctx context.Context, arg UpdateDecisionParams) error {
	_, err := q.db.Exec(ctx, updateDecision,
		arg.WhatChanged,
		arg.Why,
		arg.Alternatives,
		arg.TicketID,
	)
	return err
}
