// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package db

import (
	"context"
	"time"
)

const createDocument = `-- name: CreateDocument :one
INSERT INTO documents (project_id, number, key, title, client_id, filename, content_type, size_bytes, sha256, markdown, uploaded_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, project_id, number, key, title, client_id, filename, content_type, size_bytes, sha256, markdown, superseded_by, uploaded_by, created_at, archived_at
`

type CreateDocumentParams struct {
	ProjectID   int64
	Number      int64
	Key         string
	Title       string
	ClientID    *int64
	Filename    string
	ContentType string
	SizeBytes   int64
	Sha256      []byte
	Markdown    string
	UploadedBy  int64
}

func (q *Queries) CreateDocument(ctx context.Context, arg CreateDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, createDocument,
		arg.ProjectID,
		arg.Number,
		arg.Key,
		arg.Title,
		arg.ClientID,
		arg.Filename,
		arg.ContentType,
		arg.SizeBytes,
		arg.Sha256,
		arg.Markdown,
		arg.UploadedBy,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Key,
		&i.Title,
		&i.ClientID,
		&i.Filename,
		&i.ContentType,
		&i.SizeBytes,
		&i.Sha256,
		&i.Markdown,
		&i.SupersededBy,
		&i.UploadedBy,
		&i.CreatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const createSection = `-- name: CreateSection :one
INSERT INTO document_sections (document_id, number, title, level, position, body)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type CreateSectionParams struct {
	DocumentID int64
	Number     string
	Title      string
	Level      int32
	Position   int32
	Body       string
}

func (q *Queries) CreateSection(ctx context.Context, arg CreateSectionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createSection,
		arg.DocumentID,
		arg.Number,
		arg.Title,
		arg.Level,
		arg.Position,
		arg.Body,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createTreeDraft = `-- name: CreateTreeDraft :one
INSERT INTO tree_drafts (project_id, document_id, status, proposal, used_ai, total_parts, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, document_id, status, proposal, used_ai, done_parts, total_parts, error, created_by, created_at, applied_at
`

type CreateTreeDraftParams struct {
	ProjectID  int64
	DocumentID int64
	Status     string
	Proposal   []byte
	UsedAi     bool
	TotalParts int32
	CreatedBy  int64
}

func (q *Queries) CreateTreeDraft(ctx context.Context, arg CreateTreeDraftParams) (TreeDraft, error) {
	row := q.db.QueryRow(ctx, createTreeDraft,
		arg.ProjectID,
		arg.DocumentID,
		arg.Status,
		arg.Proposal,
		arg.UsedAi,
		arg.TotalParts,
		arg.CreatedBy,
	)
	var i TreeDraft
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.DocumentID,
		&i.Status,
		&i.Proposal,
		&i.UsedAi,
		&i.DoneParts,
		&i.TotalParts,
		&i.Error,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.AppliedAt,
	)
	return i, err
}

const deleteSectionChunks = `-- name: DeleteSectionChunks :exec
DELETE FROM chunks WHERE section_id = $1
`

func (q *Queries) DeleteSectionChunks(ctx context.Context, sectionID *int64) error {
	_, err := q.db.Exec(ctx, deleteSectionChunks, sectionID)
	return err
}

const deleteStaleSectionChunks = `-- name: DeleteStaleSectionChunks :exec
DELETE FROM chunks c
WHERE c.section_id = $1::bigint
  AND c.source_type || ':' || c.source_id || ':' || c.seq <> ALL ($2::text[])
`

type DeleteStaleSectionChunksParams struct {
	SectionID int64
	Keep      []string
}

func (q *Queries) DeleteStaleSectionChunks(ctx context.Context, arg DeleteStaleSectionChunksParams) error {
	_, err := q.db.Exec(ctx, deleteStaleSectionChunks, arg.SectionID, arg.Keep)
	return err
}

const finishTreeDraft = `-- name: FinishTreeDraft :exec
UPDATE tree_drafts SET status = $1, proposal = $2, error = $3
WHERE id = $4 AND status = 'running'
`

type FinishTreeDraftParams struct {
	Status   string
	Proposal []byte
	Error    string
	ID       int64
}

func (q *Queries) FinishTreeDraft(ctx context.Context, arg FinishTreeDraftParams) error {
	_, err := q.db.Exec(ctx, finishTreeDraft,
		arg.Status,
		arg.Proposal,
		arg.Error,
		arg.ID,
	)
	return err
}

const getDocumentByID = `-- name: GetDocumentByID :one
SELECT d.id, d.project_id, d.number, d.key, d.title, d.client_id, d.filename, d.content_type, d.size_bytes, d.sha256, d.markdown, d.superseded_by, d.uploaded_by, d.created_at, d.archived_at, c.name AS client_name, u.name AS uploader_name, sk.key AS superseded_by_key
FROM documents d
JOIN users u ON u.id = d.uploaded_by
LEFT JOIN clients c ON c.id = d.client_id
LEFT JOIN documents sk ON sk.id = d.superseded_by
WHERE d.id = $1
`

type GetDocumentByIDRow struct {
	Document        Document
	ClientName      *string
	UploaderName    string
	SupersededByKey *string
}

func (q *Queries) GetDocumentByID(ctx context.Context, id int64) (GetDocumentByIDRow, error) {
	row := q.db.QueryRow(ctx, getDocumentByID, id)
	var i GetDocumentByIDRow
	err := row.Scan(
		&i.Document.ID,
		&i.Document.ProjectID,
		&i.Document.Number,
		&i.Document.Key,
		&i.Document.Title,
		&i.Document.ClientID,
		&i.Document.Filename,
		&i.Document.ContentType,
		&i.Document.SizeBytes,
		&i.Document.Sha256,
		&i.Document.Markdown,
		&i.Document.SupersededBy,
		&i.Document.UploadedBy,
		&i.Document.CreatedAt,
		&i.Document.ArchivedAt,
		&i.ClientName,
		&i.UploaderName,
		&i.SupersededByKey,
	)
	return i, err
}

const getDocumentByKey = `-- name: GetDocumentByKey :one
SELECT d.id, d.project_id, d.number, d.key, d.title, d.client_id, d.filename, d.content_type, d.size_bytes, d.sha256, d.markdown, d.superseded_by, d.uploaded_by, d.created_at, d.archived_at, c.name AS client_name, u.name AS uploader_name, sk.key AS superseded_by_key
FROM documents d
JOIN users u ON u.id = d.uploaded_by
LEFT JOIN clients c ON c.id = d.client_id
LEFT JOIN documents sk ON sk.id = d.superseded_by
WHERE d.key = $1
`

type GetDocumentByKeyRow struct {
	Document        Document
	ClientName      *string
	UploaderName    string
	SupersededByKey *string
}

func (q *Queries) GetDocumentByKey(ctx context.Context, key string) (GetDocumentByKeyRow, error) {
	row := q.db.QueryRow(ctx, getDocumentByKey, key)
	var i GetDocumentByKeyRow
	err := row.Scan(
		&i.Document.ID,
		&i.Document.ProjectID,
		&i.Document.Number,
		&i.Document.Key,
		&i.Document.Title,
		&i.Document.ClientID,
		&i.Document.Filename,
		&i.Document.ContentType,
		&i.Document.SizeBytes,
		&i.Document.Sha256,
		&i.Document.Markdown,
		&i.Document.SupersededBy,
		&i.Document.UploadedBy,
		&i.Document.CreatedAt,
		&i.Document.ArchivedAt,
		&i.ClientName,
		&i.UploaderName,
		&i.SupersededByKey,
	)
	return i, err
}

const getSection = `-- name: GetSection :one
SELECT s.id, s.document_id, s.number, s.title, s.level, s.position, s.body, d.key AS document_key, d.title AS document_title, d.project_id, d.client_id, c.name AS client_name,
       d.created_at AS document_created_at, d.archived_at AS document_archived_at, sk.key AS superseded_by_key
FROM document_sections s
JOIN documents d ON d.id = s.document_id
LEFT JOIN clients c ON c.id = d.client_id
LEFT JOIN documents sk ON sk.id = d.superseded_by
WHERE s.id = $1
`

type GetSectionRow struct {
	ID                 int64
	DocumentID         int64
	Number             string
	Title              string
	Level              int32
	Position           int32
	Body               string
	DocumentKey        string
	DocumentTitle      string
	ProjectID          int64
	ClientID           *int64
	ClientName         *string
	DocumentCreatedAt  time.Time
	DocumentArchivedAt *time.Time
	SupersededByKey    *string
}

func (q *Queries) GetSection(ctx context.Context, id int64) (GetSectionRow, error) {
	row := q.db.QueryRow(ctx, getSection, id)
	var i GetSectionRow
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.Number,
		&i.Title,
		&i.Level,
		&i.Position,
		&i.Body,
		&i.DocumentKey,
		&i.DocumentTitle,
		&i.ProjectID,
		&i.ClientID,
		&i.ClientName,
		&i.DocumentCreatedAt,
		&i.DocumentArchivedAt,
		&i.SupersededByKey,
	)
	return i, err
}

const getTreeDraft = `-- name: GetTreeDraft :one
SELECT t.id, t.project_id, t.document_id, t.status, t.proposal, t.used_ai, t.done_parts, t.total_parts, t.error, t.created_by, t.created_at, t.applied_at, d.key AS document_key, d.title AS document_title
FROM tree_drafts t JOIN documents d ON d.id = t.document_id
WHERE t.id = $1
`

type GetTreeDraftRow struct {
	TreeDraft     TreeDraft
	DocumentKey   string
	DocumentTitle string
}

func (q *Queries) GetTreeDraft(ctx context.Context, id int64) (GetTreeDraftRow, error) {
	row := q.db.QueryRow(ctx, getTreeDraft, id)
	var i GetTreeDraftRow
	err := row.Scan(
		&i.TreeDraft.ID,
		&i.TreeDraft.ProjectID,
		&i.TreeDraft.DocumentID,
		&i.TreeDraft.Status,
		&i.TreeDraft.Proposal,
		&i.TreeDraft.UsedAi,
		&i.TreeDraft.DoneParts,
		&i.TreeDraft.TotalParts,
		&i.TreeDraft.Error,
		&i.TreeDraft.CreatedBy,
		&i.TreeDraft.CreatedAt,
		&i.TreeDraft.AppliedAt,
		&i.DocumentKey,
		&i.DocumentTitle,
	)
	return i, err
}

const linkSectionNode = `-- name: LinkSectionNode :exec
INSERT INTO document_section_nodes (section_id, node_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type LinkSectionNodeParams struct {
	SectionID int64
	NodeID    int64
}

func (q *Queries) LinkSectionNode(ctx context.Context, arg LinkSectionNodeParams) error {
	_, err := q.db.Exec(ctx, linkSectionNode, arg.SectionID, arg.NodeID)
	return err
}

const listAllSectionIDs = `-- name: ListAllSectionIDs :many
SELECT s.id FROM document_sections s JOIN documents d ON d.id = s.document_id WHERE d.archived_at IS NULL ORDER BY s.id
`

func (q *Queries) ListAllSectionIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listAllSectionIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentDrafts = `-- name: ListDocumentDrafts :many
SELECT id, status, used_ai, created_at FROM tree_drafts WHERE document_id = $1 ORDER BY id DESC
`

type ListDocumentDraftsRow struct {
	ID        int64
	Status    string
	UsedAi    bool
	CreatedAt time.Time
}

func (q *Queries) ListDocumentDrafts(ctx context.Context, documentID int64) ([]ListDocumentDraftsRow, error) {
	rows, err := q.db.Query(ctx, listDocumentDrafts, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDocumentDraftsRow
	for rows.Next() {
		var i ListDocumentDraftsRow
		if err := rows.Scan(
			&i.ID,
			&i.Status,
			&i.UsedAi,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentSectionIDs = `-- name: ListDocumentSectionIDs :many
SELECT s.id FROM document_sections s WHERE s.document_id = $1 ORDER BY s.position
`

func (q *Queries) ListDocumentSectionIDs(ctx context.Context, documentID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listDocumentSectionIDs, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeSections = `-- name: ListNodeSections :many
SELECT s.number, s.title, s.body, d.key AS document_key, d.title AS document_title, d.client_id, c.name AS client_name,
       d.created_at AS uploaded_at, sk.key AS superseded_by_key
FROM document_sections s
JOIN documents d ON d.id = s.document_id
LEFT JOIN clients c ON c.id = d.client_id
LEFT JOIN documents sk ON sk.id = d.superseded_by
WHERE d.project_id = $1 AND d.archived_at IS NULL
  AND EXISTS (SELECT 1 FROM document_section_nodes sn WHERE sn.section_id = s.id AND sn.node_id = ANY ($2::bigint[]))
  AND ($3::boolean OR d.client_id IS NULL OR d.client_id = ANY ($4::bigint[]))
  AND ($5::bigint IS NULL OR d.client_id = $5::bigint)
  AND (NOT $6::boolean OR d.client_id IS NULL)
  AND ($7::date IS NULL OR d.created_at >= $7::date)
  AND ($8::date IS NULL OR d.created_at < $8::date + 1)
ORDER BY d.superseded_by IS NOT NULL, d.created_at DESC, d.id DESC, s.position
LIMIT 100
`

type ListNodeSectionsParams struct {
	ProjectID  int64
	NodeIds    []int64
	AllClients bool
	ClientIds  []int64
	ClientID   *int64
	CoreOnly   bool
	FromDate   *time.Time
	ToDate     *time.Time
}

type ListNodeSectionsRow struct {
	Number          string
	Title           string
	Body            string
	DocumentKey     string
	DocumentTitle   string
	ClientID        *int64
	ClientName      *string
	UploadedAt      time.Time
	SupersededByKey *string
}

// The visible document sections these nodes came from, for a node page's
// timeline (§7.7): where a menu's history starts. Archived documents never;
// replaced ones come after current ones and say so. from_date and to_date
// filter on the upload day, like a note's decision day.
func (q *Queries) ListNodeSections(ctx context.Context, arg ListNodeSectionsParams) ([]ListNodeSectionsRow, error) {
	rows, err := q.db.Query(ctx, listNodeSections,
		arg.ProjectID,
		arg.NodeIds,
		arg.AllClients,
		arg.ClientIds,
		arg.ClientID,
		arg.CoreOnly,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodeSectionsRow
	for rows.Next() {
		var i ListNodeSectionsRow
		if err := rows.Scan(
			&i.Number,
			&i.Title,
			&i.Body,
			&i.DocumentKey,
			&i.DocumentTitle,
			&i.ClientID,
			&i.ClientName,
			&i.UploadedAt,
			&i.SupersededByKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSectionChunks = `-- name: ListPendingSectionChunks :many
SELECT id, content, content_hash FROM chunks
WHERE section_id = $1::bigint AND (embedding IS NULL OR embed_model IS DISTINCT FROM $2::text)
ORDER BY id
`

type ListPendingSectionChunksParams struct {
	SectionID int64
	Model     string
}

type ListPendingSectionChunksRow struct {
	ID          int64
	Content     string
	ContentHash []byte
}

func (q *Queries) ListPendingSectionChunks(ctx context.Context, arg ListPendingSectionChunksParams) ([]ListPendingSectionChunksRow, error) {
	rows, err := q.db.Query(ctx, listPendingSectionChunks, arg.SectionID, arg.Model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingSectionChunksRow
	for rows.Next() {
		var i ListPendingSectionChunksRow
		if err := rows.Scan(&i.ID, &i.Content, &i.ContentHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectDocuments = `-- name: ListProjectDocuments :many
SELECT d.id, d.key, d.title, d.client_id, c.name AS client_name, d.filename, d.created_at, u.name AS uploader_name, sk.key AS superseded_by_key
FROM documents d
JOIN users u ON u.id = d.uploaded_by
LEFT JOIN clients c ON c.id = d.client_id
LEFT JOIN documents sk ON sk.id = d.superseded_by
WHERE d.project_id = $1 AND d.archived_at IS NULL
  AND ($2::boolean OR d.client_id IS NULL OR d.client_id = ANY ($3::bigint[]))
ORDER BY d.number DESC
`

type ListProjectDocumentsParams struct {
	ProjectID  int64
	AllClients bool
	ClientIds  []int64
}

type ListProjectDocumentsRow struct {
	ID              int64
	Key             string
	Title           string
	ClientID        *int64
	ClientName      *string
	Filename        string
	CreatedAt       time.Time
	UploaderName    string
	SupersededByKey *string
}

// The project's live documents the scope may see (R-MR-15), newest first.
func (q *Queries) ListProjectDocuments(ctx context.Context, arg ListProjectDocumentsParams) ([]ListProjectDocumentsRow, error) {
	rows, err := q.db.Query(ctx, listProjectDocuments, arg.ProjectID, arg.AllClients, arg.ClientIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectDocumentsRow
	for rows.Next() {
		var i ListProjectDocumentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Title,
			&i.ClientID,
			&i.ClientName,
			&i.Filename,
			&i.CreatedAt,
			&i.UploaderName,
			&i.SupersededByKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionNodePaths = `-- name: ListSectionNodePaths :many
WITH RECURSIVE up AS (
  SELECT sn.node_id AS id, n.parent_id, ARRAY[n.name]::text[] AS path, sn.node_id AS origin
  FROM document_section_nodes sn JOIN nodes n ON n.id = sn.node_id
  WHERE sn.section_id = $1
  UNION ALL
  SELECT up.id, p.parent_id, p.name || up.path, up.origin
  FROM up JOIN nodes p ON p.id = up.parent_id
)
SELECT origin AS id, path::text[] AS path FROM up WHERE parent_id IS NULL ORDER BY origin
`

type ListSectionNodePathsRow struct {
	ID   int64
	Path []string
}

// The nodes a section produced, each with its path from the top.
func (q *Queries) ListSectionNodePaths(ctx context.Context, sectionID int64) ([]ListSectionNodePathsRow, error) {
	rows, err := q.db.Query(ctx, listSectionNodePaths, sectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSectionNodePathsRow
	for rows.Next() {
		var i ListSectionNodePathsRow
		if err := rows.Scan(&i.ID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSectionNodes = `-- name: ListSectionNodes :many
SELECT sn.section_id, sn.node_id FROM document_section_nodes sn
JOIN document_sections s ON s.id = sn.section_id
WHERE s.document_id = $1 ORDER BY sn.section_id, sn.node_id
`

func (q *Queries) ListSectionNodes(ctx context.Context, documentID int64) ([]DocumentSectionNode, error) {
	rows, err := q.db.Query(ctx, listSectionNodes, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentSectionNode
	for rows.Next() {
		var i DocumentSectionNode
		if err := rows.Scan(&i.SectionID, &i.NodeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSections = `-- name: ListSections :many
SELECT id, document_id, number, title, level, position, body FROM document_sections WHERE document_id = $1 ORDER BY position
`

func (q *Queries) ListSections(ctx context.Context, documentID int64) ([]DocumentSection, error) {
	rows, err := q.db.Query(ctx, listSections, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DocumentSection
	for rows.Next() {
		var i DocumentSection
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.Number,
			&i.Title,
			&i.Level,
			&i.Position,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockSectionIndex = `-- name: LockSectionIndex :exec
SELECT pg_advisory_xact_lock(hashtextextended('index_section:' || $1::bigint::text, 0))
`

func (q *Queries) LockSectionIndex(ctx context.Context, sectionID int64) error {
	_, err := q.db.Exec(ctx, lockSectionIndex, sectionID)
	return err
}

const nextDocNumber = `-- name: NextDocNumber :one
UPDATE projects SET doc_seq = doc_seq + 1 WHERE id = $1 RETURNING doc_seq
`

func (q *Queries) NextDocNumber(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, nextDocNumber, id)
	var doc_seq int64
	err := row.Scan(&doc_seq)
	return doc_seq, err
}

const saveTreeDraft = `-- name: SaveTreeDraft :exec
UPDATE tree_drafts SET proposal = $2 WHERE id = $1 AND status = 'ready'
`

type SaveTreeDraftParams struct {
	ID       int64
	Proposal []byte
}

func (q *Queries) SaveTreeDraft(ctx context.Context, arg SaveTreeDraftParams) error {
	_, err := q.db.Exec(ctx, saveTreeDraft, arg.ID, arg.Proposal)
	return err
}

const setDocumentSupersededBy = `-- name: SetDocumentSupersededBy :exec
UPDATE documents SET superseded_by = $1 WHERE id = $2
`

type SetDocumentSupersededByParams struct {
	By *int64
	ID int64
}

// Marks a document replaced after its upload, or current again with NULL (§7.7).
func (q *Queries) SetDocumentSupersededBy(ctx context.Context, arg SetDocumentSupersededByParams) error {
	_, err := q.db.Exec(ctx, setDocumentSupersededBy, arg.By, arg.ID)
	return err
}

const setDraftProgress = `-- name: SetDraftProgress :exec
UPDATE tree_drafts SET done_parts = $2 WHERE id = $1
`

type SetDraftProgressParams struct {
	ID        int64
	DoneParts int32
}

func (q *Queries) SetDraftProgress(ctx context.Context, arg SetDraftProgressParams) error {
	_, err := q.db.Exec(ctx, setDraftProgress, arg.ID, arg.DoneParts)
	return err
}

const setTreeDraftStatus = `-- name: SetTreeDraftStatus :one
UPDATE tree_drafts SET status = $1, applied_at = CASE WHEN $1 = 'applied' THEN now() END
WHERE id = $2 AND status = 'ready'
RETURNING id
`

type SetTreeDraftStatusParams struct {
	Status string
	ID     int64
}

// Applies or discards a ready draft once.
func (q *Queries) SetTreeDraftStatus(ctx context.Context, arg SetTreeDraftStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, setTreeDraftStatus, arg.Status, arg.ID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const supersedeDocument = `-- name: SupersedeDocument :exec
UPDATE documents SET superseded_by = $1 WHERE id = $2 AND superseded_by IS NULL
`

type SupersedeDocumentParams struct {
	By *int64
	ID int64
}

func (q *Queries) SupersedeDocument(ctx context.Context, arg SupersedeDocumentParams) error {
	_, err := q.db.Exec(ctx, supersedeDocument, arg.By, arg.ID)
	return err
}

const visibleSectionIDs = `-- name: VisibleSectionIDs :many
SELECT s.id
FROM document_sections s JOIN documents d ON d.id = s.document_id
WHERE s.id = ANY ($1::bigint[]) AND d.archived_at IS NULL
  AND ($2::boolean OR EXISTS (
        SELECT 1 FROM memberships m
        WHERE m.user_id = $3::bigint AND m.project_id = d.project_id
          AND (m.all_clients OR d.client_id IS NULL OR EXISTS (
                SELECT 1 FROM membership_clients mc
                WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = d.client_id))))
`

type VisibleSectionIDsParams struct {
	Ids     []int64
	IsAdmin bool
	UserID  int64
}

// Of the given sections, those the asker may open now (R-MR-15).
func (q *Queries) VisibleSectionIDs(ctx context.Context, arg VisibleSectionIDsParams) ([]int64, error) {
	rows, err := q.db.Query(ctx, visibleSectionIDs, arg.Ids, arg.IsAdmin, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
