// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: home.sql

package db

import (
	"context"
	"time"
)

const countMyTickets = `-- name: CountMyTickets :one
SELECT count(*) AS all_open,
       count(*) FILTER (WHERE t.due_date < $1::date) AS overdue,
       count(*) FILTER (WHERE t.due_date BETWEEN $1::date AND $1::date + 7) AS week,
       count(*) FILTER (WHERE t.reason = '' OR NOT EXISTS (SELECT 1 FROM ticket_nodes tn WHERE tn.ticket_id = t.id)) AS incomplete
FROM tickets t
JOIN statuses s ON s.id = t.status_id
JOIN projects p ON p.id = t.project_id AND p.archived_at IS NULL -- MSL-64
WHERE t.assignee_id = $2::bigint
  AND s.category IN ('todo', 'in_progress')
  AND ($3::boolean OR EXISTS (
        SELECT 1 FROM memberships m
        WHERE m.user_id = $2::bigint AND m.project_id = t.project_id
          AND (m.all_clients OR t.client_id IS NULL OR EXISTS (
                SELECT 1 FROM membership_clients mc
                WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = t.client_id))))
`

type CountMyTicketsParams struct {
	Today   time.Time
	UserID  int64
	IsAdmin bool
}

type CountMyTicketsRow struct {
	AllOpen    int64
	Overdue    int64
	Week       int64
	Incomplete int64
}

// The counts of Home's tabs, over all of the user's open tickets, with the
// same today as ListMyTickets.
func (q *Queries) CountMyTickets(ctx context.Context, arg CountMyTicketsParams) (CountMyTicketsRow, error) {
	row := q.db.QueryRow(ctx, countMyTickets, arg.Today, arg.UserID, arg.IsAdmin)
	var i CountMyTicketsRow
	err := row.Scan(
		&i.AllOpen,
		&i.Overdue,
		&i.Week,
		&i.Incomplete,
	)
	return i, err
}

const countMyTicketsByProject = `-- name: CountMyTicketsByProject :many
SELECT p.key, count(*) AS open
FROM tickets t
JOIN statuses s ON s.id = t.status_id
JOIN projects p ON p.id = t.project_id AND p.archived_at IS NULL -- MSL-64
WHERE t.assignee_id = $1::bigint
  AND s.category IN ('todo', 'in_progress')
  AND ($2::boolean OR EXISTS (
        SELECT 1 FROM memberships m
        WHERE m.user_id = $1::bigint AND m.project_id = t.project_id
          AND (m.all_clients OR t.client_id IS NULL OR EXISTS (
                SELECT 1 FROM membership_clients mc
                WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = t.client_id))))
GROUP BY p.key
ORDER BY p.key
`

type CountMyTicketsByProjectParams struct {
	UserID  int64
	IsAdmin bool
}

type CountMyTicketsByProjectRow struct {
	Key  string
	Open int64
}

// The user's open tickets per project, for Home's My projects.
func (q *Queries) CountMyTicketsByProject(ctx context.Context, arg CountMyTicketsByProjectParams) ([]CountMyTicketsByProjectRow, error) {
	rows, err := q.db.Query(ctx, countMyTicketsByProject, arg.UserID, arg.IsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountMyTicketsByProjectRow
	for rows.Next() {
		var i CountMyTicketsByProjectRow
		if err := rows.Scan(&i.Key, &i.Open); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const latestTicketChanges = `-- name: LatestTicketChanges :many
SELECT DISTINCT ON (x.ticket_id) x.ticket_id::bigint AS ticket_id, x.at::timestamptz AS at, x.id::bigint AS id,
       coalesce(x.actor_id, 0)::bigint AS actor_id, u.name AS actor_name, x.action::text AS action, x.changes::jsonb AS changes
FROM (
  SELECT e.entity_id AS ticket_id, e.occurred_at AS at, e.id, e.actor_id, e.action, e.changes
  FROM audit_events e
  WHERE e.entity = 'ticket' AND e.entity_id = ANY ($1::bigint[])
  UNION ALL
  SELECT c.ticket_id, c.created_at, c.id, c.author_id, 'comment', '{}'::jsonb
  FROM comments c
  WHERE c.ticket_id = ANY ($1::bigint[]) AND c.deleted_at IS NULL
) x
LEFT JOIN users u ON u.id = x.actor_id
ORDER BY x.ticket_id, x.at DESC, x.id DESC
`

type LatestTicketChangesRow struct {
	TicketID  int64
	At        time.Time
	ID        int64
	ActorID   int64
	ActorName *string
	Action    string
	Changes   []byte
}

// The latest change on each of these tickets: a history event or a comment.
// Events of one transaction share a time, so the later row wins. actor_id is 0
// for a change without an actor.
func (q *Queries) LatestTicketChanges(ctx context.Context, ticketIds []int64) ([]LatestTicketChangesRow, error) {
	rows, err := q.db.Query(ctx, latestTicketChanges, ticketIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LatestTicketChangesRow
	for rows.Next() {
		var i LatestTicketChangesRow
		if err := rows.Scan(
			&i.TicketID,
			&i.At,
			&i.ID,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.Changes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAttention = `-- name: ListAttention :many
SELECT p.key, p.name,
       count(*) FILTER (WHERE t.due_date < $1::date) AS overdue,
       count(*) FILTER (WHERE t.due_date BETWEEN $1::date AND $1::date + 7) AS week,
       count(*) FILTER (WHERE t.assignee_id IS NULL) AS unassigned,
       count(*) FILTER (WHERE t.reason = '') AS no_reason,
       count(*) FILTER (WHERE weak_reason(t.reason)) AS weak_reason,
       count(*) FILTER (WHERE NOT EXISTS (SELECT 1 FROM ticket_nodes tn WHERE tn.ticket_id = t.id)) AS no_menu,
       count(*) FILTER (WHERE t.updated_at < now() - interval '7 days') AS stale
FROM tickets t
JOIN statuses s ON s.id = t.status_id
JOIN projects p ON p.id = t.project_id AND p.archived_at IS NULL -- MSL-64
WHERE s.category IN ('todo', 'in_progress')
  AND ($2::boolean OR EXISTS (
        SELECT 1 FROM memberships m
        WHERE m.user_id = $3::bigint AND m.project_id = t.project_id AND m.role = 'admin'))
GROUP BY p.id, p.key, p.name
ORDER BY p.key
`

type ListAttentionParams struct {
	Today   time.Time
	IsAdmin bool
	UserID  int64
}

type ListAttentionRow struct {
	Key        string
	Name       string
	Overdue    int64
	Week       int64
	Unassigned int64
	NoReason   int64
	WeakReason int64
	NoMenu     int64
	Stale      int64
}

// Home's Needs attention (MSL-9): for each project the user runs as project
// admin (every project for a system admin), the open tickets that need a
// lead's eye, counted as Workload counts them. Project admins see all clients.
func (q *Queries) ListAttention(ctx context.Context, arg ListAttentionParams) ([]ListAttentionRow, error) {
	rows, err := q.db.Query(ctx, listAttention, arg.Today, arg.IsAdmin, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAttentionRow
	for rows.Next() {
		var i ListAttentionRow
		if err := rows.Scan(
			&i.Key,
			&i.Name,
			&i.Overdue,
			&i.Week,
			&i.Unassigned,
			&i.NoReason,
			&i.WeakReason,
			&i.NoMenu,
			&i.Stale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyTickets = `-- name: ListMyTickets :many
SELECT t.id, t.key, t.title, t.type, t.priority, t.due_date, t.client_id, c.name AS client_name, s.id, s.project_id, s.name, s.category, s.position, s.color, s.is_default,
       t.reason = '' AS missing_reason,
       NOT EXISTS (SELECT 1 FROM ticket_nodes tn WHERE tn.ticket_id = t.id) AS missing_menus,
       coalesce((SELECT coalesce(pn.name || ' › ', '') || n.name
                 FROM ticket_nodes tn JOIN nodes n ON n.id = tn.node_id LEFT JOIN nodes pn ON pn.id = n.parent_id
                 WHERE tn.ticket_id = t.id ORDER BY lower(n.name), n.id LIMIT 1), '')::text AS menu
FROM tickets t
JOIN statuses s ON s.id = t.status_id
JOIN projects p ON p.id = t.project_id AND p.archived_at IS NULL -- MSL-64
LEFT JOIN clients c ON c.id = t.client_id
WHERE t.assignee_id = $1::bigint
  AND s.category IN ('todo', 'in_progress')
  AND ($2::boolean OR EXISTS (
        SELECT 1 FROM memberships m
        WHERE m.user_id = $1::bigint AND m.project_id = t.project_id
          AND (m.all_clients OR t.client_id IS NULL OR EXISTS (
                SELECT 1 FROM membership_clients mc
                WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = t.client_id))))
  AND ($3::text = 'all'
       OR ($3::text = 'overdue' AND t.due_date < $4::date)
       OR ($3::text = 'week' AND t.due_date BETWEEN $4::date AND $4::date + 7)
       OR ($3::text = 'incomplete' AND (t.reason = '' OR NOT EXISTS (SELECT 1 FROM ticket_nodes tn WHERE tn.ticket_id = t.id))))
ORDER BY t.due_date NULLS LAST, array_position(ARRAY['urgent', 'high', 'medium', 'low'], t.priority), t.project_id, t.number
LIMIT $6 OFFSET $5
`

type ListMyTicketsParams struct {
	UserID  int64
	IsAdmin bool
	View    string
	Today   time.Time
	Off     int32
	Lim     int32
}

type ListMyTicketsRow struct {
	ID            int64
	Key           string
	Title         string
	Type          string
	Priority      string
	DueDate       *time.Time
	ClientID      *int64
	ClientName    *string
	Status        Status
	MissingReason bool
	MissingMenus  bool
	Menu          string
}

// Home's My tickets (FSD §6.4): the open tickets assigned to the user that
// they may see in any project (R-AC-2, R-AC-3), by due date (none last), then
// priority and key. view narrows them: overdue, week (due today through 7 days
// ahead) or incomplete (no reason or no menu). today is the date on the user's
// calendar, in their profile's timezone. menu is the first menu's parent and
// name, or ” without one.
func (q *Queries) ListMyTickets(ctx context.Context, arg ListMyTicketsParams) ([]ListMyTicketsRow, error) {
	rows, err := q.db.Query(ctx, listMyTickets,
		arg.UserID,
		arg.IsAdmin,
		arg.View,
		arg.Today,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMyTicketsRow
	for rows.Next() {
		var i ListMyTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Title,
			&i.Type,
			&i.Priority,
			&i.DueDate,
			&i.ClientID,
			&i.ClientName,
			&i.Status.ID,
			&i.Status.ProjectID,
			&i.Status.Name,
			&i.Status.Category,
			&i.Status.Position,
			&i.Status.Color,
			&i.Status.IsDefault,
			&i.MissingReason,
			&i.MissingMenus,
			&i.Menu,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentTickets = `-- name: ListRecentTickets :many
SELECT t.id, t.key, t.title, t.type, t.updated_at, s.id, s.project_id, s.name, s.category, s.position, s.color, s.is_default
FROM tickets t
JOIN statuses s ON s.id = t.status_id
JOIN projects p ON p.id = t.project_id AND p.archived_at IS NULL -- MSL-64
WHERE ($1::boolean OR EXISTS (
        SELECT 1 FROM memberships m
        WHERE m.user_id = $2::bigint AND m.project_id = t.project_id
          AND (m.all_clients OR t.client_id IS NULL OR EXISTS (
                SELECT 1 FROM membership_clients mc
                WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = t.client_id))))
ORDER BY t.updated_at DESC, t.id DESC
LIMIT 10
`

type ListRecentTicketsParams struct {
	IsAdmin bool
	UserID  int64
}

type ListRecentTicketsRow struct {
	ID        int64
	Key       string
	Title     string
	Type      string
	UpdatedAt time.Time
	Status    Status
}

// Home's Recently updated (FSD §6.4): the tickets the user may see that changed
// last. Comments, files and decision records touch updated_at (00006).
func (q *Queries) ListRecentTickets(ctx context.Context, arg ListRecentTicketsParams) ([]ListRecentTicketsRow, error) {
	rows, err := q.db.Query(ctx, listRecentTickets, arg.IsAdmin, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentTicketsRow
	for rows.Next() {
		var i ListRecentTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Title,
			&i.Type,
			&i.UpdatedAt,
			&i.Status.ID,
			&i.Status.ProjectID,
			&i.Status.Name,
			&i.Status.Category,
			&i.Status.Position,
			&i.Status.Color,
			&i.Status.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const projectSetupStatus = `-- name: ProjectSetupStatus :one
SELECT EXISTS (SELECT 1 FROM project_clients WHERE project_id = $1::bigint) AS clients,
       (SELECT count(*) FROM memberships WHERE project_id = $1::bigint) > 1 AS team,
       EXISTS (SELECT 1 FROM documents WHERE project_id = $1::bigint) AS documents,
       EXISTS (SELECT 1 FROM nodes WHERE project_id = $1::bigint) AS tree,
       EXISTS (SELECT 1 FROM tickets WHERE project_id = $1::bigint) AS tickets,
       EXISTS (SELECT 1 FROM git_repos WHERE project_id = $1::bigint) AS repos
`

type ProjectSetupStatusRow struct {
	Clients   bool
	Team      bool
	Documents bool
	Tree      bool
	Tickets   bool
	Repos     bool
}

// How far a project is set up, for its checklist on the board (MSL-48).
func (q *Queries) ProjectSetupStatus(ctx context.Context, pid int64) (ProjectSetupStatusRow, error) {
	row := q.db.QueryRow(ctx, projectSetupStatus, pid)
	var i ProjectSetupStatusRow
	err := row.Scan(
		&i.Clients,
		&i.Team,
		&i.Documents,
		&i.Tree,
		&i.Tickets,
		&i.Repos,
	)
	return i, err
}

const setupStatus = `-- name: SetupStatus :one
SELECT (SELECT count(*) FROM users WHERE disabled_at IS NULL) > 1 AS invited,
       EXISTS (SELECT 1 FROM projects) AS project,
       EXISTS (SELECT 1 FROM nodes) AS tree,
       EXISTS (SELECT 1 FROM tickets) AS history,
       coalesce((SELECT key FROM projects ORDER BY id LIMIT 1), '')::text AS first_project
`

type SetupStatusRow struct {
	Invited      bool
	Project      bool
	Tree         bool
	History      bool
	FirstProject string
}

// How far a new server is set up, for Home's checklist (MSL-18).
func (q *Queries) SetupStatus(ctx context.Context) (SetupStatusRow, error) {
	row := q.db.QueryRow(ctx, setupStatus)
	var i SetupStatusRow
	err := row.Scan(
		&i.Invited,
		&i.Project,
		&i.Tree,
		&i.History,
		&i.FirstProject,
	)
	return i, err
}
