// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: imports.sql

package db

import (
	"context"
	"time"
)

const countImportedComments = `-- name: CountImportedComments :one
SELECT count(*) FROM comments c JOIN tickets t ON t.id = c.ticket_id WHERE t.project_id = $1 AND c.external_hash IS NOT NULL
`

func (q *Queries) CountImportedComments(ctx context.Context, projectID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countImportedComments, projectID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImportRun = `-- name: CreateImportRun :one

INSERT INTO import_runs (kind, project_id, file_name, file_path, mapping, status, created_by)
VALUES ('tickets', $1, $2, $3, $4, 'uploaded', $5)
RETURNING id, kind, project_id, file_name, file_path, mapping, status, stats, errors, created_by, created_at, finished_at
`

type CreateImportRunParams struct {
	ProjectID int64
	FileName  string
	FilePath  string
	Mapping   []byte
	CreatedBy int64
}

// Ticket imports (FSD §14.2).
func (q *Queries) CreateImportRun(ctx context.Context, arg CreateImportRunParams) (ImportRun, error) {
	row := q.db.QueryRow(ctx, createImportRun,
		arg.ProjectID,
		arg.FileName,
		arg.FilePath,
		arg.Mapping,
		arg.CreatedBy,
	)
	var i ImportRun
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.ProjectID,
		&i.FileName,
		&i.FilePath,
		&i.Mapping,
		&i.Status,
		&i.Stats,
		&i.Errors,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createImportedTicket = `-- name: CreateImportedTicket :one
INSERT INTO tickets (project_id, number, key, type, title, description, reason, status_id, client_id,
                     requester_contact_id, requester_user_id, reporter_id, assignee_id, priority,
                     source, external_ref, external_meta, created_at, updated_at, closed_at)
VALUES ($1, $2, $3, $4, $5, $6,
        $7, $8, $9, $10, $11,
        $12, $13, $14, 'import', $15, $16,
        $17, $17, $18)
RETURNING id, project_id, number, key, type, title, description, reason, status_id, client_id, requester_contact_id, requester_user_id, reporter_id, assignee_id, priority, due_date, version, created_at, updated_at, closed_at, source, external_ref, external_meta, estimate_hours, labels, accepted_contact_id, accepted_on, acceptance_note, release_id
`

type CreateImportedTicketParams struct {
	ProjectID          int64
	Number             int64
	Key                string
	Type               string
	Title              string
	Description        string
	Reason             string
	StatusID           int64
	ClientID           *int64
	RequesterContactID *int64
	RequesterUserID    *int64
	ReporterID         int64
	AssigneeID         *int64
	Priority           string
	ExternalRef        *string
	ExternalMeta       []byte
	CreatedAt          time.Time
	ClosedAt           *time.Time
}

// An imported ticket keeps its old key and dates; source = import (R-IN-2).
func (q *Queries) CreateImportedTicket(ctx context.Context, arg CreateImportedTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createImportedTicket,
		arg.ProjectID,
		arg.Number,
		arg.Key,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Reason,
		arg.StatusID,
		arg.ClientID,
		arg.RequesterContactID,
		arg.RequesterUserID,
		arg.ReporterID,
		arg.AssigneeID,
		arg.Priority,
		arg.ExternalRef,
		arg.ExternalMeta,
		arg.CreatedAt,
		arg.ClosedAt,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Key,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Reason,
		&i.StatusID,
		&i.ClientID,
		&i.RequesterContactID,
		&i.RequesterUserID,
		&i.ReporterID,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.Source,
		&i.ExternalRef,
		&i.ExternalMeta,
		&i.EstimateHours,
		&i.Labels,
		&i.AcceptedContactID,
		&i.AcceptedOn,
		&i.AcceptanceNote,
		&i.ReleaseID,
	)
	return i, err
}

const findInternalContact = `-- name: FindInternalContact :one
SELECT id FROM contacts WHERE client_id IS NULL AND lower(name) = lower($1) ORDER BY id LIMIT 1
`

func (q *Queries) FindInternalContact(ctx context.Context, lower string) (int64, error) {
	row := q.db.QueryRow(ctx, findInternalContact, lower)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const findUserByNameOrEmail = `-- name: FindUserByNameOrEmail :one
SELECT id FROM users WHERE lower(name) = lower($1) OR lower(email) = lower($1)
ORDER BY (lower(email) = lower($1)) DESC, id LIMIT 1
`

func (q *Queries) FindUserByNameOrEmail(ctx context.Context, who string) (int64, error) {
	row := q.db.QueryRow(ctx, findUserByNameOrEmail, who)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getImportRun = `-- name: GetImportRun :one
SELECT r.id, r.kind, r.project_id, r.file_name, r.file_path, r.mapping, r.status, r.stats, r.errors, r.created_by, r.created_at, r.finished_at, p.key AS project_key, u.name AS created_by_name
FROM import_runs r JOIN projects p ON p.id = r.project_id JOIN users u ON u.id = r.created_by
WHERE r.id = $1
`

type GetImportRunRow struct {
	ImportRun     ImportRun
	ProjectKey    string
	CreatedByName string
}

func (q *Queries) GetImportRun(ctx context.Context, id int64) (GetImportRunRow, error) {
	row := q.db.QueryRow(ctx, getImportRun, id)
	var i GetImportRunRow
	err := row.Scan(
		&i.ImportRun.ID,
		&i.ImportRun.Kind,
		&i.ImportRun.ProjectID,
		&i.ImportRun.FileName,
		&i.ImportRun.FilePath,
		&i.ImportRun.Mapping,
		&i.ImportRun.Status,
		&i.ImportRun.Stats,
		&i.ImportRun.Errors,
		&i.ImportRun.CreatedBy,
		&i.ImportRun.CreatedAt,
		&i.ImportRun.FinishedAt,
		&i.ProjectKey,
		&i.CreatedByName,
	)
	return i, err
}

const getTicketByExternalRef = `-- name: GetTicketByExternalRef :one
SELECT id, project_id, number, key, type, title, description, reason, status_id, client_id, requester_contact_id, requester_user_id, reporter_id, assignee_id, priority, due_date, version, created_at, updated_at, closed_at, source, external_ref, external_meta, estimate_hours, labels, accepted_contact_id, accepted_on, acceptance_note, release_id FROM tickets WHERE project_id = $1 AND upper(external_ref) = upper($2)
`

type GetTicketByExternalRefParams struct {
	ProjectID int64
	Ref       interface{}
}

func (q *Queries) GetTicketByExternalRef(ctx context.Context, arg GetTicketByExternalRefParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByExternalRef, arg.ProjectID, arg.Ref)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Key,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Reason,
		&i.StatusID,
		&i.ClientID,
		&i.RequesterContactID,
		&i.RequesterUserID,
		&i.ReporterID,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.Source,
		&i.ExternalRef,
		&i.ExternalMeta,
		&i.EstimateHours,
		&i.Labels,
		&i.AcceptedContactID,
		&i.AcceptedOn,
		&i.AcceptanceNote,
		&i.ReleaseID,
	)
	return i, err
}

const insertImportedComment = `-- name: InsertImportedComment :execrows
INSERT INTO comments (ticket_id, author_id, author_label, internal, body, created_at, external_hash)
VALUES ($1, $2, $3, true, $4, $5, $6)
ON CONFLICT (ticket_id, external_hash) WHERE external_hash IS NOT NULL DO NOTHING
`

type InsertImportedCommentParams struct {
	TicketID     int64
	AuthorID     *int64
	AuthorLabel  *string
	Body         string
	CreatedAt    time.Time
	ExternalHash []byte
}

// Comments match on a hash of the ticket's old key, date, author and body (R-IN-1).
func (q *Queries) InsertImportedComment(ctx context.Context, arg InsertImportedCommentParams) (int64, error) {
	result, err := q.db.Exec(ctx, insertImportedComment,
		arg.TicketID,
		arg.AuthorID,
		arg.AuthorLabel,
		arg.Body,
		arg.CreatedAt,
		arg.ExternalHash,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const linkImportedNodes = `-- name: LinkImportedNodes :exec
INSERT INTO ticket_nodes (ticket_id, node_id)
SELECT $1::bigint, unnest($2::bigint[])
ON CONFLICT DO NOTHING
`

type LinkImportedNodesParams struct {
	TicketID int64
	NodeIds  []int64
}

// A re-import adds menus and keeps the ones already linked.
func (q *Queries) LinkImportedNodes(ctx context.Context, arg LinkImportedNodesParams) error {
	_, err := q.db.Exec(ctx, linkImportedNodes, arg.TicketID, arg.NodeIds)
	return err
}

const listExternalRefs = `-- name: ListExternalRefs :many
SELECT upper(external_ref)::text FROM tickets WHERE project_id = $1 AND external_ref IS NOT NULL
`

func (q *Queries) ListExternalRefs(ctx context.Context, projectID int64) ([]string, error) {
	rows, err := q.db.Query(ctx, listExternalRefs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var column_1 string
		if err := rows.Scan(&column_1); err != nil {
			return nil, err
		}
		items = append(items, column_1)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportRuns = `-- name: ListImportRuns :many
SELECT r.id, r.kind, r.project_id, r.file_name, r.file_path, r.mapping, r.status, r.stats, r.errors, r.created_by, r.created_at, r.finished_at, p.key AS project_key, u.name AS created_by_name
FROM import_runs r JOIN projects p ON p.id = r.project_id JOIN users u ON u.id = r.created_by
ORDER BY r.id DESC LIMIT 100
`

type ListImportRunsRow struct {
	ImportRun     ImportRun
	ProjectKey    string
	CreatedByName string
}

func (q *Queries) ListImportRuns(ctx context.Context) ([]ListImportRunsRow, error) {
	rows, err := q.db.Query(ctx, listImportRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImportRunsRow
	for rows.Next() {
		var i ListImportRunsRow
		if err := rows.Scan(
			&i.ImportRun.ID,
			&i.ImportRun.Kind,
			&i.ImportRun.ProjectID,
			&i.ImportRun.FileName,
			&i.ImportRun.FilePath,
			&i.ImportRun.Mapping,
			&i.ImportRun.Status,
			&i.ImportRun.Stats,
			&i.ImportRun.Errors,
			&i.ImportRun.CreatedBy,
			&i.ImportRun.CreatedAt,
			&i.ImportRun.FinishedAt,
			&i.ProjectKey,
			&i.CreatedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveImportPlan = `-- name: SaveImportPlan :exec
UPDATE import_runs SET mapping = $1, status = $2, stats = $3, errors = $4
WHERE id = $5
`

type SaveImportPlanParams struct {
	Mapping []byte
	Status  string
	Stats   []byte
	Errors  []byte
	ID      int64
}

func (q *Queries) SaveImportPlan(ctx context.Context, arg SaveImportPlanParams) error {
	_, err := q.db.Exec(ctx, saveImportPlan,
		arg.Mapping,
		arg.Status,
		arg.Stats,
		arg.Errors,
		arg.ID,
	)
	return err
}

const setImportStatus = `-- name: SetImportStatus :exec
UPDATE import_runs SET status = $1, stats = $2,
  finished_at = CASE WHEN $1::text IN ('done', 'failed') THEN now() END
WHERE id = $3
`

type SetImportStatusParams struct {
	Status string
	Stats  []byte
	ID     int64
}

func (q *Queries) SetImportStatus(ctx context.Context, arg SetImportStatusParams) error {
	_, err := q.db.Exec(ctx, setImportStatus, arg.Status, arg.Stats, arg.ID)
	return err
}

const updateImportedTicket = `-- name: UpdateImportedTicket :one
UPDATE tickets SET type = $1, title = $2, description = $3,
  status_id = $4, priority = $5, assignee_id = $6,
  external_meta = $7, closed_at = $8, version = version + 1, updated_at = now()
WHERE id = $9
RETURNING id, project_id, number, key, type, title, description, reason, status_id, client_id, requester_contact_id, requester_user_id, reporter_id, assignee_id, priority, due_date, version, created_at, updated_at, closed_at, source, external_ref, external_meta, estimate_hours, labels, accepted_contact_id, accepted_on, acceptance_note, release_id
`

type UpdateImportedTicketParams struct {
	Type         string
	Title        string
	Description  string
	StatusID     int64
	Priority     string
	AssigneeID   *int64
	ExternalMeta []byte
	ClosedAt     *time.Time
	ID           int64
}

// A re-import updates what the old tool owns and leaves Zettra's own work
// (reason, menus added by hand, decision records) alone.
func (q *Queries) UpdateImportedTicket(ctx context.Context, arg UpdateImportedTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateImportedTicket,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.StatusID,
		arg.Priority,
		arg.AssigneeID,
		arg.ExternalMeta,
		arg.ClosedAt,
		arg.ID,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Key,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Reason,
		&i.StatusID,
		&i.ClientID,
		&i.RequesterContactID,
		&i.RequesterUserID,
		&i.ReporterID,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.Source,
		&i.ExternalRef,
		&i.ExternalMeta,
		&i.EstimateHours,
		&i.Labels,
		&i.AcceptedContactID,
		&i.AcceptedOn,
		&i.AcceptanceNote,
		&i.ReleaseID,
	)
	return i, err
}
