// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: index.sql

package db

import (
	"context"
	"time"
)

const deleteStaleChunks = `-- name: DeleteStaleChunks :exec
DELETE FROM chunks c
WHERE c.ticket_id = $1::bigint
  AND c.source_type || ':' || c.source_id || ':' || c.seq <> ALL ($2::text[])
`

type DeleteStaleChunksParams struct {
	TicketID int64
	Keep     []string
}

// Drops the ticket's chunks that the rebuild no longer produced: a deleted
// comment, a drafted decision, the tail of a shorter text.
// keep holds "type:id:seq" of every chunk the rebuild wrote.
func (q *Queries) DeleteStaleChunks(ctx context.Context, arg DeleteStaleChunksParams) error {
	_, err := q.db.Exec(ctx, deleteStaleChunks, arg.TicketID, arg.Keep)
	return err
}

const getClientByName = `-- name: GetClientByName :one
SELECT id, name, code, aliases, archived_at FROM clients WHERE lower(name) = lower($1)
`

func (q *Queries) GetClientByName(ctx context.Context, lower string) (Client, error) {
	row := q.db.QueryRow(ctx, getClientByName, lower)
	var i Client
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.Aliases,
		&i.ArchivedAt,
	)
	return i, err
}

const getNodeIDByPath = `-- name: GetNodeIDByPath :one
WITH RECURSIVE walk AS (
  SELECT n.id, 1 AS depth
  FROM nodes n JOIN projects p ON p.id = n.project_id
  WHERE p.key = $2 AND n.parent_id IS NULL AND n.name = ($1::text[])[1]
  UNION ALL
  SELECT n.id, w.depth + 1
  FROM nodes n JOIN walk w ON n.parent_id = w.id
  WHERE n.name = ($1::text[])[w.depth + 1]
)
SELECT id FROM walk WHERE depth = cardinality($1::text[])
`

type GetNodeIDByPathParams struct {
	Path       []string
	ProjectKey string
}

// A node by its names from the top of the tree, for the eval's node chips.
func (q *Queries) GetNodeIDByPath(ctx context.Context, arg GetNodeIDByPathParams) (int64, error) {
	row := q.db.QueryRow(ctx, getNodeIDByPath, arg.Path, arg.ProjectKey)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getTicketSource = `-- name: GetTicketSource :one
SELECT t.id, t.key, t.type, t.title, t.description, t.reason, t.project_id, t.client_id,
       t.requester_contact_id, t.requester_user_id, t.reporter_id, t.assignee_id, t.created_at, t.closed_at,
       s.name AS status_name, c.name AS client_name,
       rc.name AS contact_name, rc.title AS contact_title, rcc.name AS contact_client_name,
       ru.name AS requester_user_name
FROM tickets t
JOIN statuses s ON s.id = t.status_id
LEFT JOIN clients c ON c.id = t.client_id
LEFT JOIN contacts rc ON rc.id = t.requester_contact_id
LEFT JOIN clients rcc ON rcc.id = rc.client_id
LEFT JOIN users ru ON ru.id = t.requester_user_id
WHERE t.id = $1
`

type GetTicketSourceRow struct {
	ID                 int64
	Key                string
	Type               string
	Title              string
	Description        string
	Reason             string
	ProjectID          int64
	ClientID           *int64
	RequesterContactID *int64
	RequesterUserID    *int64
	ReporterID         int64
	AssigneeID         *int64
	CreatedAt          time.Time
	ClosedAt           *time.Time
	StatusName         string
	ClientName         *string
	ContactName        *string
	ContactTitle       *string
	ContactClientName  *string
	RequesterUserName  *string
}

// Everything a ticket's chunks say about it (FSD §13.1).
func (q *Queries) GetTicketSource(ctx context.Context, id int64) (GetTicketSourceRow, error) {
	row := q.db.QueryRow(ctx, getTicketSource, id)
	var i GetTicketSourceRow
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Reason,
		&i.ProjectID,
		&i.ClientID,
		&i.RequesterContactID,
		&i.RequesterUserID,
		&i.ReporterID,
		&i.AssigneeID,
		&i.CreatedAt,
		&i.ClosedAt,
		&i.StatusName,
		&i.ClientName,
		&i.ContactName,
		&i.ContactTitle,
		&i.ContactClientName,
		&i.RequesterUserName,
	)
	return i, err
}

const listAllTicketIDs = `-- name: ListAllTicketIDs :many
SELECT id FROM tickets ORDER BY id DESC
`

func (q *Queries) ListAllTicketIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listAllTicketIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommentSources = `-- name: ListCommentSources :many
SELECT c.id, u.name AS author, c.internal, c.body, c.created_at
FROM comments c
JOIN users u ON u.id = c.author_id
WHERE c.ticket_id = $1 AND c.deleted_at IS NULL
ORDER BY c.created_at, c.id
`

type ListCommentSourcesRow struct {
	ID        int64
	Author    string
	Internal  bool
	Body      string
	CreatedAt time.Time
}

func (q *Queries) ListCommentSources(ctx context.Context, ticketID int64) ([]ListCommentSourcesRow, error) {
	rows, err := q.db.Query(ctx, listCommentSources, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentSourcesRow
	for rows.Next() {
		var i ListCommentSourcesRow
		if err := rows.Scan(
			&i.ID,
			&i.Author,
			&i.Internal,
			&i.Body,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingTicketChunks = `-- name: ListPendingTicketChunks :many
SELECT id, content, content_hash FROM chunks
WHERE ticket_id = $1::bigint AND (embedding IS NULL OR embed_model IS DISTINCT FROM $2::text)
ORDER BY id
`

type ListPendingTicketChunksParams struct {
	TicketID int64
	Model    string
}

type ListPendingTicketChunksRow struct {
	ID          int64
	Content     string
	ContentHash []byte
}

func (q *Queries) ListPendingTicketChunks(ctx context.Context, arg ListPendingTicketChunksParams) ([]ListPendingTicketChunksRow, error) {
	rows, err := q.db.Query(ctx, listPendingTicketChunks, arg.TicketID, arg.Model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingTicketChunksRow
	for rows.Next() {
		var i ListPendingTicketChunksRow
		if err := rows.Scan(&i.ID, &i.Content, &i.ContentHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectTicketIDs = `-- name: ListProjectTicketIDs :many
SELECT id FROM tickets WHERE project_id = $1 ORDER BY id
`

func (q *Queries) ListProjectTicketIDs(ctx context.Context, projectID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listProjectTicketIDs, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketIDsOfClient = `-- name: ListTicketIDsOfClient :many
SELECT id FROM tickets WHERE client_id = $1::bigint ORDER BY id
`

func (q *Queries) ListTicketIDsOfClient(ctx context.Context, clientID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listTicketIDsOfClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketIDsUnderNode = `-- name: ListTicketIDsUnderNode :many
WITH RECURSIVE sub AS (
  SELECT n.id FROM nodes n WHERE n.id = $1
  UNION ALL
  SELECT n.id FROM nodes n JOIN sub ON n.parent_id = sub.id
)
SELECT DISTINCT tn.ticket_id FROM ticket_nodes tn JOIN sub ON sub.id = tn.node_id ORDER BY 1
`

// Tickets on a node or its sub-nodes, whose chunks name the node's path.
func (q *Queries) ListTicketIDsUnderNode(ctx context.Context, id int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listTicketIDsUnderNode, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var ticket_id int64
		if err := rows.Scan(&ticket_id); err != nil {
			return nil, err
		}
		items = append(items, ticket_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTicketNodePaths = `-- name: ListTicketNodePaths :many
WITH RECURSIVE up AS (
  SELECT tn.node_id AS id, n.parent_id, ARRAY[n.name]::text[] AS path
  FROM ticket_nodes tn
  JOIN nodes n ON n.id = tn.node_id
  WHERE tn.ticket_id = $1
  UNION ALL
  SELECT up.id, p.parent_id, p.name || up.path
  FROM up
  JOIN nodes p ON p.id = up.parent_id
)
SELECT id, path::text[] AS path FROM up WHERE parent_id IS NULL ORDER BY id
`

type ListTicketNodePathsRow struct {
	ID   int64
	Path []string
}

// The ticket's menus, each with the names from the top of the tree down.
func (q *Queries) ListTicketNodePaths(ctx context.Context, ticketID int64) ([]ListTicketNodePathsRow, error) {
	rows, err := q.db.Query(ctx, listTicketNodePaths, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketNodePathsRow
	for rows.Next() {
		var i ListTicketNodePathsRow
		if err := rows.Scan(&i.ID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTicketIndex = `-- name: LockTicketIndex :exec
SELECT pg_advisory_xact_lock(hashtextextended('index_ticket:' || $1::bigint::text, 0))
`

// One index job per ticket at a time (§13.2); the lock ends with the transaction.
func (q *Queries) LockTicketIndex(ctx context.Context, ticketID int64) error {
	_, err := q.db.Exec(ctx, lockTicketIndex, ticketID)
	return err
}
