// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: links.sql

package db

import (
	"context"
	"time"
)

const createLink = `-- name: CreateLink :one

INSERT INTO ticket_links (from_id, to_id, type, created_by)
VALUES ($1, $2, $3, $4)
ON CONFLICT (from_id, to_id, type) DO NOTHING
RETURNING id, from_id, to_id, type, created_by, created_at
`

type CreateLinkParams struct {
	FromID    int64
	ToID      int64
	Type      string
	CreatedBy int64
}

// Ticket links (FSD §8.8): stored once, shown on both tickets.
func (q *Queries) CreateLink(ctx context.Context, arg CreateLinkParams) (TicketLink, error) {
	row := q.db.QueryRow(ctx, createLink,
		arg.FromID,
		arg.ToID,
		arg.Type,
		arg.CreatedBy,
	)
	var i TicketLink
	err := row.Scan(
		&i.ID,
		&i.FromID,
		&i.ToID,
		&i.Type,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLink = `-- name: DeleteLink :exec
DELETE FROM ticket_links WHERE id = $1
`

func (q *Queries) DeleteLink(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteLink, id)
	return err
}

const getLink = `-- name: GetLink :one
SELECT id, from_id, to_id, type, created_by, created_at FROM ticket_links WHERE id = $1
`

func (q *Queries) GetLink(ctx context.Context, id int64) (TicketLink, error) {
	row := q.db.QueryRow(ctx, getLink, id)
	var i TicketLink
	err := row.Scan(
		&i.ID,
		&i.FromID,
		&i.ToID,
		&i.Type,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getTicketByID = `-- name: GetTicketByID :one
SELECT id, project_id, number, key, type, title, description, reason, status_id, client_id, requester_contact_id, requester_user_id, reporter_id, assignee_id, priority, due_date, version, created_at, updated_at, closed_at FROM tickets WHERE id = $1
`

func (q *Queries) GetTicketByID(ctx context.Context, id int64) (Ticket, error) {
	row := q.db.QueryRow(ctx, getTicketByID, id)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Key,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Reason,
		&i.StatusID,
		&i.ClientID,
		&i.RequesterContactID,
		&i.RequesterUserID,
		&i.ReporterID,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
	)
	return i, err
}

const listTicketLinks = `-- name: ListTicketLinks :many
SELECT l.id, l.type, (l.from_id = $1)::boolean AS outgoing,
       o.id AS other_id, o.key AS other_key, o.title AS other_title, o.project_id AS other_project_id,
       o.client_id AS other_client_id, o.closed_at AS other_closed_at, s.id, s.project_id, s.name, s.category, s.position, s.color, s.is_default, l.created_at
FROM ticket_links l
JOIN tickets o ON o.id = CASE WHEN l.from_id = $1 THEN l.to_id ELSE l.from_id END
JOIN statuses s ON s.id = o.status_id
WHERE l.from_id = $1 OR l.to_id = $1
ORDER BY l.created_at, l.id
`

type ListTicketLinksRow struct {
	ID             int64
	Type           string
	Outgoing       bool
	OtherID        int64
	OtherKey       string
	OtherTitle     string
	OtherProjectID int64
	OtherClientID  *int64
	OtherClosedAt  *time.Time
	Status         Status
	CreatedAt      time.Time
}

// Both directions, each with the other ticket; the caller keeps the ones the
// reader may see (R-TK-6).
func (q *Queries) ListTicketLinks(ctx context.Context, ticketID int64) ([]ListTicketLinksRow, error) {
	rows, err := q.db.Query(ctx, listTicketLinks, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketLinksRow
	for rows.Next() {
		var i ListTicketLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Outgoing,
			&i.OtherID,
			&i.OtherKey,
			&i.OtherTitle,
			&i.OtherProjectID,
			&i.OtherClientID,
			&i.OtherClosedAt,
			&i.Status.ID,
			&i.Status.ProjectID,
			&i.Status.Name,
			&i.Status.Category,
			&i.Status.Position,
			&i.Status.Color,
			&i.Status.IsDefault,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
