// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: memberships.sql

package db

import (
	"context"
)

const addMembershipClients = `-- name: AddMembershipClients :exec
INSERT INTO membership_clients (user_id, project_id, client_id)
SELECT $1::bigint, $2::bigint, unnest($3::bigint[])
`

type AddMembershipClientsParams struct {
	UserID    int64
	ProjectID int64
	ClientIds []int64
}

func (q *Queries) AddMembershipClients(ctx context.Context, arg AddMembershipClientsParams) error {
	_, err := q.db.Exec(ctx, addMembershipClients, arg.UserID, arg.ProjectID, arg.ClientIds)
	return err
}

const clearMembershipClients = `-- name: ClearMembershipClients :exec
DELETE FROM membership_clients WHERE user_id = $1 AND project_id = $2
`

type ClearMembershipClientsParams struct {
	UserID    int64
	ProjectID int64
}

func (q *Queries) ClearMembershipClients(ctx context.Context, arg ClearMembershipClientsParams) error {
	_, err := q.db.Exec(ctx, clearMembershipClients, arg.UserID, arg.ProjectID)
	return err
}

const deleteMembershipsExcept = `-- name: DeleteMembershipsExcept :exec
DELETE FROM memberships
WHERE project_id = $1 AND NOT (user_id = ANY ($2::bigint[]))
`

type DeleteMembershipsExceptParams struct {
	ProjectID int64
	UserIds   []int64
}

func (q *Queries) DeleteMembershipsExcept(ctx context.Context, arg DeleteMembershipsExceptParams) error {
	_, err := q.db.Exec(ctx, deleteMembershipsExcept, arg.ProjectID, arg.UserIds)
	return err
}

const getMembership = `-- name: GetMembership :one
SELECT m.role, m.all_clients,
       coalesce(array_agg(mc.client_id ORDER BY mc.client_id) FILTER (WHERE mc.client_id IS NOT NULL), '{}')::bigint[] AS client_ids
FROM memberships m
LEFT JOIN membership_clients mc ON mc.user_id = m.user_id AND mc.project_id = m.project_id
WHERE m.user_id = $1 AND m.project_id = $2
GROUP BY m.role, m.all_clients
`

type GetMembershipParams struct {
	UserID    int64
	ProjectID int64
}

type GetMembershipRow struct {
	Role       string
	AllClients bool
	ClientIds  []int64
}

func (q *Queries) GetMembership(ctx context.Context, arg GetMembershipParams) (GetMembershipRow, error) {
	row := q.db.QueryRow(ctx, getMembership, arg.UserID, arg.ProjectID)
	var i GetMembershipRow
	err := row.Scan(&i.Role, &i.AllClients, &i.ClientIds)
	return i, err
}

const isProjectAdminAnywhere = `-- name: IsProjectAdminAnywhere :one
SELECT EXISTS (SELECT 1 FROM memberships WHERE user_id = $1 AND role = 'admin')
`

func (q *Queries) IsProjectAdminAnywhere(ctx context.Context, userID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isProjectAdminAnywhere, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAssignees = `-- name: ListAssignees :many
SELECT u.id, u.name
FROM memberships m JOIN users u ON u.id = m.user_id
WHERE m.project_id = $1 AND m.role IN ('admin', 'member') AND u.disabled_at IS NULL
  AND ($2::bigint IS NULL OR m.role = 'admin' OR m.all_clients OR EXISTS (
        SELECT 1 FROM membership_clients mc
        WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = $2::bigint))
ORDER BY lower(u.name), u.id
`

type ListAssigneesParams struct {
	ProjectID int64
	ClientID  *int64
}

type ListAssigneesRow struct {
	ID   int64
	Name string
}

// Who can own tickets: active members who are not viewers (FSD §8.1). With a
// client, only those who may see its tickets (MSL-22): project admins, members
// of all clients, and members scoped to it.
func (q *Queries) ListAssignees(ctx context.Context, arg ListAssigneesParams) ([]ListAssigneesRow, error) {
	rows, err := q.db.Query(ctx, listAssignees, arg.ProjectID, arg.ClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssigneesRow
	for rows.Next() {
		var i ListAssigneesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemberCandidates = `-- name: ListMemberCandidates :many
SELECT u.id, u.name, u.email FROM users u
WHERE u.disabled_at IS NULL
  AND ($1::boolean OR EXISTS (
    SELECT 1 FROM memberships mine
    JOIN memberships theirs ON theirs.project_id = mine.project_id
    WHERE mine.user_id = $2 AND theirs.user_id = u.id))
ORDER BY lower(u.name), u.id
`

type ListMemberCandidatesParams struct {
	Everyone bool
	UserID   int64
}

type ListMemberCandidatesRow struct {
	ID    int64
	Name  string
	Email string
}

// MSL-21: who a project admin can pick as a member: the active users who
// already share a project with them. A system admin picks from everyone.
func (q *Queries) ListMemberCandidates(ctx context.Context, arg ListMemberCandidatesParams) ([]ListMemberCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listMemberCandidates, arg.Everyone, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemberCandidatesRow
	for rows.Next() {
		var i ListMemberCandidatesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Email); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT u.id AS user_id, u.name, u.email, m.role, m.all_clients,
       coalesce(array_agg(mc.client_id ORDER BY mc.client_id) FILTER (WHERE mc.client_id IS NOT NULL), '{}')::bigint[] AS client_ids
FROM memberships m
JOIN users u ON u.id = m.user_id
LEFT JOIN membership_clients mc ON mc.user_id = m.user_id AND mc.project_id = m.project_id
WHERE m.project_id = $1
GROUP BY u.id, u.name, u.email, m.role, m.all_clients
ORDER BY lower(u.name), u.id
`

type ListProjectMembersRow struct {
	UserID     int64
	Name       string
	Email      string
	Role       string
	AllClients bool
	ClientIds  []int64
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID int64) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMembersRow
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Name,
			&i.Email,
			&i.Role,
			&i.AllClients,
			&i.ClientIds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMembership = `-- name: UpsertMembership :exec
INSERT INTO memberships (user_id, project_id, role, all_clients)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, project_id) DO UPDATE SET role = excluded.role, all_clients = excluded.all_clients
`

type UpsertMembershipParams struct {
	UserID     int64
	ProjectID  int64
	Role       string
	AllClients bool
}

func (q *Queries) UpsertMembership(ctx context.Context, arg UpsertMembershipParams) error {
	_, err := q.db.Exec(ctx, upsertMembership,
		arg.UserID,
		arg.ProjectID,
		arg.Role,
		arg.AllClients,
	)
	return err
}
