// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"
	"time"
)

type AuditEvent struct {
	ID         int64
	OccurredAt time.Time
	ActorID    *int64
	Via        string
	Entity     string
	EntityID   int64
	ProjectID  *int64
	Action     string
	Changes    []byte
	RequestID  *string
	Ip         *netip.Addr
}

type Session struct {
	TokenHash  []byte
	UserID     int64
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
	Ip         *netip.Addr
	UserAgent  *string
}

type SetupToken struct {
	TokenHash []byte
	UserID    int64
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type User struct {
	ID           int64
	Email        string
	Name         string
	PasswordHash *string
	IsAdmin      bool
	Locale       string
	Timezone     string
	FailedLogins int32
	FailedSince  *time.Time
	LockedUntil  *time.Time
	DisabledAt   *time.Time
	LastLoginAt  *time.Time
	CreatedAt    time.Time
}
