// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"
	"time"

	pgvector "github.com/pgvector/pgvector-go"
)

type ApiToken struct {
	ID         int64
	UserID     int64
	Name       string
	TokenHash  []byte
	ReadOnly   bool
	ExpiresAt  *time.Time
	LastUsedAt *time.Time
	RevokedAt  *time.Time
	CreatedAt  time.Time
}

type AskFeedback struct {
	QueryID   int64
	UserID    int64
	Rating    int16
	Reasons   []string
	Comment   *string
	CreatedAt time.Time
}

type AskQuery struct {
	ID           int64
	ThreadID     *int64
	UserID       int64
	Question     string
	Lang         string
	Scope        []byte
	Evidence     []byte
	LlmCalled    bool
	Status       string
	Answer       []byte
	Dropped      []byte
	Model        *string
	LatencyMs    *int32
	FirstClaimMs *int32
	CreatedAt    time.Time
}

type AskThread struct {
	ID        int64
	UserID    int64
	Title     string
	CreatedAt time.Time
	HiddenAt  *time.Time
}

type Attachment struct {
	ID          int64
	TicketID    int64
	UploaderID  int64
	Filename    string
	ContentType string
	SizeBytes   int64
	Sha256      []byte
	CreatedAt   time.Time
	DeletedAt   *time.Time
}

type AuditEvent struct {
	ID         int64
	OccurredAt time.Time
	ActorID    *int64
	Via        string
	Entity     string
	EntityID   int64
	ProjectID  *int64
	Action     string
	Changes    []byte
	RequestID  *string
	Ip         *netip.Addr
}

type Chunk struct {
	ID          int64
	SourceType  string
	SourceID    int64
	Seq         int32
	TicketID    *int64
	ProjectID   int64
	ClientID    *int64
	NodeIds     []int64
	UserIds     []int64
	ContactIds  []int64
	Internal    bool
	OccurredAt  time.Time
	Content     string
	ContentHash []byte
	Tsv         interface{}
	Embedding   *pgvector.HalfVector
	EmbedModel  *string
	IndexedAt   time.Time
	NoteID      *int64
}

type Client struct {
	ID         int64
	Name       string
	Code       *string
	Aliases    []string
	ArchivedAt *time.Time
}

type Comment struct {
	ID           int64
	TicketID     int64
	AuthorID     *int64
	Internal     bool
	Body         string
	CreatedAt    time.Time
	EditedAt     *time.Time
	DeletedAt    *time.Time
	AuthorLabel  *string
	ExternalHash []byte
}

type Commit struct {
	ID          int64
	RepoID      int64
	Sha         string
	Message     string
	AuthorName  *string
	AuthorEmail *string
	CommittedAt *time.Time
	Url         *string
}

type Contact struct {
	ID       int64
	ClientID *int64
	Name     string
	Title    *string
	Email    *string
	Phone    *string
}

type DecisionNote struct {
	ID         int64
	ProjectID  int64
	Number     int64
	Key        string
	Title      string
	DecidedOn  time.Time
	ClientID   *int64
	Attendees  string
	Body       string
	CreatedBy  int64
	CreatedAt  time.Time
	UpdatedAt  time.Time
	ArchivedAt *time.Time
}

type DecisionNoteNode struct {
	NoteID int64
	NodeID int64
}

type DecisionNoteTicket struct {
	NoteID   int64
	TicketID int64
}

type DecisionRecord struct {
	TicketID     int64
	WhatChanged  string
	Why          string
	Alternatives string
	Outcome      string
	State        string
	ConfirmedBy  *int64
	ConfirmedAt  *time.Time
	SupersededBy *int64
}

type GitRepo struct {
	ID        int64
	ProjectID int64
	Provider  string
	Name      string
	WebUrl    string
	SecretEnc []byte
	CreatedAt time.Time
}

type IdempotencyKey struct {
	UserID    int64
	Key       string
	TicketID  int64
	CreatedAt time.Time
}

type ImportRun struct {
	ID         int64
	Kind       string
	ProjectID  int64
	FileName   string
	FilePath   string
	Mapping    []byte
	Status     string
	Stats      []byte
	Errors     []byte
	CreatedBy  int64
	CreatedAt  time.Time
	FinishedAt *time.Time
}

type Membership struct {
	UserID     int64
	ProjectID  int64
	Role       string
	AllClients bool
}

type MembershipClient struct {
	UserID    int64
	ProjectID int64
	ClientID  int64
}

type MergeRequest struct {
	ID       int64
	RepoID   int64
	Number   int32
	Title    string
	State    string
	MergedAt *time.Time
	Url      *string
}

type Node struct {
	ID             int64
	ProjectID      int64
	ParentID       *int64
	Type           string
	Name           string
	Code           *string
	Aliases        []string
	Description    string
	ClientSpecific bool
	Source         string
	Position       int32
	ArchivedAt     *time.Time
}

type NodeClient struct {
	NodeID    int64
	ProjectID int64
	ClientID  int64
}

type Notification struct {
	ID        int64
	UserID    int64
	Type      string
	TicketID  *int64
	ActorID   *int64
	Payload   []byte
	CreatedAt time.Time
	ReadAt    *time.Time
}

type Project struct {
	ID          int64
	Key         string
	Name        string
	Description string
	CreatedAt   time.Time
	TicketSeq   int64
	NoteSeq     int64
}

type ProjectClient struct {
	ProjectID int64
	ClientID  int64
}

type Session struct {
	TokenHash  []byte
	UserID     int64
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
	Ip         *netip.Addr
	UserAgent  *string
}

type Setting struct {
	Key       string
	Value     []byte
	UpdatedBy *int64
	UpdatedAt time.Time
}

type SetupToken struct {
	TokenHash []byte
	UserID    int64
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type Status struct {
	ID        int64
	ProjectID int64
	Name      string
	Category  string
	Position  int32
	Color     string
	IsDefault bool
}

type Ticket struct {
	ID                 int64
	ProjectID          int64
	Number             int64
	Key                string
	Type               string
	Title              string
	Description        string
	Reason             string
	StatusID           int64
	ClientID           *int64
	RequesterContactID *int64
	RequesterUserID    *int64
	ReporterID         int64
	AssigneeID         *int64
	Priority           string
	DueDate            *time.Time
	Version            int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
	ClosedAt           *time.Time
	Source             string
	ExternalRef        *string
	ExternalMeta       []byte
}

type TicketCommit struct {
	TicketID int64
	CommitID int64
}

type TicketLink struct {
	ID        int64
	FromID    int64
	ToID      int64
	Type      string
	CreatedBy int64
	CreatedAt time.Time
}

type TicketMergeRequest struct {
	TicketID int64
	MrID     int64
}

type TicketNode struct {
	TicketID int64
	NodeID   int64
}

type User struct {
	ID           int64
	Email        string
	Name         string
	PasswordHash *string
	IsAdmin      bool
	Locale       string
	Timezone     string
	FailedLogins int32
	FailedSince  *time.Time
	LockedUntil  *time.Time
	DisabledAt   *time.Time
	LastLoginAt  *time.Time
	CreatedAt    time.Time
	NotifyPrefs  []byte
}

type WebhookDelivery struct {
	ID         int64
	RepoID     int64
	Event      string
	Payload    []byte
	ReceivedAt time.Time
}
