// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"
	"time"
)

type Attachment struct {
	ID          int64
	TicketID    int64
	UploaderID  int64
	Filename    string
	ContentType string
	SizeBytes   int64
	Sha256      []byte
	CreatedAt   time.Time
	DeletedAt   *time.Time
}

type AuditEvent struct {
	ID         int64
	OccurredAt time.Time
	ActorID    *int64
	Via        string
	Entity     string
	EntityID   int64
	ProjectID  *int64
	Action     string
	Changes    []byte
	RequestID  *string
	Ip         *netip.Addr
}

type Client struct {
	ID         int64
	Name       string
	Code       *string
	Aliases    []string
	ArchivedAt *time.Time
}

type Comment struct {
	ID        int64
	TicketID  int64
	AuthorID  int64
	Internal  bool
	Body      string
	CreatedAt time.Time
	EditedAt  *time.Time
	DeletedAt *time.Time
}

type Contact struct {
	ID       int64
	ClientID *int64
	Name     string
	Title    *string
	Email    *string
	Phone    *string
}

type DecisionRecord struct {
	TicketID     int64
	WhatChanged  string
	Why          string
	Alternatives string
	Outcome      string
	State        string
	ConfirmedBy  *int64
	ConfirmedAt  *time.Time
}

type Membership struct {
	UserID     int64
	ProjectID  int64
	Role       string
	AllClients bool
}

type MembershipClient struct {
	UserID    int64
	ProjectID int64
	ClientID  int64
}

type Node struct {
	ID             int64
	ProjectID      int64
	ParentID       *int64
	Type           string
	Name           string
	Code           *string
	Aliases        []string
	Description    string
	ClientSpecific bool
	Source         string
	Position       int32
	ArchivedAt     *time.Time
}

type NodeClient struct {
	NodeID    int64
	ProjectID int64
	ClientID  int64
}

type Project struct {
	ID          int64
	Key         string
	Name        string
	Description string
	CreatedAt   time.Time
	TicketSeq   int64
}

type ProjectClient struct {
	ProjectID int64
	ClientID  int64
}

type Session struct {
	TokenHash  []byte
	UserID     int64
	CreatedAt  time.Time
	LastSeenAt time.Time
	ExpiresAt  time.Time
	Ip         *netip.Addr
	UserAgent  *string
}

type SetupToken struct {
	TokenHash []byte
	UserID    int64
	ExpiresAt time.Time
	UsedAt    *time.Time
}

type Status struct {
	ID        int64
	ProjectID int64
	Name      string
	Category  string
	Position  int32
	Color     string
	IsDefault bool
}

type Ticket struct {
	ID                 int64
	ProjectID          int64
	Number             int64
	Key                string
	Type               string
	Title              string
	Description        string
	Reason             string
	StatusID           int64
	ClientID           *int64
	RequesterContactID *int64
	RequesterUserID    *int64
	ReporterID         int64
	AssigneeID         *int64
	Priority           string
	DueDate            *time.Time
	Version            int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
	ClosedAt           *time.Time
}

type TicketNode struct {
	TicketID int64
	NodeID   int64
}

type User struct {
	ID           int64
	Email        string
	Name         string
	PasswordHash *string
	IsAdmin      bool
	Locale       string
	Timezone     string
	FailedLogins int32
	FailedSince  *time.Time
	LockedUntil  *time.Time
	DisabledAt   *time.Time
	LastLoginAt  *time.Time
	CreatedAt    time.Time
}
