// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notes.sql

package db

import (
	"context"
	"time"
)

const archiveNote = `-- name: ArchiveNote :exec
UPDATE decision_notes SET archived_at = CASE WHEN $1::boolean THEN coalesce(archived_at, now()) END, updated_at = now()
WHERE id = $2
`

type ArchiveNoteParams struct {
	Archived bool
	ID       int64
}

func (q *Queries) ArchiveNote(ctx context.Context, arg ArchiveNoteParams) error {
	_, err := q.db.Exec(ctx, archiveNote, arg.Archived, arg.ID)
	return err
}

const createNote = `-- name: CreateNote :one
INSERT INTO decision_notes (project_id, number, key, title, decided_on, client_id, attendees, body, created_by)
VALUES ($1, $2, $3, $4, $5,
        $6, $7, $8, $9)
RETURNING id, project_id, number, key, title, decided_on, client_id, attendees, body, created_by, created_at, updated_at, archived_at
`

type CreateNoteParams struct {
	ProjectID int64
	Number    int64
	Key       string
	Title     string
	DecidedOn time.Time
	ClientID  *int64
	Attendees string
	Body      string
	CreatedBy int64
}

func (q *Queries) CreateNote(ctx context.Context, arg CreateNoteParams) (DecisionNote, error) {
	row := q.db.QueryRow(ctx, createNote,
		arg.ProjectID,
		arg.Number,
		arg.Key,
		arg.Title,
		arg.DecidedOn,
		arg.ClientID,
		arg.Attendees,
		arg.Body,
		arg.CreatedBy,
	)
	var i DecisionNote
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Key,
		&i.Title,
		&i.DecidedOn,
		&i.ClientID,
		&i.Attendees,
		&i.Body,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}

const deleteStaleNoteChunks = `-- name: DeleteStaleNoteChunks :exec
DELETE FROM chunks c
WHERE c.note_id = $1::bigint
  AND c.source_type || ':' || c.source_id || ':' || c.seq <> ALL ($2::text[])
`

type DeleteStaleNoteChunksParams struct {
	NoteID int64
	Keep   []string
}

func (q *Queries) DeleteStaleNoteChunks(ctx context.Context, arg DeleteStaleNoteChunksParams) error {
	_, err := q.db.Exec(ctx, deleteStaleNoteChunks, arg.NoteID, arg.Keep)
	return err
}

const getNoteByID = `-- name: GetNoteByID :one
SELECT n.id, n.project_id, n.number, n.key, n.title, n.decided_on, n.client_id, n.attendees, n.body, n.created_by, n.created_at, n.updated_at, n.archived_at, p.key AS project_key, c.name AS client_name, u.name AS author_name
FROM decision_notes n
JOIN projects p ON p.id = n.project_id
JOIN users u ON u.id = n.created_by
LEFT JOIN clients c ON c.id = n.client_id
WHERE n.id = $1
`

type GetNoteByIDRow struct {
	DecisionNote DecisionNote
	ProjectKey   string
	ClientName   *string
	AuthorName   string
}

func (q *Queries) GetNoteByID(ctx context.Context, id int64) (GetNoteByIDRow, error) {
	row := q.db.QueryRow(ctx, getNoteByID, id)
	var i GetNoteByIDRow
	err := row.Scan(
		&i.DecisionNote.ID,
		&i.DecisionNote.ProjectID,
		&i.DecisionNote.Number,
		&i.DecisionNote.Key,
		&i.DecisionNote.Title,
		&i.DecisionNote.DecidedOn,
		&i.DecisionNote.ClientID,
		&i.DecisionNote.Attendees,
		&i.DecisionNote.Body,
		&i.DecisionNote.CreatedBy,
		&i.DecisionNote.CreatedAt,
		&i.DecisionNote.UpdatedAt,
		&i.DecisionNote.ArchivedAt,
		&i.ProjectKey,
		&i.ClientName,
		&i.AuthorName,
	)
	return i, err
}

const getNoteByKey = `-- name: GetNoteByKey :one
SELECT n.id, n.project_id, n.number, n.key, n.title, n.decided_on, n.client_id, n.attendees, n.body, n.created_by, n.created_at, n.updated_at, n.archived_at, p.key AS project_key, c.name AS client_name, u.name AS author_name
FROM decision_notes n
JOIN projects p ON p.id = n.project_id
JOIN users u ON u.id = n.created_by
LEFT JOIN clients c ON c.id = n.client_id
WHERE n.key = $1
`

type GetNoteByKeyRow struct {
	DecisionNote DecisionNote
	ProjectKey   string
	ClientName   *string
	AuthorName   string
}

func (q *Queries) GetNoteByKey(ctx context.Context, key string) (GetNoteByKeyRow, error) {
	row := q.db.QueryRow(ctx, getNoteByKey, key)
	var i GetNoteByKeyRow
	err := row.Scan(
		&i.DecisionNote.ID,
		&i.DecisionNote.ProjectID,
		&i.DecisionNote.Number,
		&i.DecisionNote.Key,
		&i.DecisionNote.Title,
		&i.DecisionNote.DecidedOn,
		&i.DecisionNote.ClientID,
		&i.DecisionNote.Attendees,
		&i.DecisionNote.Body,
		&i.DecisionNote.CreatedBy,
		&i.DecisionNote.CreatedAt,
		&i.DecisionNote.UpdatedAt,
		&i.DecisionNote.ArchivedAt,
		&i.ProjectKey,
		&i.ClientName,
		&i.AuthorName,
	)
	return i, err
}

const isProjectClient = `-- name: IsProjectClient :one
SELECT EXISTS (SELECT 1 FROM project_clients WHERE project_id = $1 AND client_id = $2)::boolean
`

type IsProjectClientParams struct {
	ProjectID int64
	ClientID  int64
}

func (q *Queries) IsProjectClient(ctx context.Context, arg IsProjectClientParams) (bool, error) {
	row := q.db.QueryRow(ctx, isProjectClient, arg.ProjectID, arg.ClientID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const linkNoteTicket = `-- name: LinkNoteTicket :exec
INSERT INTO decision_note_tickets (note_id, ticket_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type LinkNoteTicketParams struct {
	NoteID   int64
	TicketID int64
}

// A ticket filed from a note's action item joins the note's tickets (MSL-11).
func (q *Queries) LinkNoteTicket(ctx context.Context, arg LinkNoteTicketParams) error {
	_, err := q.db.Exec(ctx, linkNoteTicket, arg.NoteID, arg.TicketID)
	return err
}

const listAllNoteIDs = `-- name: ListAllNoteIDs :many
SELECT id FROM decision_notes ORDER BY id DESC
`

func (q *Queries) ListAllNoteIDs(ctx context.Context) ([]int64, error) {
	rows, err := q.db.Query(ctx, listAllNoteIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodeNotes = `-- name: ListNodeNotes :many
SELECT n.id, n.key, n.title, n.decided_on, n.client_id, c.name AS client_name, n.attendees, n.body, u.name AS author_name
FROM decision_notes n
JOIN users u ON u.id = n.created_by
LEFT JOIN clients c ON c.id = n.client_id
WHERE n.project_id = $1 AND n.archived_at IS NULL
  AND EXISTS (SELECT 1 FROM decision_note_nodes dn WHERE dn.note_id = n.id AND dn.node_id = ANY ($2::bigint[]))
  AND ($3::boolean OR n.client_id IS NULL OR n.client_id = ANY ($4::bigint[]))
  AND ($5::bigint IS NULL OR n.client_id = $5::bigint)
  AND (NOT $6::boolean OR n.client_id IS NULL)
  AND ($7::date IS NULL OR n.decided_on >= $7::date)
  AND ($8::date IS NULL OR n.decided_on <= $8::date)
ORDER BY n.decided_on DESC, n.id DESC
LIMIT 500
`

type ListNodeNotesParams struct {
	ProjectID  int64
	NodeIds    []int64
	AllClients bool
	ClientIds  []int64
	ClientID   *int64
	CoreOnly   bool
	FromDate   *time.Time
	ToDate     *time.Time
}

type ListNodeNotesRow struct {
	ID         int64
	Key        string
	Title      string
	DecidedOn  time.Time
	ClientID   *int64
	ClientName *string
	Attendees  string
	Body       string
	AuthorName string
}

// The visible notes on these nodes for a node page, newest decision first
// (§9.4, AC-DC-8); from_date and to_date filter on the decision date.
func (q *Queries) ListNodeNotes(ctx context.Context, arg ListNodeNotesParams) ([]ListNodeNotesRow, error) {
	rows, err := q.db.Query(ctx, listNodeNotes,
		arg.ProjectID,
		arg.NodeIds,
		arg.AllClients,
		arg.ClientIds,
		arg.ClientID,
		arg.CoreOnly,
		arg.FromDate,
		arg.ToDate,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNodeNotesRow
	for rows.Next() {
		var i ListNodeNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Title,
			&i.DecidedOn,
			&i.ClientID,
			&i.ClientName,
			&i.Attendees,
			&i.Body,
			&i.AuthorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNoteIDsUnderNode = `-- name: ListNoteIDsUnderNode :many
WITH RECURSIVE sub AS (
  SELECT n.id FROM nodes n WHERE n.id = $1
  UNION ALL
  SELECT n.id FROM nodes n JOIN sub ON n.parent_id = sub.id
)
SELECT DISTINCT dn.note_id FROM decision_note_nodes dn JOIN sub ON sub.id = dn.node_id ORDER BY 1
`

// Notes on a node or its sub-nodes, whose chunks name the node's path.
func (q *Queries) ListNoteIDsUnderNode(ctx context.Context, id int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listNoteIDsUnderNode, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var note_id int64
		if err := rows.Scan(&note_id); err != nil {
			return nil, err
		}
		items = append(items, note_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNoteNodePaths = `-- name: ListNoteNodePaths :many
WITH RECURSIVE up AS (
  SELECT dn.node_id AS id, n.parent_id, ARRAY[n.name]::text[] AS path
  FROM decision_note_nodes dn
  JOIN nodes n ON n.id = dn.node_id
  WHERE dn.note_id = $1
  UNION ALL
  SELECT up.id, p.parent_id, p.name || up.path
  FROM up
  JOIN nodes p ON p.id = up.parent_id
)
SELECT id, path::text[] AS path FROM up WHERE parent_id IS NULL ORDER BY id
`

type ListNoteNodePathsRow struct {
	ID   int64
	Path []string
}

// The note's menus, each with the names from the top of the tree down.
func (q *Queries) ListNoteNodePaths(ctx context.Context, noteID int64) ([]ListNoteNodePathsRow, error) {
	rows, err := q.db.Query(ctx, listNoteNodePaths, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNoteNodePathsRow
	for rows.Next() {
		var i ListNoteNodePathsRow
		if err := rows.Scan(&i.ID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNoteNodes = `-- name: ListNoteNodes :many
SELECT n.id, n.name, (n.archived_at IS NOT NULL)::boolean AS archived
FROM decision_note_nodes dn JOIN nodes n ON n.id = dn.node_id
WHERE dn.note_id = $1 ORDER BY lower(n.name), n.id
`

type ListNoteNodesRow struct {
	ID       int64
	Name     string
	Archived bool
}

func (q *Queries) ListNoteNodes(ctx context.Context, noteID int64) ([]ListNoteNodesRow, error) {
	rows, err := q.db.Query(ctx, listNoteNodes, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNoteNodesRow
	for rows.Next() {
		var i ListNoteNodesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Archived); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNoteTickets = `-- name: ListNoteTickets :many
SELECT t.id, t.key, t.title, t.project_id, t.client_id
FROM decision_note_tickets dt JOIN tickets t ON t.id = dt.ticket_id
WHERE dt.note_id = $1 ORDER BY t.id
`

type ListNoteTicketsRow struct {
	ID        int64
	Key       string
	Title     string
	ProjectID int64
	ClientID  *int64
}

func (q *Queries) ListNoteTickets(ctx context.Context, noteID int64) ([]ListNoteTicketsRow, error) {
	rows, err := q.db.Query(ctx, listNoteTickets, noteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNoteTicketsRow
	for rows.Next() {
		var i ListNoteTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Title,
			&i.ProjectID,
			&i.ClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingNoteChunks = `-- name: ListPendingNoteChunks :many
SELECT id, content, content_hash FROM chunks
WHERE note_id = $1::bigint AND (embedding IS NULL OR embed_model IS DISTINCT FROM $2::text)
ORDER BY id
`

type ListPendingNoteChunksParams struct {
	NoteID int64
	Model  string
}

type ListPendingNoteChunksRow struct {
	ID          int64
	Content     string
	ContentHash []byte
}

func (q *Queries) ListPendingNoteChunks(ctx context.Context, arg ListPendingNoteChunksParams) ([]ListPendingNoteChunksRow, error) {
	rows, err := q.db.Query(ctx, listPendingNoteChunks, arg.NoteID, arg.Model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingNoteChunksRow
	for rows.Next() {
		var i ListPendingNoteChunksRow
		if err := rows.Scan(&i.ID, &i.Content, &i.ContentHash); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectNotes = `-- name: ListProjectNotes :many
SELECT n.id, n.key, n.title, n.decided_on, n.client_id, c.name AS client_name, n.archived_at
FROM decision_notes n
LEFT JOIN clients c ON c.id = n.client_id
WHERE n.project_id = $1
  AND ($2::boolean OR n.archived_at IS NULL)
  AND ($3::boolean OR n.client_id IS NULL OR n.client_id = ANY ($4::bigint[]))
ORDER BY n.decided_on DESC, n.id DESC
LIMIT 500
`

type ListProjectNotesParams struct {
	ProjectID  int64
	Archived   bool
	AllClients bool
	ClientIds  []int64
}

type ListProjectNotesRow struct {
	ID         int64
	Key        string
	Title      string
	DecidedOn  time.Time
	ClientID   *int64
	ClientName *string
	ArchivedAt *time.Time
}

// A project's notes the scope may see, newest decision first (R-AC-2, R-AC-3).
func (q *Queries) ListProjectNotes(ctx context.Context, arg ListProjectNotesParams) ([]ListProjectNotesRow, error) {
	rows, err := q.db.Query(ctx, listProjectNotes,
		arg.ProjectID,
		arg.Archived,
		arg.AllClients,
		arg.ClientIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectNotesRow
	for rows.Next() {
		var i ListProjectNotesRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Title,
			&i.DecidedOn,
			&i.ClientID,
			&i.ClientName,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockNoteIndex = `-- name: LockNoteIndex :exec
SELECT pg_advisory_xact_lock(hashtextextended('index_note:' || $1::bigint::text, 0))
`

func (q *Queries) LockNoteIndex(ctx context.Context, noteID int64) error {
	_, err := q.db.Exec(ctx, lockNoteIndex, noteID)
	return err
}

const nextNoteNumber = `-- name: NextNoteNumber :one

UPDATE projects SET note_seq = note_seq + 1 WHERE id = $1 RETURNING note_seq
`

// Decision notes (FSD §9.4): decisions made outside tickets.
func (q *Queries) NextNoteNumber(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, nextNoteNumber, id)
	var note_seq int64
	err := row.Scan(&note_seq)
	return note_seq, err
}

const searchNotes = `-- name: SearchNotes :many
SELECT n.key, n.title, p.key AS project_key, n.decided_on
FROM decision_notes n
JOIN projects p ON p.id = n.project_id
WHERE n.archived_at IS NULL
  AND ($1::boolean OR EXISTS (
        SELECT 1 FROM memberships m
        WHERE m.user_id = $2::bigint AND m.project_id = n.project_id
          AND (m.all_clients OR n.client_id IS NULL OR EXISTS (
                SELECT 1 FROM membership_clients mc
                WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = n.client_id))))
  AND (n.key = upper($3::text)
       OR n.title ILIKE '%' || $3::text || '%'
       OR to_tsvector('simple', n.title || ' ' || n.attendees || ' ' || n.body) @@ websearch_to_tsquery('simple', $3::text))
ORDER BY n.key = upper($3::text) DESC, n.decided_on DESC
LIMIT 20
`

type SearchNotesParams struct {
	IsAdmin bool
	UserID  int64
	Q       string
}

type SearchNotesRow struct {
	Key        string
	Title      string
	ProjectKey string
	DecidedOn  time.Time
}

// Notes the user may see (R-AC-2, R-AC-3): a key, words in the title or body,
// or part of the title (FSD §6.1). An exact key comes first.
func (q *Queries) SearchNotes(ctx context.Context, arg SearchNotesParams) ([]SearchNotesRow, error) {
	rows, err := q.db.Query(ctx, searchNotes, arg.IsAdmin, arg.UserID, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchNotesRow
	for rows.Next() {
		var i SearchNotesRow
		if err := rows.Scan(
			&i.Key,
			&i.Title,
			&i.ProjectKey,
			&i.DecidedOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setNoteNodes = `-- name: SetNoteNodes :exec
WITH gone AS (
  DELETE FROM decision_note_nodes WHERE note_id = $1 AND node_id <> ALL ($2::bigint[])
)
INSERT INTO decision_note_nodes (note_id, node_id)
SELECT $1, unnest($2::bigint[])
ON CONFLICT DO NOTHING
`

type SetNoteNodesParams struct {
	NoteID  int64
	NodeIds []int64
}

// Replaces the note's menus.
func (q *Queries) SetNoteNodes(ctx context.Context, arg SetNoteNodesParams) error {
	_, err := q.db.Exec(ctx, setNoteNodes, arg.NoteID, arg.NodeIds)
	return err
}

const setNoteTickets = `-- name: SetNoteTickets :exec
WITH gone AS (
  DELETE FROM decision_note_tickets WHERE note_id = $1 AND ticket_id <> ALL ($2::bigint[])
)
INSERT INTO decision_note_tickets (note_id, ticket_id)
SELECT $1, unnest($2::bigint[])
ON CONFLICT DO NOTHING
`

type SetNoteTicketsParams struct {
	NoteID    int64
	TicketIds []int64
}

func (q *Queries) SetNoteTickets(ctx context.Context, arg SetNoteTicketsParams) error {
	_, err := q.db.Exec(ctx, setNoteTickets, arg.NoteID, arg.TicketIds)
	return err
}

const updateNote = `-- name: UpdateNote :one
UPDATE decision_notes SET title = $1, decided_on = $2, client_id = $3,
  attendees = $4, body = $5, updated_at = now()
WHERE id = $6
RETURNING id, project_id, number, key, title, decided_on, client_id, attendees, body, created_by, created_at, updated_at, archived_at
`

type UpdateNoteParams struct {
	Title     string
	DecidedOn time.Time
	ClientID  *int64
	Attendees string
	Body      string
	ID        int64
}

func (q *Queries) UpdateNote(ctx context.Context, arg UpdateNoteParams) (DecisionNote, error) {
	row := q.db.QueryRow(ctx, updateNote,
		arg.Title,
		arg.DecidedOn,
		arg.ClientID,
		arg.Attendees,
		arg.Body,
		arg.ID,
	)
	var i DecisionNote
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Key,
		&i.Title,
		&i.DecidedOn,
		&i.ClientID,
		&i.Attendees,
		&i.Body,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ArchivedAt,
	)
	return i, err
}
