// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"
	"time"
)

const countUnread = `-- name: CountUnread :one
SELECT count(*) FROM notifications WHERE user_id = $1 AND read_at IS NULL
`

func (q *Queries) CountUnread(ctx context.Context, userID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countUnread, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listCommenters = `-- name: ListCommenters :many
SELECT DISTINCT author_id::bigint FROM comments WHERE ticket_id = $1 AND author_id IS NOT NULL AND deleted_at IS NULL
`

func (q *Queries) ListCommenters(ctx context.Context, ticketID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listCommenters, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var author_id int64
		if err := rows.Scan(&author_id); err != nil {
			return nil, err
		}
		items = append(items, author_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMentionable = `-- name: ListMentionable :many
SELECT u.id, u.name, lower(split_part(u.email, '@', 1))::text AS handle
FROM users u
JOIN tickets t ON t.id = $1
JOIN memberships m ON m.user_id = u.id AND m.project_id = t.project_id
WHERE u.disabled_at IS NULL
  AND (m.all_clients OR t.client_id IS NULL OR EXISTS (
        SELECT 1 FROM membership_clients mc
        WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = t.client_id))
ORDER BY lower(u.name), u.id
`

type ListMentionableRow struct {
	ID     int64
	Name   string
	Handle string
}

// Project members who can see the ticket, with the handle an @mention uses:
// the email's part before the @ (§8.7).
func (q *Queries) ListMentionable(ctx context.Context, ticketID int64) ([]ListMentionableRow, error) {
	rows, err := q.db.Query(ctx, listMentionable, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMentionableRow
	for rows.Next() {
		var i ListMentionableRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Handle); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNotifications = `-- name: ListNotifications :many
SELECT n.id, n.type, n.payload, n.created_at, n.read_at, t.key AS ticket_key, t.title AS ticket_title,
       n.actor_id, a.name AS actor_name
FROM notifications n
LEFT JOIN tickets t ON t.id = n.ticket_id
LEFT JOIN users a ON a.id = n.actor_id
WHERE n.user_id = $1
  AND ($2::bigint IS NULL OR n.id = $2::bigint)
  AND (t.id IS NULL OR $3::boolean OR EXISTS (
        SELECT 1 FROM memberships m
        WHERE m.user_id = n.user_id AND m.project_id = t.project_id
          AND (m.all_clients OR t.client_id IS NULL OR EXISTS (
                SELECT 1 FROM membership_clients mc
                WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = t.client_id))))
ORDER BY n.created_at DESC, n.id DESC
LIMIT 50
`

type ListNotificationsParams struct {
	UserID  int64
	ID      *int64
	IsAdmin bool
}

type ListNotificationsRow struct {
	ID          int64
	Type        string
	Payload     []byte
	CreatedAt   time.Time
	ReadAt      *time.Time
	TicketKey   *string
	TicketTitle *string
	ActorID     *int64
	ActorName   *string
}

// The latest 50, each checked against the ticket's visibility now (§8.10).
func (q *Queries) ListNotifications(ctx context.Context, arg ListNotificationsParams) ([]ListNotificationsRow, error) {
	rows, err := q.db.Query(ctx, listNotifications, arg.UserID, arg.ID, arg.IsAdmin)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListNotificationsRow
	for rows.Next() {
		var i ListNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
			&i.ReadAt,
			&i.TicketKey,
			&i.TicketTitle,
			&i.ActorID,
			&i.ActorName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRead = `-- name: MarkRead :exec
UPDATE notifications SET read_at = now()
WHERE user_id = $1 AND read_at IS NULL AND ($2::bigint IS NULL OR id = $2::bigint)
`

type MarkReadParams struct {
	UserID int64
	ID     *int64
}

// One notification, or all of them when id is null.
func (q *Queries) MarkRead(ctx context.Context, arg MarkReadParams) error {
	_, err := q.db.Exec(ctx, markRead, arg.UserID, arg.ID)
	return err
}

const notifyJobDone = `-- name: NotifyJobDone :exec
WITH ins AS (
  INSERT INTO notifications (user_id, type, payload)
  SELECT u.id, 'job_done', $1 FROM users u
  WHERE u.id = $2 AND coalesce((u.notify_prefs ->> 'job_done')::boolean, true)
  RETURNING id, user_id
)
SELECT pg_notify('muasal_notifications', ins.user_id || ':' || ins.id) FROM ins
`

type NotifyJobDoneParams struct {
	Payload []byte
	UserID  int64
}

// An import (or a later tree draft or re-index) finished: its starter hears.
func (q *Queries) NotifyJobDone(ctx context.Context, arg NotifyJobDoneParams) error {
	_, err := q.db.Exec(ctx, notifyJobDone, arg.Payload, arg.UserID)
	return err
}

const notifyTicket = `-- name: NotifyTicket :many

WITH ins AS (
  INSERT INTO notifications (user_id, type, ticket_id, actor_id, payload)
  SELECT u.id, $1, t.id, $2, $3
  FROM users u
  JOIN tickets t ON t.id = $4
  WHERE u.id = ANY ($5::bigint[])
    AND u.id IS DISTINCT FROM $2::bigint
    AND u.disabled_at IS NULL
    AND coalesce((u.notify_prefs ->> $1::text)::boolean, true)
    AND (u.is_admin OR EXISTS (
          SELECT 1 FROM memberships m
          WHERE m.user_id = u.id AND m.project_id = t.project_id
            AND (m.all_clients OR t.client_id IS NULL OR EXISTS (
                  SELECT 1 FROM membership_clients mc
                  WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = t.client_id))))
  RETURNING id, user_id
)
SELECT ins.id, ins.user_id, pg_notify('muasal_notifications', ins.user_id || ':' || ins.id)::text AS sent FROM ins
`

type NotifyTicketParams struct {
	Type     string
	ActorID  *int64
	Payload  []byte
	TicketID int64
	UserIds  []int64
}

type NotifyTicketRow struct {
	ID     int64
	UserID int64
	Sent   string
}

// Notifications (FSD §8.10). A row goes only to a user who can see the
// ticket and has the event on; pg_notify tells the app's listener, which
// pushes it to the user's open tabs. The notification fires on commit.
func (q *Queries) NotifyTicket(ctx context.Context, arg NotifyTicketParams) ([]NotifyTicketRow, error) {
	rows, err := q.db.Query(ctx, notifyTicket,
		arg.Type,
		arg.ActorID,
		arg.Payload,
		arg.TicketID,
		arg.UserIds,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotifyTicketRow
	for rows.Next() {
		var i NotifyTicketRow
		if err := rows.Scan(&i.ID, &i.UserID, &i.Sent); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeNotifications = `-- name: PurgeNotifications :execrows
DELETE FROM notifications WHERE created_at < now() - interval '90 days'
`

func (q *Queries) PurgeNotifications(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeNotifications)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setNotifyPrefs = `-- name: SetNotifyPrefs :one
UPDATE users SET notify_prefs = $1 WHERE id = $2 RETURNING id, email, name, password_hash, is_admin, locale, timezone, failed_logins, failed_since, locked_until, disabled_at, last_login_at, created_at, notify_prefs
`

type SetNotifyPrefsParams struct {
	Prefs []byte
	ID    int64
}

func (q *Queries) SetNotifyPrefs(ctx context.Context, arg SetNotifyPrefsParams) (User, error) {
	row := q.db.QueryRow(ctx, setNotifyPrefs, arg.Prefs, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Locale,
		&i.Timezone,
		&i.FailedLogins,
		&i.FailedSince,
		&i.LockedUntil,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.NotifyPrefs,
	)
	return i, err
}
