// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package db

import (
	"context"
	"time"
)

const createOAuthClient = `-- name: CreateOAuthClient :one

INSERT INTO oauth_clients (id, name, redirect_uris)
VALUES ($1, $2, $3)
RETURNING id, name, redirect_uris, created_at
`

type CreateOAuthClientParams struct {
	ID           string
	Name         string
	RedirectUris []string
}

// MCP sign-in: OAuth clients and authorization codes (MCP spec).
func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, createOAuthClient, arg.ID, arg.Name, arg.RedirectUris)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RedirectUris,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthCode = `-- name: CreateOAuthCode :exec
INSERT INTO oauth_codes (code_hash, client_id, user_id, redirect_uri, code_challenge, read_only, expires_at)
VALUES ($1, $2, $3, $4,
        $5, $6, $7)
`

type CreateOAuthCodeParams struct {
	CodeHash      []byte
	ClientID      string
	UserID        int64
	RedirectUri   string
	CodeChallenge string
	ReadOnly      bool
	ExpiresAt     time.Time
}

func (q *Queries) CreateOAuthCode(ctx context.Context, arg CreateOAuthCodeParams) error {
	_, err := q.db.Exec(ctx, createOAuthCode,
		arg.CodeHash,
		arg.ClientID,
		arg.UserID,
		arg.RedirectUri,
		arg.CodeChallenge,
		arg.ReadOnly,
		arg.ExpiresAt,
	)
	return err
}

const getOAuthClient = `-- name: GetOAuthClient :one
SELECT id, name, redirect_uris, created_at FROM oauth_clients WHERE id = $1
`

func (q *Queries) GetOAuthClient(ctx context.Context, id string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClient, id)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RedirectUris,
		&i.CreatedAt,
	)
	return i, err
}

const purgeOAuthCodes = `-- name: PurgeOAuthCodes :execrows
DELETE FROM oauth_codes WHERE expires_at < now() - interval '1 day'
`

func (q *Queries) PurgeOAuthCodes(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOAuthCodes)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const useOAuthCode = `-- name: UseOAuthCode :one
UPDATE oauth_codes SET used_at = now()
WHERE code_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING code_hash, client_id, user_id, redirect_uri, code_challenge, read_only, expires_at, used_at
`

// Marks a live code used and returns it; a used or expired code returns no row.
func (q *Queries) UseOAuthCode(ctx context.Context, codeHash []byte) (OauthCode, error) {
	row := q.db.QueryRow(ctx, useOAuthCode, codeHash)
	var i OauthCode
	err := row.Scan(
		&i.CodeHash,
		&i.ClientID,
		&i.UserID,
		&i.RedirectUri,
		&i.CodeChallenge,
		&i.ReadOnly,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}
