// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package db

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (key, name, description)
VALUES ($1, $2, $3)
RETURNING id, key, name, description, created_at, ticket_seq, note_seq, doc_seq, archived_at
`

type CreateProjectParams struct {
	Key         string
	Name        string
	Description string
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.Key, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.TicketSeq,
		&i.NoteSeq,
		&i.DocSeq,
		&i.ArchivedAt,
	)
	return i, err
}

const getProjectByID = `-- name: GetProjectByID :one
SELECT id, key, name, description, created_at, ticket_seq, note_seq, doc_seq, archived_at FROM projects WHERE id = $1
`

func (q *Queries) GetProjectByID(ctx context.Context, id int64) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByID, id)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.TicketSeq,
		&i.NoteSeq,
		&i.DocSeq,
		&i.ArchivedAt,
	)
	return i, err
}

const getProjectByKey = `-- name: GetProjectByKey :one
SELECT id, key, name, description, created_at, ticket_seq, note_seq, doc_seq, archived_at FROM projects WHERE key = $1
`

func (q *Queries) GetProjectByKey(ctx context.Context, key string) (Project, error) {
	row := q.db.QueryRow(ctx, getProjectByKey, key)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.TicketSeq,
		&i.NoteSeq,
		&i.DocSeq,
		&i.ArchivedAt,
	)
	return i, err
}

const linkClients = `-- name: LinkClients :exec
INSERT INTO project_clients (project_id, client_id)
SELECT $1::bigint, unnest($2::bigint[])
ON CONFLICT DO NOTHING
`

type LinkClientsParams struct {
	ProjectID int64
	ClientIds []int64
}

func (q *Queries) LinkClients(ctx context.Context, arg LinkClientsParams) error {
	_, err := q.db.Exec(ctx, linkClients, arg.ProjectID, arg.ClientIds)
	return err
}

const listProjectClients = `-- name: ListProjectClients :many
SELECT c.id, c.name, c.code, c.aliases, c.archived_at FROM clients c
JOIN project_clients pc ON pc.client_id = c.id
WHERE pc.project_id = $1
  AND ($2::boolean OR c.id = ANY ($3::bigint[]))
ORDER BY lower(c.name), c.id
`

type ListProjectClientsParams struct {
	ProjectID  int64
	AllClients bool
	ClientIds  []int64
}

func (q *Queries) ListProjectClients(ctx context.Context, arg ListProjectClientsParams) ([]Client, error) {
	rows, err := q.db.Query(ctx, listProjectClients, arg.ProjectID, arg.AllClients, arg.ClientIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Client
	for rows.Next() {
		var i Client
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.Aliases,
			&i.ArchivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT p.id, p.key, p.name, p.description, p.created_at, p.ticket_seq, p.note_seq, p.doc_seq, p.archived_at, m.role
FROM projects p
LEFT JOIN memberships m ON m.project_id = p.id AND m.user_id = $1
WHERE ($2::boolean OR m.user_id IS NOT NULL)
  AND ($3::boolean OR p.archived_at IS NULL)
ORDER BY p.key
`

type ListProjectsParams struct {
	UserID   int64
	IsAdmin  bool
	Archived bool
}

type ListProjectsRow struct {
	Project Project
	Role    *string
}

// System admins see every project; everyone else sees the projects they belong to.
// Archived projects only with archived (MSL-64).
func (q *Queries) ListProjects(ctx context.Context, arg ListProjectsParams) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects, arg.UserID, arg.IsAdmin, arg.Archived)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.Project.ID,
			&i.Project.Key,
			&i.Project.Name,
			&i.Project.Description,
			&i.Project.CreatedAt,
			&i.Project.TicketSeq,
			&i.Project.NoteSeq,
			&i.Project.DocSeq,
			&i.Project.ArchivedAt,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockProject = `-- name: LockProject :exec
SELECT id FROM projects WHERE id = $1 FOR UPDATE
`

// Serializes tree moves inside one project, so two moves cannot build a cycle.
func (q *Queries) LockProject(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, lockProject, id)
	return err
}

const setProjectArchived = `-- name: SetProjectArchived :one
UPDATE projects SET archived_at = CASE WHEN $1::boolean THEN coalesce(archived_at, now()) END
WHERE id = $2 RETURNING id, key, name, description, created_at, ticket_seq, note_seq, doc_seq, archived_at
`

type SetProjectArchivedParams struct {
	Archived bool
	ID       int64
}

func (q *Queries) SetProjectArchived(ctx context.Context, arg SetProjectArchivedParams) (Project, error) {
	row := q.db.QueryRow(ctx, setProjectArchived, arg.Archived, arg.ID)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.TicketSeq,
		&i.NoteSeq,
		&i.DocSeq,
		&i.ArchivedAt,
	)
	return i, err
}

const unlinkClientsExcept = `-- name: UnlinkClientsExcept :exec
DELETE FROM project_clients
WHERE project_id = $1 AND NOT (client_id = ANY ($2::bigint[]))
`

type UnlinkClientsExceptParams struct {
	ProjectID int64
	ClientIds []int64
}

func (q *Queries) UnlinkClientsExcept(ctx context.Context, arg UnlinkClientsExceptParams) error {
	_, err := q.db.Exec(ctx, unlinkClientsExcept, arg.ProjectID, arg.ClientIds)
	return err
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects SET
  key         = coalesce($1, key),
  name        = coalesce($2, name),
  description = coalesce($3, description)
WHERE id = $4
RETURNING id, key, name, description, created_at, ticket_seq, note_seq, doc_seq, archived_at
`

type UpdateProjectParams struct {
	Key         *string
	Name        *string
	Description *string
	ID          int64
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.Key,
		arg.Name,
		arg.Description,
		arg.ID,
	)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.TicketSeq,
		&i.NoteSeq,
		&i.DocSeq,
		&i.ArchivedAt,
	)
	return i, err
}
