// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: releases.sql

package db

import (
	"context"
	"time"
)

const createRelease = `-- name: CreateRelease :one
INSERT INTO releases (project_id, name, released_on) VALUES ($1, $2, $3) RETURNING id, project_id, name, released_on, created_at
`

type CreateReleaseParams struct {
	ProjectID  int64
	Name       string
	ReleasedOn *time.Time
}

func (q *Queries) CreateRelease(ctx context.Context, arg CreateReleaseParams) (Release, error) {
	row := q.db.QueryRow(ctx, createRelease, arg.ProjectID, arg.Name, arg.ReleasedOn)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.ReleasedOn,
		&i.CreatedAt,
	)
	return i, err
}

const getRelease = `-- name: GetRelease :one
SELECT id, project_id, name, released_on, created_at FROM releases WHERE id = $1
`

func (q *Queries) GetRelease(ctx context.Context, id int64) (Release, error) {
	row := q.db.QueryRow(ctx, getRelease, id)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.ReleasedOn,
		&i.CreatedAt,
	)
	return i, err
}

const listReleases = `-- name: ListReleases :many
SELECT id, project_id, name, released_on, created_at FROM releases WHERE project_id = $1 ORDER BY released_on DESC NULLS FIRST, id DESC
`

// MSL-67: a project's releases, unreleased ones first, then the latest.
func (q *Queries) ListReleases(ctx context.Context, projectID int64) ([]Release, error) {
	rows, err := q.db.Query(ctx, listReleases, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Release
	for rows.Next() {
		var i Release
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.ReleasedOn,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRelease = `-- name: UpdateRelease :one
UPDATE releases SET name = $2, released_on = $3 WHERE id = $1 RETURNING id, project_id, name, released_on, created_at
`

type UpdateReleaseParams struct {
	ID         int64
	Name       string
	ReleasedOn *time.Time
}

func (q *Queries) UpdateRelease(ctx context.Context, arg UpdateReleaseParams) (Release, error) {
	row := q.db.QueryRow(ctx, updateRelease, arg.ID, arg.Name, arg.ReleasedOn)
	var i Release
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.ReleasedOn,
		&i.CreatedAt,
	)
	return i, err
}
