// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search.sql

package db

import (
	"context"
)

const searchNodes = `-- name: SearchNodes :many
WITH RECURSIVE visible AS (
  SELECT n.id, ARRAY[n.name]::text[] AS path
  FROM nodes n
  WHERE n.parent_id IS NULL AND n.archived_at IS NULL
    AND ($2::boolean OR EXISTS (
          SELECT 1 FROM memberships m
          WHERE m.user_id = $3::bigint AND m.project_id = n.project_id
            AND (NOT n.client_specific OR m.all_clients OR EXISTS (
                  SELECT 1 FROM node_clients nc
                  JOIN membership_clients mc ON mc.client_id = nc.client_id AND mc.project_id = m.project_id AND mc.user_id = m.user_id
                  WHERE nc.node_id = n.id))))
  UNION
  SELECT n.id, v.path || n.name
  FROM nodes n
  JOIN visible v ON n.parent_id = v.id
  WHERE n.archived_at IS NULL
    AND ($2::boolean OR EXISTS (
          SELECT 1 FROM memberships m
          WHERE m.user_id = $3::bigint AND m.project_id = n.project_id
            AND (NOT n.client_specific OR m.all_clients OR EXISTS (
                  SELECT 1 FROM node_clients nc
                  JOIN membership_clients mc ON mc.client_id = nc.client_id AND mc.project_id = m.project_id AND mc.user_id = m.user_id
                  WHERE nc.node_id = n.id))))
)
SELECT n.id, n.name, n.type, n.code, n.aliases, p.key AS project_key, v.path::text[] AS path
FROM visible v
JOIN nodes n ON n.id = v.id
JOIN projects p ON p.id = n.project_id
WHERE n.name ILIKE '%' || $1::text || '%'
   OR n.code ILIKE '%' || $1::text || '%'
   OR array_to_string(n.aliases, ' ') ILIKE '%' || $1::text || '%'
ORDER BY lower(n.name) = lower($1::text) DESC, p.key, v.path
LIMIT 20
`

type SearchNodesParams struct {
	Q       string
	IsAdmin bool
	UserID  int64
}

type SearchNodesRow struct {
	ID         int64
	Name       string
	Type       string
	Code       *string
	Aliases    []string
	ProjectKey string
	Path       []string
}

// Live nodes the user may see (R-AC-5) whose name, alias or code holds q, with
// the names on their path from the top of the tree. A client-specific menu,
// and everything under it, needs one of its clients in the user's scope.
// UNION, not UNION ALL, so a cycle could never loop forever.
func (q *Queries) SearchNodes(ctx context.Context, arg SearchNodesParams) ([]SearchNodesRow, error) {
	rows, err := q.db.Query(ctx, searchNodes, arg.Q, arg.IsAdmin, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchNodesRow
	for rows.Next() {
		var i SearchNodesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Code,
			&i.Aliases,
			&i.ProjectKey,
			&i.Path,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTickets = `-- name: SearchTickets :many
SELECT t.key, t.title, p.key AS project_key, t.client_id, c.name AS client_name, s.id, s.project_id, s.name, s.category, s.position, s.color, s.is_default
FROM tickets t
JOIN projects p ON p.id = t.project_id
JOIN statuses s ON s.id = t.status_id
LEFT JOIN clients c ON c.id = t.client_id
WHERE ($1::boolean OR EXISTS (
        SELECT 1 FROM memberships m
        WHERE m.user_id = $2::bigint AND m.project_id = t.project_id
          AND (m.all_clients OR t.client_id IS NULL OR EXISTS (
                SELECT 1 FROM membership_clients mc
                WHERE mc.user_id = m.user_id AND mc.project_id = m.project_id AND mc.client_id = t.client_id))))
  AND (t.key = upper($3::text)
       OR upper(t.external_ref) = upper($3::text)
       OR t.title ILIKE '%' || $3::text || '%'
       OR to_tsvector('simple', t.key || ' ' || t.title || ' ' || t.reason || ' ' || t.description)
          @@ websearch_to_tsquery('simple', $3::text))
ORDER BY t.key = upper($3::text) OR upper(t.external_ref) = upper($3::text) DESC, t.title ILIKE '%' || $3::text || '%' DESC, t.updated_at DESC
LIMIT 50
`

type SearchTicketsParams struct {
	IsAdmin bool
	UserID  int64
	Q       string
}

type SearchTicketsRow struct {
	Key        string
	Title      string
	ProjectKey string
	ClientID   *int64
	ClientName *string
	Status     Status
}

// Tickets the user may see in any project (R-AC-2, R-AC-3): a key or an
// imported ticket's old key (R-IN-2), words
// anywhere in the ticket, or part of the title (FSD §6.1). An exact key comes
// first, then title matches, then the latest updates.
// ponytail: at most 50 results; pages come when people ask for them.
func (q *Queries) SearchTickets(ctx context.Context, arg SearchTicketsParams) ([]SearchTicketsRow, error) {
	rows, err := q.db.Query(ctx, searchTickets, arg.IsAdmin, arg.UserID, arg.Q)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTicketsRow
	for rows.Next() {
		var i SearchTicketsRow
		if err := rows.Scan(
			&i.Key,
			&i.Title,
			&i.ProjectKey,
			&i.ClientID,
			&i.ClientName,
			&i.Status.ID,
			&i.Status.ProjectID,
			&i.Status.Name,
			&i.Status.Category,
			&i.Status.Position,
			&i.Status.Color,
			&i.Status.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
