// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"
)

const getSetting = `-- name: GetSetting :one
SELECT value FROM settings WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const putSetting = `-- name: PutSetting :exec
INSERT INTO settings (key, value, updated_by, updated_at) VALUES ($1, $2, $3, now())
ON CONFLICT (key) DO UPDATE SET value = excluded.value, updated_by = excluded.updated_by, updated_at = now()
`

type PutSettingParams struct {
	Key       string
	Value     []byte
	UpdatedBy *int64
}

func (q *Queries) PutSetting(ctx context.Context, arg PutSettingParams) error {
	_, err := q.db.Exec(ctx, putSetting, arg.Key, arg.Value, arg.UpdatedBy)
	return err
}
