// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: setup_tokens.sql

package db

import (
	"context"
	"time"
)

const createSetupToken = `-- name: CreateSetupToken :exec
INSERT INTO setup_tokens (token_hash, user_id, expires_at) VALUES ($1, $2, $3)
`

type CreateSetupTokenParams struct {
	TokenHash []byte
	UserID    int64
	ExpiresAt time.Time
}

func (q *Queries) CreateSetupToken(ctx context.Context, arg CreateSetupTokenParams) error {
	_, err := q.db.Exec(ctx, createSetupToken, arg.TokenHash, arg.UserID, arg.ExpiresAt)
	return err
}

const useSetupToken = `-- name: UseSetupToken :one
UPDATE setup_tokens SET used_at = now()
WHERE token_hash = $1 AND used_at IS NULL AND expires_at > now()
RETURNING user_id
`

func (q *Queries) UseSetupToken(ctx context.Context, tokenHash []byte) (int64, error) {
	row := q.db.QueryRow(ctx, useSetupToken, tokenHash)
	var user_id int64
	err := row.Scan(&user_id)
	return user_id, err
}

const voidSetupTokens = `-- name: VoidSetupTokens :exec
UPDATE setup_tokens SET used_at = now() WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) VoidSetupTokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, voidSetupTokens, userID)
	return err
}
