// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statuses.sql

package db

import (
	"context"
)

const clearDefaultStatus = `-- name: ClearDefaultStatus :exec
UPDATE statuses SET is_default = false WHERE project_id = $1
`

// Runs before a statuses update, so the new default never meets the old one.
func (q *Queries) ClearDefaultStatus(ctx context.Context, projectID int64) error {
	_, err := q.db.Exec(ctx, clearDefaultStatus, projectID)
	return err
}

const deleteStatusesExcept = `-- name: DeleteStatusesExcept :exec
DELETE FROM statuses
WHERE project_id = $1 AND NOT (id = ANY ($2::bigint[]))
`

type DeleteStatusesExceptParams struct {
	ProjectID int64
	KeepIds   []int64
}

func (q *Queries) DeleteStatusesExcept(ctx context.Context, arg DeleteStatusesExceptParams) error {
	_, err := q.db.Exec(ctx, deleteStatusesExcept, arg.ProjectID, arg.KeepIds)
	return err
}

const getDefaultStatus = `-- name: GetDefaultStatus :one
SELECT id, project_id, name, category, position, color, is_default FROM statuses WHERE project_id = $1 AND is_default
`

func (q *Queries) GetDefaultStatus(ctx context.Context, projectID int64) (Status, error) {
	row := q.db.QueryRow(ctx, getDefaultStatus, projectID)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Category,
		&i.Position,
		&i.Color,
		&i.IsDefault,
	)
	return i, err
}

const getStatus = `-- name: GetStatus :one
SELECT id, project_id, name, category, position, color, is_default FROM statuses WHERE id = $1
`

func (q *Queries) GetStatus(ctx context.Context, id int64) (Status, error) {
	row := q.db.QueryRow(ctx, getStatus, id)
	var i Status
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Category,
		&i.Position,
		&i.Color,
		&i.IsDefault,
	)
	return i, err
}

const insertStatus = `-- name: InsertStatus :one
INSERT INTO statuses (project_id, name, category, position, color, is_default)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertStatusParams struct {
	ProjectID int64
	Name      string
	Category  string
	Position  int32
	Color     string
	IsDefault bool
}

func (q *Queries) InsertStatus(ctx context.Context, arg InsertStatusParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertStatus,
		arg.ProjectID,
		arg.Name,
		arg.Category,
		arg.Position,
		arg.Color,
		arg.IsDefault,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listStatusIDsInUse = `-- name: ListStatusIDsInUse :many
SELECT DISTINCT status_id FROM tickets WHERE project_id = $1
`

func (q *Queries) ListStatusIDsInUse(ctx context.Context, projectID int64) ([]int64, error) {
	rows, err := q.db.Query(ctx, listStatusIDsInUse, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var status_id int64
		if err := rows.Scan(&status_id); err != nil {
			return nil, err
		}
		items = append(items, status_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatuses = `-- name: ListStatuses :many
SELECT id, project_id, name, category, position, color, is_default FROM statuses WHERE project_id = $1 ORDER BY position, id
`

func (q *Queries) ListStatuses(ctx context.Context, projectID int64) ([]Status, error) {
	rows, err := q.db.Query(ctx, listStatuses, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Status
	for rows.Next() {
		var i Status
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Category,
			&i.Position,
			&i.Color,
			&i.IsDefault,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveTicketsToStatus = `-- name: MoveTicketsToStatus :exec
UPDATE tickets SET status_id = $1, version = version + 1, updated_at = now()
WHERE project_id = $2 AND status_id = $3
`

type MoveTicketsToStatusParams struct {
	ToID      int64
	ProjectID int64
	FromID    int64
}

func (q *Queries) MoveTicketsToStatus(ctx context.Context, arg MoveTicketsToStatusParams) error {
	_, err := q.db.Exec(ctx, moveTicketsToStatus, arg.ToID, arg.ProjectID, arg.FromID)
	return err
}

const updateStatus = `-- name: UpdateStatus :execrows
UPDATE statuses SET name = $3, category = $4, position = $5, color = $6, is_default = $7
WHERE id = $1 AND project_id = $2
`

type UpdateStatusParams struct {
	ID        int64
	ProjectID int64
	Name      string
	Category  string
	Position  int32
	Color     string
	IsDefault bool
}

func (q *Queries) UpdateStatus(ctx context.Context, arg UpdateStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStatus,
		arg.ID,
		arg.ProjectID,
		arg.Name,
		arg.Category,
		arg.Position,
		arg.Color,
		arg.IsDefault,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
