// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: summaries.sql

package db

import (
	"context"
	"time"
)

const createSummary = `-- name: CreateSummary :one
INSERT INTO summaries (project_id, created_by, title, params, items, markdown, model)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, created_by, title, params, items, markdown, model, created_at, updated_at
`

type CreateSummaryParams struct {
	ProjectID int64
	CreatedBy int64
	Title     string
	Params    []byte
	Items     []byte
	Markdown  string
	Model     string
}

func (q *Queries) CreateSummary(ctx context.Context, arg CreateSummaryParams) (Summary, error) {
	row := q.db.QueryRow(ctx, createSummary,
		arg.ProjectID,
		arg.CreatedBy,
		arg.Title,
		arg.Params,
		arg.Items,
		arg.Markdown,
		arg.Model,
	)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Title,
		&i.Params,
		&i.Items,
		&i.Markdown,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSummary = `-- name: GetSummary :one
SELECT s.id, s.project_id, s.created_by, s.title, s.params, s.items, s.markdown, s.model, s.created_at, s.updated_at, u.name AS creator_name, p.key AS project_key
FROM summaries s
JOIN users u ON u.id = s.created_by
JOIN projects p ON p.id = s.project_id
WHERE s.id = $1
`

type GetSummaryRow struct {
	Summary     Summary
	CreatorName string
	ProjectKey  string
}

func (q *Queries) GetSummary(ctx context.Context, id int64) (GetSummaryRow, error) {
	row := q.db.QueryRow(ctx, getSummary, id)
	var i GetSummaryRow
	err := row.Scan(
		&i.Summary.ID,
		&i.Summary.ProjectID,
		&i.Summary.CreatedBy,
		&i.Summary.Title,
		&i.Summary.Params,
		&i.Summary.Items,
		&i.Summary.Markdown,
		&i.Summary.Model,
		&i.Summary.CreatedAt,
		&i.Summary.UpdatedAt,
		&i.CreatorName,
		&i.ProjectKey,
	)
	return i, err
}

const listCommentsOfTickets = `-- name: ListCommentsOfTickets :many
SELECT c.ticket_id, c.body, c.created_at
FROM comments c
WHERE c.ticket_id = ANY ($1::bigint[]) AND c.deleted_at IS NULL
  AND (NOT $2::boolean OR NOT c.internal)
ORDER BY c.ticket_id, c.created_at, c.id
`

type ListCommentsOfTicketsParams struct {
	TicketIds  []int64
	ClientSafe bool
}

type ListCommentsOfTicketsRow struct {
	TicketID  int64
	Body      string
	CreatedAt time.Time
}

// Live comments for a summary's model input; client-facing summaries take
// Client-safe comments only (AC-TK-10).
func (q *Queries) ListCommentsOfTickets(ctx context.Context, arg ListCommentsOfTicketsParams) ([]ListCommentsOfTicketsRow, error) {
	rows, err := q.db.Query(ctx, listCommentsOfTickets, arg.TicketIds, arg.ClientSafe)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsOfTicketsRow
	for rows.Next() {
		var i ListCommentsOfTicketsRow
		if err := rows.Scan(&i.TicketID, &i.Body, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDraftComments = `-- name: ListDraftComments :many
SELECT body, created_at, author_name FROM (
  SELECT c.body, c.created_at, c.id, coalesce(u.name, c.author_label, '')::text AS author_name
  FROM comments c LEFT JOIN users u ON u.id = c.author_id
  WHERE c.ticket_id = $1 AND c.deleted_at IS NULL
  ORDER BY c.created_at DESC, c.id DESC
  LIMIT 30
) x ORDER BY created_at, id
`

type ListDraftCommentsRow struct {
	Body       string
	CreatedAt  time.Time
	AuthorName string
}

// The latest 30 live comments, oldest first, for an AI draft (§9.3).
func (q *Queries) ListDraftComments(ctx context.Context, ticketID int64) ([]ListDraftCommentsRow, error) {
	rows, err := q.db.Query(ctx, listDraftComments, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDraftCommentsRow
	for rows.Next() {
		var i ListDraftCommentsRow
		if err := rows.Scan(&i.Body, &i.CreatedAt, &i.AuthorName); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesOfNotes = `-- name: ListNodesOfNotes :many
SELECT dn.note_id, dn.node_id FROM decision_note_nodes dn WHERE dn.note_id = ANY ($1::bigint[]) ORDER BY dn.note_id, dn.node_id
`

func (q *Queries) ListNodesOfNotes(ctx context.Context, noteIds []int64) ([]DecisionNoteNode, error) {
	rows, err := q.db.Query(ctx, listNodesOfNotes, noteIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DecisionNoteNode
	for rows.Next() {
		var i DecisionNoteNode
		if err := rows.Scan(&i.NoteID, &i.NodeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNodesOfTickets = `-- name: ListNodesOfTickets :many
SELECT tn.ticket_id, tn.node_id FROM ticket_nodes tn WHERE tn.ticket_id = ANY ($1::bigint[]) ORDER BY tn.ticket_id, tn.node_id
`

func (q *Queries) ListNodesOfTickets(ctx context.Context, ticketIds []int64) ([]TicketNode, error) {
	rows, err := q.db.Query(ctx, listNodesOfTickets, ticketIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TicketNode
	for rows.Next() {
		var i TicketNode
		if err := rows.Scan(&i.TicketID, &i.NodeID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSummaries = `-- name: ListSummaries :many
SELECT s.id, s.title, s.created_at, s.updated_at, u.name AS creator_name, p.key AS project_key
FROM summaries s
JOIN users u ON u.id = s.created_by
JOIN projects p ON p.id = s.project_id
WHERE ($1::bigint IS NULL OR s.project_id = $1::bigint)
  AND ($2::boolean OR s.created_by = $3::bigint OR EXISTS (
        SELECT 1 FROM memberships m WHERE m.user_id = $3::bigint AND m.project_id = s.project_id AND m.role = 'admin'))
ORDER BY s.created_at DESC
LIMIT 100
`

type ListSummariesParams struct {
	ProjectID *int64
	IsAdmin   bool
	UserID    int64
}

type ListSummariesRow struct {
	ID          int64
	Title       string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	CreatorName string
	ProjectKey  string
}

// A summary is visible to its creator and to project admins (§12.1).
func (q *Queries) ListSummaries(ctx context.Context, arg ListSummariesParams) ([]ListSummariesRow, error) {
	rows, err := q.db.Query(ctx, listSummaries, arg.ProjectID, arg.IsAdmin, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSummariesRow
	for rows.Next() {
		var i ListSummariesRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CreatorName,
			&i.ProjectKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSummary = `-- name: UpdateSummary :one
UPDATE summaries SET title = $1, markdown = $2, updated_at = now()
WHERE id = $3
RETURNING id, project_id, created_by, title, params, items, markdown, model, created_at, updated_at
`

type UpdateSummaryParams struct {
	Title    string
	Markdown string
	ID       int64
}

func (q *Queries) UpdateSummary(ctx context.Context, arg UpdateSummaryParams) (Summary, error) {
	row := q.db.QueryRow(ctx, updateSummary, arg.Title, arg.Markdown, arg.ID)
	var i Summary
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.Title,
		&i.Params,
		&i.Items,
		&i.Markdown,
		&i.Model,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
