// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tickets.sql

package db

import (
	"context"
	"time"
)

const addTicketNodes = `-- name: AddTicketNodes :exec
INSERT INTO ticket_nodes (ticket_id, node_id)
SELECT $1::bigint, unnest($2::bigint[])
`

type AddTicketNodesParams struct {
	TicketID int64
	NodeIds  []int64
}

func (q *Queries) AddTicketNodes(ctx context.Context, arg AddTicketNodesParams) error {
	_, err := q.db.Exec(ctx, addTicketNodes, arg.TicketID, arg.NodeIds)
	return err
}

const clearTicketNodes = `-- name: ClearTicketNodes :exec
DELETE FROM ticket_nodes WHERE ticket_id = $1
`

func (q *Queries) ClearTicketNodes(ctx context.Context, ticketID int64) error {
	_, err := q.db.Exec(ctx, clearTicketNodes, ticketID)
	return err
}

const createTicket = `-- name: CreateTicket :one
INSERT INTO tickets (project_id, number, key, type, title, description, reason, status_id, client_id,
                     requester_contact_id, requester_user_id, reporter_id, assignee_id, priority, due_date, estimate_hours)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
RETURNING id, project_id, number, key, type, title, description, reason, status_id, client_id, requester_contact_id, requester_user_id, reporter_id, assignee_id, priority, due_date, version, created_at, updated_at, closed_at, source, external_ref, external_meta, estimate_hours
`

type CreateTicketParams struct {
	ProjectID          int64
	Number             int64
	Key                string
	Type               string
	Title              string
	Description        string
	Reason             string
	StatusID           int64
	ClientID           *int64
	RequesterContactID *int64
	RequesterUserID    *int64
	ReporterID         int64
	AssigneeID         *int64
	Priority           string
	DueDate            *time.Time
	EstimateHours      *float64
}

func (q *Queries) CreateTicket(ctx context.Context, arg CreateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, createTicket,
		arg.ProjectID,
		arg.Number,
		arg.Key,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Reason,
		arg.StatusID,
		arg.ClientID,
		arg.RequesterContactID,
		arg.RequesterUserID,
		arg.ReporterID,
		arg.AssigneeID,
		arg.Priority,
		arg.DueDate,
		arg.EstimateHours,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Key,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Reason,
		&i.StatusID,
		&i.ClientID,
		&i.RequesterContactID,
		&i.RequesterUserID,
		&i.ReporterID,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.Source,
		&i.ExternalRef,
		&i.ExternalMeta,
		&i.EstimateHours,
	)
	return i, err
}

const getTicketByKey = `-- name: GetTicketByKey :one
SELECT t.id, t.project_id, t.number, t.key, t.type, t.title, t.description, t.reason, t.status_id, t.client_id, t.requester_contact_id, t.requester_user_id, t.reporter_id, t.assignee_id, t.priority, t.due_date, t.version, t.created_at, t.updated_at, t.closed_at, t.source, t.external_ref, t.external_meta, t.estimate_hours, s.id, s.project_id, s.name, s.category, s.position, s.color, s.is_default, p.key AS project_key, rp.name AS reporter_name, c.name AS client_name,
       rc.name AS requester_contact_name, rc.title AS requester_contact_title,
       ru.name AS requester_user_name, a.name AS assignee_name
FROM tickets t
JOIN statuses s ON s.id = t.status_id
JOIN projects p ON p.id = t.project_id
JOIN users rp ON rp.id = t.reporter_id
LEFT JOIN clients c ON c.id = t.client_id
LEFT JOIN contacts rc ON rc.id = t.requester_contact_id
LEFT JOIN users ru ON ru.id = t.requester_user_id
LEFT JOIN users a ON a.id = t.assignee_id
WHERE t.key = $1
`

type GetTicketByKeyRow struct {
	Ticket                Ticket
	Status                Status
	ProjectKey            string
	ReporterName          string
	ClientName            *string
	RequesterContactName  *string
	RequesterContactTitle *string
	RequesterUserName     *string
	AssigneeName          *string
}

func (q *Queries) GetTicketByKey(ctx context.Context, key string) (GetTicketByKeyRow, error) {
	row := q.db.QueryRow(ctx, getTicketByKey, key)
	var i GetTicketByKeyRow
	err := row.Scan(
		&i.Ticket.ID,
		&i.Ticket.ProjectID,
		&i.Ticket.Number,
		&i.Ticket.Key,
		&i.Ticket.Type,
		&i.Ticket.Title,
		&i.Ticket.Description,
		&i.Ticket.Reason,
		&i.Ticket.StatusID,
		&i.Ticket.ClientID,
		&i.Ticket.RequesterContactID,
		&i.Ticket.RequesterUserID,
		&i.Ticket.ReporterID,
		&i.Ticket.AssigneeID,
		&i.Ticket.Priority,
		&i.Ticket.DueDate,
		&i.Ticket.Version,
		&i.Ticket.CreatedAt,
		&i.Ticket.UpdatedAt,
		&i.Ticket.ClosedAt,
		&i.Ticket.Source,
		&i.Ticket.ExternalRef,
		&i.Ticket.ExternalMeta,
		&i.Ticket.EstimateHours,
		&i.Status.ID,
		&i.Status.ProjectID,
		&i.Status.Name,
		&i.Status.Category,
		&i.Status.Position,
		&i.Status.Color,
		&i.Status.IsDefault,
		&i.ProjectKey,
		&i.ReporterName,
		&i.ClientName,
		&i.RequesterContactName,
		&i.RequesterContactTitle,
		&i.RequesterUserName,
		&i.AssigneeName,
	)
	return i, err
}

const listTicketNodes = `-- name: ListTicketNodes :many
SELECT n.id, n.name, (n.archived_at IS NOT NULL)::boolean AS archived
FROM ticket_nodes tn
JOIN nodes n ON n.id = tn.node_id
WHERE tn.ticket_id = $1
ORDER BY lower(n.name), n.id
`

type ListTicketNodesRow struct {
	ID       int64
	Name     string
	Archived bool
}

func (q *Queries) ListTicketNodes(ctx context.Context, ticketID int64) ([]ListTicketNodesRow, error) {
	rows, err := q.db.Query(ctx, listTicketNodes, ticketID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketNodesRow
	for rows.Next() {
		var i ListTicketNodesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Archived); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTickets = `-- name: ListTickets :many
SELECT t.id, t.key, t.title, t.type, t.priority, t.due_date, t.status_id, t.client_id, c.name AS client_name,
       t.assignee_id, a.name AS assignee_name, coalesce(rc.name, ru.name, '')::text AS requester_name,
       t.reason = '' AS missing_reason, t.updated_at,
       ARRAY(SELECT n.name FROM ticket_nodes tn JOIN nodes n ON n.id = tn.node_id
             WHERE tn.ticket_id = t.id ORDER BY lower(n.name), n.id)::text[] AS node_names
FROM tickets t
JOIN statuses s ON s.id = t.status_id
LEFT JOIN clients c ON c.id = t.client_id
LEFT JOIN users a ON a.id = t.assignee_id
LEFT JOIN contacts rc ON rc.id = t.requester_contact_id
LEFT JOIN users ru ON ru.id = t.requester_user_id
WHERE t.project_id = $1
  AND ($2::boolean OR t.client_id IS NULL OR t.client_id = ANY ($3::bigint[]))
  AND ($4::bigint IS NULL OR t.status_id = $4::bigint)
  AND ($5::text IS NULL OR s.category = $5::text)
  AND (NOT $6::boolean OR s.category IN ('todo', 'in_progress'))
  AND ($7::int IS NULL OR t.closed_at IS NULL OR t.closed_at >= now() - make_interval(days => $7::int))
  AND ($8::text IS NULL OR t.type = $8::text)
  AND ($9::bigint IS NULL OR t.client_id = $9::bigint)
  AND (NOT $10::boolean OR t.client_id IS NULL)
  AND ($11::bigint IS NULL OR t.assignee_id = $11::bigint)
  AND (NOT $12::boolean OR t.assignee_id IS NULL)
  -- due and stale_days count open tickets only, as Home and the workload page do;
  -- due counts from today on the caller's calendar.
  AND ($13::text IS NULL OR (s.category IN ('todo', 'in_progress') AND (
        ($13::text = 'overdue' AND t.due_date < $14::date)
        OR ($13::text = 'week' AND t.due_date BETWEEN $14::date AND $14::date + 7))))
  AND ($15::int IS NULL OR (s.category IN ('todo', 'in_progress')
        AND t.updated_at < now() - make_interval(days => $15::int)))
  AND ($16::bigint[] IS NULL OR EXISTS (
        SELECT 1 FROM ticket_nodes tn WHERE tn.ticket_id = t.id AND tn.node_id = ANY ($16::bigint[])))
  AND (NOT $17::boolean OR t.reason = '')
  -- Tickets filed through the API or an import never show the form's
  -- weak-reason hint, so the list finds them (MSL-12, 00017).
  AND (NOT $18::boolean OR weak_reason(t.reason))
  AND (NOT $19::boolean OR NOT EXISTS (SELECT 1 FROM ticket_nodes tn WHERE tn.ticket_id = t.id))
  AND ($20::text = '' OR t.title ILIKE '%' || $20::text || '%' OR t.key = upper($20::text))
ORDER BY
  CASE WHEN $21::text = 'priority' THEN array_position(ARRAY['urgent', 'high', 'medium', 'low'], t.priority) END,
  CASE WHEN $21::text IN ('priority', 'due') THEN t.due_date END NULLS LAST,
  CASE WHEN $21::text = 'updated' THEN t.updated_at END DESC,
  CASE WHEN $21::text = 'created' THEN t.number END DESC,
  t.number
LIMIT $23 OFFSET $22
`

type ListTicketsParams struct {
	ProjectID     int64
	AllClients    bool
	ClientIds     []int64
	StatusID      *int64
	Category      *string
	OpenOnly      bool
	ClosedDays    *int32
	Type          *string
	ClientID      *int64
	CoreOnly      bool
	AssigneeID    *int64
	Unassigned    bool
	Due           *string
	Today         time.Time
	StaleDays     *int32
	NodeIds       []int64
	MissingReason bool
	WeakReason    bool
	MissingMenus  bool
	Q             string
	Sort          string
	Off           int32
	Lim           int32
}

type ListTicketsRow struct {
	ID            int64
	Key           string
	Title         string
	Type          string
	Priority      string
	DueDate       *time.Time
	StatusID      int64
	ClientID      *int64
	ClientName    *string
	AssigneeID    *int64
	AssigneeName  *string
	RequesterName string
	MissingReason bool
	UpdatedAt     time.Time
	NodeNames     []string
}

// One project's tickets that the scope may see (R-AC-2, R-AC-3), for the list
// and the board. A filter is off when its argument is NULL or false.
func (q *Queries) ListTickets(ctx context.Context, arg ListTicketsParams) ([]ListTicketsRow, error) {
	rows, err := q.db.Query(ctx, listTickets,
		arg.ProjectID,
		arg.AllClients,
		arg.ClientIds,
		arg.StatusID,
		arg.Category,
		arg.OpenOnly,
		arg.ClosedDays,
		arg.Type,
		arg.ClientID,
		arg.CoreOnly,
		arg.AssigneeID,
		arg.Unassigned,
		arg.Due,
		arg.Today,
		arg.StaleDays,
		arg.NodeIds,
		arg.MissingReason,
		arg.WeakReason,
		arg.MissingMenus,
		arg.Q,
		arg.Sort,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTicketsRow
	for rows.Next() {
		var i ListTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Title,
			&i.Type,
			&i.Priority,
			&i.DueDate,
			&i.StatusID,
			&i.ClientID,
			&i.ClientName,
			&i.AssigneeID,
			&i.AssigneeName,
			&i.RequesterName,
			&i.MissingReason,
			&i.UpdatedAt,
			&i.NodeNames,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextTicketNumber = `-- name: NextTicketNumber :one
UPDATE projects SET ticket_seq = ticket_seq + 1 WHERE id = $1 RETURNING ticket_seq
`

// The row lock makes ticket numbers gapless and unique per project (FSD §8.1).
func (q *Queries) NextTicketNumber(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, nextTicketNumber, id)
	var ticket_seq int64
	err := row.Scan(&ticket_seq)
	return ticket_seq, err
}

const setTicketReason = `-- name: SetTicketReason :exec
UPDATE tickets SET reason = $2 WHERE id = $1
`

type SetTicketReasonParams struct {
	ID     int64
	Reason string
}

func (q *Queries) SetTicketReason(ctx context.Context, arg SetTicketReasonParams) error {
	_, err := q.db.Exec(ctx, setTicketReason, arg.ID, arg.Reason)
	return err
}

const setTicketStatus = `-- name: SetTicketStatus :one
UPDATE tickets SET status_id = $1,
  closed_at  = CASE WHEN $2::boolean THEN now() END,
  version    = version + 1,
  updated_at = now()
WHERE id = $3 AND ($4::int IS NULL OR version = $4::int)
RETURNING id, project_id, number, key, type, title, description, reason, status_id, client_id, requester_contact_id, requester_user_id, reporter_id, assignee_id, priority, due_date, version, created_at, updated_at, closed_at, source, external_ref, external_meta, estimate_hours
`

type SetTicketStatusParams struct {
	StatusID int64
	Closed   bool
	ID       int64
	Version  *int32
}

// A close stamps closed_at and any other move clears it (FSD §8.1). With a
// version, a stale one matches no row (If-Match).
func (q *Queries) SetTicketStatus(ctx context.Context, arg SetTicketStatusParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, setTicketStatus,
		arg.StatusID,
		arg.Closed,
		arg.ID,
		arg.Version,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Key,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Reason,
		&i.StatusID,
		&i.ClientID,
		&i.RequesterContactID,
		&i.RequesterUserID,
		&i.ReporterID,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.Source,
		&i.ExternalRef,
		&i.ExternalMeta,
		&i.EstimateHours,
	)
	return i, err
}

const updateTicket = `-- name: UpdateTicket :one
UPDATE tickets SET type = $3, title = $4, description = $5, reason = $6, client_id = $7,
  requester_contact_id = $8, requester_user_id = $9, assignee_id = $10, priority = $11, due_date = $12,
  estimate_hours = $13, version = version + 1, updated_at = now()
WHERE id = $1 AND version = $2
RETURNING id, project_id, number, key, type, title, description, reason, status_id, client_id, requester_contact_id, requester_user_id, reporter_id, assignee_id, priority, due_date, version, created_at, updated_at, closed_at, source, external_ref, external_meta, estimate_hours
`

type UpdateTicketParams struct {
	ID                 int64
	Version            int32
	Type               string
	Title              string
	Description        string
	Reason             string
	ClientID           *int64
	RequesterContactID *int64
	RequesterUserID    *int64
	AssigneeID         *int64
	Priority           string
	DueDate            *time.Time
	EstimateHours      *float64
}

// Optimistic locking: no row comes back when the version moved on (FSD §8.6).
func (q *Queries) UpdateTicket(ctx context.Context, arg UpdateTicketParams) (Ticket, error) {
	row := q.db.QueryRow(ctx, updateTicket,
		arg.ID,
		arg.Version,
		arg.Type,
		arg.Title,
		arg.Description,
		arg.Reason,
		arg.ClientID,
		arg.RequesterContactID,
		arg.RequesterUserID,
		arg.AssigneeID,
		arg.Priority,
		arg.DueDate,
		arg.EstimateHours,
	)
	var i Ticket
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Number,
		&i.Key,
		&i.Type,
		&i.Title,
		&i.Description,
		&i.Reason,
		&i.StatusID,
		&i.ClientID,
		&i.RequesterContactID,
		&i.RequesterUserID,
		&i.ReporterID,
		&i.AssigneeID,
		&i.Priority,
		&i.DueDate,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ClosedAt,
		&i.Source,
		&i.ExternalRef,
		&i.ExternalMeta,
		&i.EstimateHours,
	)
	return i, err
}
