// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tokens.sql

package db

import (
	"context"
	"time"
)

const createAPIToken = `-- name: CreateAPIToken :one

INSERT INTO api_tokens (user_id, name, token_hash, read_only, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, token_hash, read_only, expires_at, last_used_at, revoked_at, created_at
`

type CreateAPITokenParams struct {
	UserID    int64
	Name      string
	TokenHash []byte
	ReadOnly  bool
	ExpiresAt *time.Time
}

// Personal API tokens (FSD §14.3) and idempotency keys (§17.1).
func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, createAPIToken,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.ReadOnly,
		arg.ExpiresAt,
	)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.ReadOnly,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getAPITokenUser = `-- name: GetAPITokenUser :one
SELECT t.id, t.user_id, t.name, t.token_hash, t.read_only, t.expires_at, t.last_used_at, t.revoked_at, t.created_at, u.id, u.email, u.name, u.password_hash, u.is_admin, u.locale, u.timezone, u.failed_logins, u.failed_since, u.locked_until, u.disabled_at, u.last_login_at, u.created_at, u.notify_prefs
FROM api_tokens t JOIN users u ON u.id = t.user_id
WHERE t.token_hash = $1
`

type GetAPITokenUserRow struct {
	ApiToken ApiToken
	User     User
}

func (q *Queries) GetAPITokenUser(ctx context.Context, tokenHash []byte) (GetAPITokenUserRow, error) {
	row := q.db.QueryRow(ctx, getAPITokenUser, tokenHash)
	var i GetAPITokenUserRow
	err := row.Scan(
		&i.ApiToken.ID,
		&i.ApiToken.UserID,
		&i.ApiToken.Name,
		&i.ApiToken.TokenHash,
		&i.ApiToken.ReadOnly,
		&i.ApiToken.ExpiresAt,
		&i.ApiToken.LastUsedAt,
		&i.ApiToken.RevokedAt,
		&i.ApiToken.CreatedAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.Name,
		&i.User.PasswordHash,
		&i.User.IsAdmin,
		&i.User.Locale,
		&i.User.Timezone,
		&i.User.FailedLogins,
		&i.User.FailedSince,
		&i.User.LockedUntil,
		&i.User.DisabledAt,
		&i.User.LastLoginAt,
		&i.User.CreatedAt,
		&i.User.NotifyPrefs,
	)
	return i, err
}

const getIdempotentTicket = `-- name: GetIdempotentTicket :one
SELECT t.key FROM idempotency_keys k JOIN tickets t ON t.id = k.ticket_id
WHERE k.user_id = $1 AND k.key = $2 AND k.created_at > now() - interval '24 hours'
`

type GetIdempotentTicketParams struct {
	UserID int64
	Key    string
}

func (q *Queries) GetIdempotentTicket(ctx context.Context, arg GetIdempotentTicketParams) (string, error) {
	row := q.db.QueryRow(ctx, getIdempotentTicket, arg.UserID, arg.Key)
	var key string
	err := row.Scan(&key)
	return key, err
}

const listAPITokens = `-- name: ListAPITokens :many
SELECT id, user_id, name, token_hash, read_only, expires_at, last_used_at, revoked_at, created_at FROM api_tokens WHERE user_id = $1 AND revoked_at IS NULL ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListAPITokens(ctx context.Context, userID int64) ([]ApiToken, error) {
	rows, err := q.db.Query(ctx, listAPITokens, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ApiToken
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.ReadOnly,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIdempotencyKey = `-- name: LockIdempotencyKey :exec
SELECT pg_advisory_xact_lock(hashtextextended('idempotency:' || $1::bigint::text || ':' || $2::text, 0))
`

type LockIdempotencyKeyParams struct {
	UserID int64
	Key    string
}

func (q *Queries) LockIdempotencyKey(ctx context.Context, arg LockIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, lockIdempotencyKey, arg.UserID, arg.Key)
	return err
}

const purgeIdempotencyKeys = `-- name: PurgeIdempotencyKeys :execrows
DELETE FROM idempotency_keys WHERE created_at < now() - interval '24 hours'
`

func (q *Queries) PurgeIdempotencyKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeIdempotencyKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeAPIToken = `-- name: RevokeAPIToken :one
UPDATE api_tokens SET revoked_at = now() WHERE id = $1 AND user_id = $2 AND revoked_at IS NULL
RETURNING id, user_id, name, token_hash, read_only, expires_at, last_used_at, revoked_at, created_at
`

type RevokeAPITokenParams struct {
	ID     int64
	UserID int64
}

func (q *Queries) RevokeAPIToken(ctx context.Context, arg RevokeAPITokenParams) (ApiToken, error) {
	row := q.db.QueryRow(ctx, revokeAPIToken, arg.ID, arg.UserID)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.ReadOnly,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const revokeUserAPITokens = `-- name: RevokeUserAPITokens :exec
UPDATE api_tokens SET revoked_at = now() WHERE user_id = $1 AND revoked_at IS NULL
`

// A password reset or change ends every token the user holds.
func (q *Queries) RevokeUserAPITokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeUserAPITokens, userID)
	return err
}

const saveIdempotencyKey = `-- name: SaveIdempotencyKey :exec
INSERT INTO idempotency_keys (user_id, key, ticket_id) VALUES ($1, $2, $3)
ON CONFLICT (user_id, key) DO UPDATE SET ticket_id = excluded.ticket_id, created_at = now()
WHERE idempotency_keys.created_at <= now() - interval '24 hours'
`

type SaveIdempotencyKeyParams struct {
	UserID   int64
	Key      string
	TicketID int64
}

// A key older than 24 hours is free again.
func (q *Queries) SaveIdempotencyKey(ctx context.Context, arg SaveIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, saveIdempotencyKey, arg.UserID, arg.Key, arg.TicketID)
	return err
}

const touchAPIToken = `-- name: TouchAPIToken :exec
UPDATE api_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIToken(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, touchAPIToken, id)
	return err
}
