// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, is_admin, locale, timezone)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, email, name, password_hash, is_admin, locale, timezone, failed_logins, failed_since, locked_until, disabled_at, last_login_at, created_at, notify_prefs
`

type CreateUserParams struct {
	Email    string
	Name     string
	IsAdmin  bool
	Locale   string
	Timezone string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Name,
		arg.IsAdmin,
		arg.Locale,
		arg.Timezone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Locale,
		&i.Timezone,
		&i.FailedLogins,
		&i.FailedSince,
		&i.LockedUntil,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.NotifyPrefs,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, is_admin, locale, timezone, failed_logins, failed_since, locked_until, disabled_at, last_login_at, created_at, notify_prefs FROM users WHERE lower(email) = lower($1)
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Locale,
		&i.Timezone,
		&i.FailedLogins,
		&i.FailedSince,
		&i.LockedUntil,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.NotifyPrefs,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, is_admin, locale, timezone, failed_logins, failed_since, locked_until, disabled_at, last_login_at, created_at, notify_prefs FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Locale,
		&i.Timezone,
		&i.FailedLogins,
		&i.FailedSince,
		&i.LockedUntil,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.NotifyPrefs,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, name, password_hash, is_admin, locale, timezone, failed_logins, failed_since, locked_until, disabled_at, last_login_at, created_at, notify_prefs FROM users ORDER BY lower(name), id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.IsAdmin,
			&i.Locale,
			&i.Timezone,
			&i.FailedLogins,
			&i.FailedSince,
			&i.LockedUntil,
			&i.DisabledAt,
			&i.LastLoginAt,
			&i.CreatedAt,
			&i.NotifyPrefs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordLoginFailure = `-- name: RecordLoginFailure :exec
UPDATE users SET
  failed_logins = CASE WHEN failed_since IS NULL OR failed_since < now() - interval '15 minutes'
                       THEN 1 ELSE failed_logins + 1 END,
  failed_since  = CASE WHEN failed_since IS NULL OR failed_since < now() - interval '15 minutes'
                       THEN now() ELSE failed_since END,
  locked_until  = CASE WHEN failed_since IS NOT NULL AND failed_since >= now() - interval '15 minutes'
                            AND failed_logins + 1 >= 5
                       THEN now() + interval '15 minutes' ELSE locked_until END
WHERE id = $1
`

// Counts failures inside a 15-minute window; the 5th locks the account for 15 minutes (FSD §15.1).
// Every expression in an UPDATE reads the row's old values.
func (q *Queries) RecordLoginFailure(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, recordLoginFailure, id)
	return err
}

const recordLoginSuccess = `-- name: RecordLoginSuccess :exec
UPDATE users SET failed_logins = 0, failed_since = NULL, locked_until = NULL, last_login_at = now()
WHERE id = $1
`

func (q *Queries) RecordLoginSuccess(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, recordLoginSuccess, id)
	return err
}

const setDisabled = `-- name: SetDisabled :one
UPDATE users
SET disabled_at = CASE WHEN $1::boolean THEN coalesce(disabled_at, now()) ELSE NULL END
WHERE id = $2
RETURNING id, email, name, password_hash, is_admin, locale, timezone, failed_logins, failed_since, locked_until, disabled_at, last_login_at, created_at, notify_prefs
`

type SetDisabledParams struct {
	Disabled bool
	ID       int64
}

func (q *Queries) SetDisabled(ctx context.Context, arg SetDisabledParams) (User, error) {
	row := q.db.QueryRow(ctx, setDisabled, arg.Disabled, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Locale,
		&i.Timezone,
		&i.FailedLogins,
		&i.FailedSince,
		&i.LockedUntil,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.NotifyPrefs,
	)
	return i, err
}

const setPasswordHash = `-- name: SetPasswordHash :exec
UPDATE users
SET password_hash = $1, failed_logins = 0, failed_since = NULL, locked_until = NULL
WHERE id = $2
`

type SetPasswordHashParams struct {
	PasswordHash *string
	ID           int64
}

func (q *Queries) SetPasswordHash(ctx context.Context, arg SetPasswordHashParams) error {
	_, err := q.db.Exec(ctx, setPasswordHash, arg.PasswordHash, arg.ID)
	return err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
  name     = coalesce($1, name),
  is_admin = coalesce($2, is_admin),
  locale   = coalesce($3, locale),
  timezone = coalesce($4, timezone)
WHERE id = $5
RETURNING id, email, name, password_hash, is_admin, locale, timezone, failed_logins, failed_since, locked_until, disabled_at, last_login_at, created_at, notify_prefs
`

type UpdateUserParams struct {
	Name     *string
	IsAdmin  *bool
	Locale   *string
	Timezone *string
	ID       int64
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.IsAdmin,
		arg.Locale,
		arg.Timezone,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.IsAdmin,
		&i.Locale,
		&i.Timezone,
		&i.FailedLogins,
		&i.FailedSince,
		&i.LockedUntil,
		&i.DisabledAt,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.NotifyPrefs,
	)
	return i, err
}
